{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/truvideosdkcamera\/kbufferindexinstanceuniforms"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/truvideosdkcamera\/kbufferindexinstanceuniforms"]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/kBufferIndexInstanceUniforms"},"metadata":{"symbolKind":"var","role":"symbol","title":"kBufferIndexInstanceUniforms","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"kBufferIndexInstanceUniforms"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@BufferIndices","text":"BufferIndices"}],"externalID":"c:@E@BufferIndices@kBufferIndexInstanceUniforms","navigatorTitle":[{"kind":"identifier","text":"kBufferIndexInstanceUniforms"}],"modules":[{"name":"TruvideoSdkCamera"}],"roleHeading":"Global Variable"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/BufferIndices"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"kBufferIndexInstanceUniforms"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/BufferIndices","preciseIdentifier":"c:@E@BufferIndices","kind":"typeIdentifier","text":"BufferIndices"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/BufferIndices":{"navigatorTitle":[{"kind":"identifier","text":"BufferIndices"}],"url":"\/documentation\/truvideosdkcamera\/bufferindices","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BufferIndices"}],"kind":"symbol","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/BufferIndices","type":"topic","title":"BufferIndices","abstract":[],"role":"symbol"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/kBufferIndexInstanceUniforms":{"navigatorTitle":[{"text":"kBufferIndexInstanceUniforms","kind":"identifier"}],"url":"\/documentation\/truvideosdkcamera\/kbufferindexinstanceuniforms","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"kBufferIndexInstanceUniforms"},{"kind":"text","text":": "},{"text":"BufferIndices","kind":"typeIdentifier","preciseIdentifier":"c:@E@BufferIndices"}],"kind":"symbol","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/kBufferIndexInstanceUniforms","type":"topic","title":"kBufferIndexInstanceUniforms","abstract":[],"role":"symbol"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","title":"TruvideoSdkCamera","role":"collection","type":"topic","url":"\/documentation\/truvideosdkcamera","kind":"symbol","abstract":[{"text":"Store and capture photos and videos using a fully integrated camera system.","type":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"kBufferIndexInstanceUniforms"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","value":[{"text":"kBufferIndexInstanceUniforms","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"kBufferIndexInstanceUniforms"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1BufferIndices\/title","value":"BufferIndices","op":"replace"},{"value":[{"text":"BufferIndices","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1BufferIndices\/fragments"},{"op":"replace","value":"kBufferIndexInstanceUniforms","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1kBufferIndexInstanceUniforms\/title"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1kBufferIndexInstanceUniforms\/fragments","op":"replace","value":[{"kind":"identifier","text":"kBufferIndexInstanceUniforms"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}