{"metadata":{"roleHeading":"Global Variable","externalID":"c:@E@TextureIndices@kTextureIndexRGB","title":"kTextureIndexRGB","symbolKind":"var","navigatorTitle":[{"text":"kTextureIndexRGB","kind":"identifier"}],"modules":[{"name":"TruvideoSdkCamera"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kTextureIndexRGB"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TextureIndices","preciseIdentifier":"c:@E@TextureIndices"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/kTextureIndexRGB"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/truvideosdkcamera\/ktextureindexrgb"]},{"paths":["\/documentation\/truvideosdkcamera\/ktextureindexrgb"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"kTextureIndexRGB","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@TextureIndices","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TextureIndices","kind":"typeIdentifier","text":"TextureIndices"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera"]]},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/kTextureIndexRGB":{"title":"kTextureIndexRGB","url":"\/documentation\/truvideosdkcamera\/ktextureindexrgb","abstract":[],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"kTextureIndexRGB"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/kTextureIndexRGB","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"kTextureIndexRGB"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TextureIndices","preciseIdentifier":"c:@E@TextureIndices"}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TextureIndices":{"title":"TextureIndices","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TextureIndices","type":"topic","url":"\/documentation\/truvideosdkcamera\/textureindices","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TextureIndices","kind":"identifier"}],"abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TextureIndices"}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","title":"TruvideoSdkCamera","role":"collection","type":"topic","url":"\/documentation\/truvideosdkcamera","kind":"symbol","abstract":[{"text":"Store and capture photos and videos using a fully integrated camera system.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"kTextureIndexRGB"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","value":[{"kind":"identifier","text":"kTextureIndexRGB"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"kTextureIndexRGB"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"kTextureIndexRGB","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1kTextureIndexRGB\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1kTextureIndexRGB\/fragments","value":[{"kind":"identifier","text":"kTextureIndexRGB"}]},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TextureIndices\/title","value":"TextureIndices"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TextureIndices\/fragments","value":[{"text":"TextureIndices","kind":"identifier"}],"op":"replace"}]}]}