{"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"A configuration object for setting up the AR Camera in "},{"code":"TruvideoSdkCamera","type":"codeVoice"},{"text":".","type":"text"}],"metadata":{"title":"TruvideoSdkARCameraConfiguration","symbolKind":"class","externalID":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkARCameraConfiguration","roleHeading":"Class","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TruvideoSdkARCameraConfiguration","kind":"identifier"}],"modules":[{"name":"TruvideoSdkCamera"}],"navigatorTitle":[{"kind":"identifier","text":"TruvideoSdkARCameraConfiguration"}]},"identifier":{"url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkARCameraConfiguration","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TruvideoSdkARCameraConfiguration"}],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"type":"heading","level":2,"text":"Overview","anchor":"overview"},{"inlineContent":[{"type":"codeVoice","code":"TruvideoSdkARCameraConfiguration"},{"type":"text","text":" allows you to customize the AR Camera’s behavior, including flash settings, capture mode,"},{"text":" ","type":"text"},{"type":"text","text":"and camera orientation."}],"type":"paragraph"},{"level":2,"type":"heading","text":"Example Usage","anchor":"Example-Usage"},{"syntax":"swift","type":"codeListing","code":["let arConfig = TruvideoSdkARCameraConfiguration(","    flashMode: .auto,","    mode: .videoAndPicture(videoMaxCount: 3, pictureMaxCount: 5, durationLimit: 15),","    orientation: .portrait",")"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"This configuration can be passed to "},{"code":"presentTruvideoSdkARCameraView","type":"codeVoice"},{"type":"text","text":" to launch the AR Camera with the specified settings."}]}],"kind":"content"}],"variants":[{"paths":["\/documentation\/truvideosdkcamera\/truvideosdkarcameraconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/truvideosdkcamera\/truvideosdkarcameraconfiguration"]}],"hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera"]]},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"},{"identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/objc(pl)NSObject","doc:\/\/com.truvideo.TruvideoSdkCamera\/s7CVarArgP","doc:\/\/com.truvideo.TruvideoSdkCamera\/s28CustomDebugStringConvertibleP","doc:\/\/com.truvideo.TruvideoSdkCamera\/s23CustomStringConvertibleP","doc:\/\/com.truvideo.TruvideoSdkCamera\/SQ","doc:\/\/com.truvideo.TruvideoSdkCamera\/SH"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkARCameraConfiguration\/init(flashMode:mode:orientation:)"]},{"identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkARCameraConfiguration\/flashMode","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkARCameraConfiguration\/mode","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkARCameraConfiguration\/orientation"],"title":"Instance Properties"},{"title":"Type Methods","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkARCameraConfiguration\/instantiate(with:orientation:mode:)"]}],"seeAlsoSections":[{"identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraFlashMode","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraMediaMode","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraOrientation"],"title":"Related Documentation"}],"references":{"doc://com.truvideo.TruvideoSdkCamera/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/objc(pl)NSObject"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","title":"TruvideoSdkCamera","role":"collection","type":"topic","url":"\/documentation\/truvideosdkcamera","kind":"symbol","abstract":[{"text":"Store and capture photos and videos using a fully integrated camera system.","type":"text"}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkARCameraConfiguration/instantiate(with:orientation:mode:)":{"title":"instantiate(with:orientation:mode:)","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkARCameraConfiguration\/instantiate(with:orientation:mode:)","type":"topic","url":"\/documentation\/truvideosdkcamera\/truvideosdkarcameraconfiguration\/instantiate(with:orientation:mode:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"instantiate","kind":"identifier"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TruvideoSdkCameraFlashMode","preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraFlashMode","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"orientation"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraOrientation","text":"TruvideoSdkCameraOrientation","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"mode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraMediaMode","text":"TruvideoSdkCameraMediaMode"},{"text":") -> ","kind":"text"},{"text":"TruvideoSdkARCameraConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkARCameraConfiguration"}],"abstract":[{"type":"text","text":"Instantiates a new "},{"code":"TruvideoSdkARCameraConfiguration","type":"codeVoice"},{"type":"text","text":" using static method syntax."}],"navigatorTitle":[{"kind":"identifier","text":"instantiateWith:orientation:mode:"}],"role":"symbol","kind":"symbol"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraFlashMode":{"title":"TruvideoSdkCameraFlashMode","type":"topic","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraFlashMode","role":"symbol","abstract":[{"text":"Defines the flash mode settings for the camera.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"TruvideoSdkCameraFlashMode","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"TruvideoSdkCameraFlashMode"}],"kind":"symbol","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraflashmode"},"doc://com.truvideo.TruvideoSdkCamera/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/objc(cs)NSObject"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkARCameraConfiguration/flashMode":{"navigatorTitle":[{"kind":"identifier","text":"flashMode"}],"title":"flashMode","role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/truvideosdkcamera\/truvideosdkarcameraconfiguration\/flashmode","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkARCameraConfiguration\/flashMode","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"flashMode","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TruvideoSdkCameraFlashMode","preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraFlashMode"}],"abstract":[{"type":"text","text":"The flash mode setting for the AR Camera."}]},"doc://com.truvideo.TruvideoSdkCamera/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/s7CVarArgP"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraOrientation":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TruvideoSdkCameraOrientation"}],"title":"TruvideoSdkCameraOrientation","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TruvideoSdkCameraOrientation"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraOrientation","abstract":[{"type":"text","text":"Defines the camera orientation for media capture."}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraorientation"},"doc://com.truvideo.TruvideoSdkCamera/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/SQ"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraMediaMode":{"type":"topic","abstract":[],"title":"TruvideoSdkCameraMediaMode","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraMediaMode","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TruvideoSdkCameraMediaMode","kind":"identifier"}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameramediamode","navigatorTitle":[{"text":"TruvideoSdkCameraMediaMode","kind":"identifier"}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkARCameraConfiguration/init(flashMode:mode:orientation:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"flashMode"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraFlashMode","kind":"typeIdentifier","text":"TruvideoSdkCameraFlashMode"},{"text":", ","kind":"text"},{"text":"mode","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TruvideoSdkCameraMediaMode","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraMediaMode"},{"kind":"text","text":", "},{"kind":"externalParam","text":"orientation"},{"text":": ","kind":"text"},{"text":"TruvideoSdkCameraOrientation","preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraOrientation","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkARCameraConfiguration\/init(flashMode:mode:orientation:)","url":"\/documentation\/truvideosdkcamera\/truvideosdkarcameraconfiguration\/init(flashmode:mode:orientation:)","abstract":[{"type":"text","text":"Creates a new instance of "},{"code":"TruvideoSdkARCameraConfiguration","type":"codeVoice"},{"text":" with customizable settings.","type":"text"}],"title":"init(flashMode:mode:orientation:)"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkARCameraConfiguration/mode":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkARCameraConfiguration\/mode","title":"mode","abstract":[{"text":"The media capture mode for the AR Camera.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"mode","kind":"identifier"},{"kind":"text","text":": "},{"text":"TruvideoSdkCameraMediaMode","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraMediaMode","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"mode"}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkarcameraconfiguration\/mode","kind":"symbol"},"doc://com.truvideo.TruvideoSdkCamera/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/s23CustomStringConvertibleP"},"doc://com.truvideo.TruvideoSdkCamera/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/SH"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkARCameraConfiguration":{"navigatorTitle":[{"kind":"identifier","text":"TruvideoSdkARCameraConfiguration"}],"title":"TruvideoSdkARCameraConfiguration","role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkARCameraConfiguration","url":"\/documentation\/truvideosdkcamera\/truvideosdkarcameraconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TruvideoSdkARCameraConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"A configuration object for setting up the AR Camera in "},{"type":"codeVoice","code":"TruvideoSdkCamera"},{"text":".","type":"text"}]},"doc://com.truvideo.TruvideoSdkCamera/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/s28CustomDebugStringConvertibleP"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkARCameraConfiguration/orientation":{"navigatorTitle":[{"text":"orientation","kind":"identifier"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkARCameraConfiguration\/orientation","abstract":[{"text":"The camera orientation used when capturing AR content.","type":"text"}],"kind":"symbol","url":"\/documentation\/truvideosdkcamera\/truvideosdkarcameraconfiguration\/orientation","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"orientation","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraOrientation","text":"TruvideoSdkCameraOrientation"}],"title":"orientation","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"TruvideoSdkARCameraConfiguration"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"TruvideoSdkARCameraConfiguration","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"TruvideoSdkARCameraConfiguration"}],"op":"replace"},{"value":[{"identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkARCameraConfiguration\/flashMode","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkARCameraConfiguration\/mode","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkARCameraConfiguration\/orientation"],"title":"Instance Properties"},{"title":"Type Methods","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkARCameraConfiguration\/instantiate(with:orientation:mode:)"]}],"op":"replace","path":"\/topicSections"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"}],"path":"\/relationshipsSections"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraFlashMode","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraMediaMode","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraOrientation"],"title":"Related Documentation"}],"path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"TruvideoSdkARCameraConfiguration"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkARCameraConfiguration~1instantiate(with:orientation:mode:)\/title","value":"instantiateWith:orientation:mode:"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"instantiateWith:orientation:mode:"}],"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkARCameraConfiguration~1instantiate(with:orientation:mode:)\/fragments"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraFlashMode\/title","value":"TruvideoSdkCameraFlashMode","op":"replace"},{"value":[{"text":"TruvideoSdkCameraFlashMode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraFlashMode\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkARCameraConfiguration~1flashMode\/title","value":"flashMode"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkARCameraConfiguration~1flashMode\/fragments","value":[{"kind":"identifier","text":"flashMode"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraOrientation\/title","value":"TruvideoSdkCameraOrientation"},{"value":[{"kind":"identifier","text":"TruvideoSdkCameraOrientation"}],"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraOrientation\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraMediaMode\/title","value":"TruvideoSdkCameraMediaMode"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraMediaMode\/fragments","value":[{"text":"TruvideoSdkCameraMediaMode","kind":"identifier"}]},{"value":"mode","op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkARCameraConfiguration~1mode\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkARCameraConfiguration~1mode\/fragments","value":[{"text":"mode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkARCameraConfiguration\/title","op":"replace","value":"TruvideoSdkARCameraConfiguration"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkARCameraConfiguration\/fragments","value":[{"text":"TruvideoSdkARCameraConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkARCameraConfiguration~1orientation\/title","op":"replace","value":"orientation"},{"value":[{"text":"orientation","kind":"identifier"}],"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkARCameraConfiguration~1orientation\/fragments","op":"replace"}]}]}