{"hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraInterface\/camera"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraInterface\/configureTruvideoSdkAppDelegate(_:)"]}],"variants":[{"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcamerainterface"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcamerainterface"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraInterface","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"TruvideoSdkCamera"}],"symbolKind":"protocol","roleHeading":"Protocol","navigatorTitle":[{"kind":"identifier","text":"TruvideoSdkCameraInterface"}],"externalID":"c:@M@TruvideoSdkCamera@objc(pl)TruvideoSdkCameraInterface","title":"TruvideoSdkCameraInterface","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"TruvideoSdkCameraInterface","kind":"identifier"}],"role":"symbol"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TruvideoSdkCameraInterface","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]},{"content":[{"text":"Overview","level":2,"type":"heading","anchor":"overview"},{"inlineContent":[{"text":"The ","type":"text"},{"code":"TruvideoSdkCameraInterface","type":"codeVoice"},{"type":"text","text":" provides access to core camera functionality, including"},{"type":"text","text":" "},{"type":"text","text":"retrieving available cameras and configuring the SDK."}],"type":"paragraph"},{"type":"heading","text":"Example Usage","level":2,"anchor":"Example-Usage"},{"type":"codeListing","syntax":"swift","code":["let sdkCamera = TruvideoSdkCameraProvider.shared","sdkCamera.configureTruvideoSdkAppDelegate(myAppDelegate)"]}],"kind":"content"}],"kind":"symbol","abstract":[{"text":"Defines the interface for accessing ","type":"text"},{"type":"codeVoice","code":"TruvideoSdkCamera"},{"text":" functionalities.","type":"text"}],"references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraInterface":{"type":"topic","abstract":[{"type":"text","text":"Defines the interface for accessing "},{"type":"codeVoice","code":"TruvideoSdkCamera"},{"type":"text","text":" functionalities."}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcamerainterface","kind":"symbol","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraInterface","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TruvideoSdkCameraInterface"}],"role":"symbol","navigatorTitle":[{"text":"TruvideoSdkCameraInterface","kind":"identifier"}],"title":"TruvideoSdkCameraInterface"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraInterface/configureTruvideoSdkAppDelegate(_:)":{"role":"symbol","kind":"symbol","title":"configureTruvideoSdkAppDelegate(_:)","required":true,"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraInterface\/configureTruvideoSdkAppDelegate(_:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"configureTruvideoSdkAppDelegate:"}],"abstract":[{"type":"text","text":"Configures the Truvideo SDK with an application delegate."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"configureTruvideoSdkAppDelegate","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(pl)TruvideoSdkCameraAppDelegate","text":"TruvideoSdkCameraAppDelegate","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcamerainterface\/configuretruvideosdkappdelegate(_:)"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","title":"TruvideoSdkCamera","role":"collection","type":"topic","url":"\/documentation\/truvideosdkcamera","kind":"symbol","abstract":[{"text":"Store and capture photos and videos using a fully integrated camera system.","type":"text"}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraInterface/camera":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraInterface\/camera","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"camera","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(pl)TruvideoSdkCameraDelegate","text":"TruvideoSdkCameraDelegate"}],"required":true,"navigatorTitle":[{"text":"camera","kind":"identifier"}],"type":"topic","title":"camera","url":"\/documentation\/truvideosdkcamera\/truvideosdkcamerainterface\/camera","abstract":[{"type":"text","text":"Provides the main camera delegate, responsible for handling SDK camera operations."}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Protocol","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"TruvideoSdkCameraInterface","path":"\/metadata\/title"},{"op":"replace","value":"protocol","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"TruvideoSdkCameraInterface","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"TruvideoSdkCameraInterface"}]},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraInterface\/camera"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraInterface\/configureTruvideoSdkAppDelegate(_:)"],"title":"Instance Methods"}],"op":"replace"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TruvideoSdkCameraInterface"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraInterface\/title","value":"TruvideoSdkCameraInterface"},{"value":[{"text":"TruvideoSdkCameraInterface","kind":"identifier"}],"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraInterface\/fragments","op":"replace"},{"value":"configureTruvideoSdkAppDelegate:","op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraInterface~1configureTruvideoSdkAppDelegate(_:)\/title"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraInterface~1configureTruvideoSdkAppDelegate(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"configureTruvideoSdkAppDelegate:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraInterface~1camera\/title","value":"camera","op":"replace"},{"value":[{"kind":"identifier","text":"camera"}],"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraInterface~1camera\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}