{"metadata":{"title":"TruvideoSdkCameraOrientation","navigatorTitle":[{"text":"TruvideoSdkCameraOrientation","kind":"identifier"}],"symbolKind":"enum","modules":[{"name":"TruvideoSdkCamera"}],"roleHeading":"Enumeration","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TruvideoSdkCameraOrientation"}],"role":"symbol","externalID":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraOrientation"},"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Defines the camera orientation for media capture."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TruvideoSdkCameraOrientation","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"text":"Overview","level":2,"type":"heading","anchor":"overview"},{"inlineContent":[{"type":"text","text":"This enum specifies whether the camera operates in "},{"type":"strong","inlineContent":[{"text":"portrait or landscape mode","type":"text"}]},{"type":"text","text":"."}],"type":"paragraph"},{"anchor":"Available-Values","level":2,"text":"Available Values","type":"heading"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraOrientation\/portrait"},{"type":"text","text":": "},{"inlineContent":[{"text":"Upright portrait mode","type":"text"}],"type":"strong"},{"type":"text","text":"."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraOrientation\/landscapeLeft","isActive":true},{"type":"text","text":": "},{"type":"strong","inlineContent":[{"type":"text","text":"Landscape mode with the device rotated left"}]},{"text":".","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraOrientation\/landscapeRight","isActive":true,"type":"reference"},{"type":"text","text":": "},{"inlineContent":[{"type":"text","text":"Landscape mode with the device rotated right"}],"type":"strong"},{"type":"text","text":"."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraOrientation\/portraitReverse"},{"type":"text","text":": "},{"type":"strong","inlineContent":[{"text":"Upside-down portrait mode","type":"text"}]},{"text":".","type":"text"}]}]}],"type":"unorderedList"},{"anchor":"Automatic-Orientation-Detection","type":"heading","text":"Automatic Orientation Detection","level":2},{"inlineContent":[{"type":"text","text":"If no orientation is explicitly set, the system will determine the "},{"type":"strong","inlineContent":[{"type":"text","text":"current device orientation"}]},{"type":"text","text":"."}],"type":"paragraph"},{"type":"codeListing","syntax":"swift","code":["let orientation = TruvideoSdkCameraOrientation.currentOrientation"]}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraOrientation"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraOrientation\/landscapeLeft","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraOrientation\/landscapeRight","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraOrientation\/portrait","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraOrientation\/portraitReverse"]},{"identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraOrientation\/init(from:)","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraOrientation\/init(rawValue:)"],"title":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraOrientation\/rawValue-swift.property"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraOrientation\/encode(to:)"]},{"title":"Type Aliases","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraOrientation\/RawValue-swift.typealias"]},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraOrientation\/Equatable-Implementations","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraOrientation\/RawRepresentable-Implementations"]}],"relationshipsSections":[{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/SE","doc:\/\/com.truvideo.TruvideoSdkCamera\/SQ","doc:\/\/com.truvideo.TruvideoSdkCamera\/SH","doc:\/\/com.truvideo.TruvideoSdkCamera\/SY"],"type":"conformsTo"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcameraorientation"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcameraorientation"]}],"kind":"symbol","sections":[],"references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraOrientation/portraitReverse":{"title":"TruvideoSdkCameraOrientation.portraitReverse","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraOrientation\/portraitReverse","type":"topic","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraorientation\/portraitreverse","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"portraitReverse","kind":"identifier"}],"abstract":[{"type":"text","text":"Upside-down portrait mode."}],"kind":"symbol","navigatorTitle":[{"text":"TruvideoSdkCameraOrientationPortraitReverse","kind":"identifier"}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraOrientation/init(from:)":{"kind":"symbol","title":"init(from:)","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"kind":"text","text":": "},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP","text":"Decoder"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraorientation\/init(from:)","role":"symbol","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraOrientation\/init(from:)","abstract":[{"type":"text","text":"Creates a new instance by decoding from the given decoder."}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraOrientation/encode(to:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"encode"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"keyword","text":"any"},{"kind":"text","text":" "},{"text":"Encoder","kind":"typeIdentifier","preciseIdentifier":"s:s7EncoderP"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"title":"encode(to:)","type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraOrientation\/encode(to:)","abstract":[{"type":"text","text":"Encodes this value into the given encoder."}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraorientation\/encode(to:)"},"doc://com.truvideo.TruvideoSdkCamera/SH":{"type":"unresolvable","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/SH","title":"Swift.Hashable"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraOrientation/portrait":{"title":"TruvideoSdkCameraOrientation.portrait","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraorientation\/portrait","type":"topic","navigatorTitle":[{"text":"TruvideoSdkCameraOrientationPortrait","kind":"identifier"}],"abstract":[{"type":"text","text":"Upright portrait mode."}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"portrait","kind":"identifier"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraOrientation\/portrait","kind":"symbol","role":"symbol"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraOrientation/RawValue-swift.typealias":{"title":"TruvideoSdkCameraOrientation.RawValue","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraorientation\/rawvalue-swift.typealias","abstract":[{"text":"The raw type that can be used to represent all values of the conforming","type":"text"},{"type":"text","text":" "},{"text":"type.","type":"text"}],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"RawValue","kind":"identifier"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraOrientation\/RawValue-swift.typealias","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"RawValue","kind":"identifier"}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","title":"TruvideoSdkCamera","role":"collection","type":"topic","url":"\/documentation\/truvideosdkcamera","kind":"symbol","abstract":[{"text":"Store and capture photos and videos using a fully integrated camera system.","type":"text"}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraOrientation/Equatable-Implementations":{"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraorientation\/equatable-implementations","type":"topic","kind":"article","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraOrientation\/Equatable-Implementations","abstract":[],"role":"collectionGroup","title":"Equatable Implementations"},"doc://com.truvideo.TruvideoSdkCamera/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/SQ","title":"Swift.Equatable"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraOrientation/init(rawValue:)":{"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraorientation\/init(rawvalue:)","type":"topic","kind":"symbol","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraOrientation\/init(rawValue:)","abstract":[{"type":"text","text":"Creates a new instance with the specified raw value."}],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:17TruvideoSdkCamera0abC11OrientationO8RawValuea","text":"RawValue"},{"kind":"text","text":")"}],"title":"init(rawValue:)"},"doc://com.truvideo.TruvideoSdkCamera/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/SE"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraOrientation":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TruvideoSdkCameraOrientation"}],"title":"TruvideoSdkCameraOrientation","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TruvideoSdkCameraOrientation"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraOrientation","abstract":[{"type":"text","text":"Defines the camera orientation for media capture."}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraorientation"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraOrientation/rawValue-swift.property":{"title":"rawValue","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraOrientation\/rawValue-swift.property","type":"topic","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraorientation\/rawvalue-swift.property","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"rawValue","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"RawValue","preciseIdentifier":"s:17TruvideoSdkCamera0abC11OrientationO8RawValuea"}],"abstract":[{"type":"text","text":"The corresponding value of the raw type."}],"kind":"symbol"},"doc://com.truvideo.TruvideoSdkCamera/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/SY"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraOrientation/RawRepresentable-Implementations":{"title":"RawRepresentable Implementations","type":"topic","role":"collectionGroup","kind":"article","abstract":[],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraOrientation\/RawRepresentable-Implementations","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraorientation\/rawrepresentable-implementations"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraOrientation/landscapeRight":{"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraorientation\/landscaperight","type":"topic","kind":"symbol","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraOrientation\/landscapeRight","abstract":[{"type":"text","text":"Landscape mode with the device rotated right."}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"landscapeRight"}],"title":"TruvideoSdkCameraOrientation.landscapeRight","navigatorTitle":[{"text":"TruvideoSdkCameraOrientationLandscapeRight","kind":"identifier"}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraOrientation/landscapeLeft":{"title":"TruvideoSdkCameraOrientation.landscapeLeft","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraOrientation\/landscapeLeft","type":"topic","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraorientation\/landscapeleft","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"landscapeLeft"}],"abstract":[{"type":"text","text":"Landscape mode with the device rotated left."}],"navigatorTitle":[{"text":"TruvideoSdkCameraOrientationLandscapeLeft","kind":"identifier"}],"role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"TruvideoSdkCameraOrientation"},{"value":"enum","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"TruvideoSdkCameraOrientation","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"TruvideoSdkCameraOrientation","kind":"identifier"}]},{"value":[{"identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraOrientation\/landscapeLeft","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraOrientation\/landscapeRight","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraOrientation\/portrait","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraOrientation\/portraitReverse"],"title":"Enumeration Cases"}],"path":"\/topicSections","op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TruvideoSdkCameraOrientation"},{"kind":"text","text":": "},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraOrientation~1portraitReverse\/title","op":"replace","value":"TruvideoSdkCameraOrientationPortraitReverse"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraOrientation~1portraitReverse\/fragments","value":[{"text":"TruvideoSdkCameraOrientationPortraitReverse","kind":"identifier"}],"op":"replace"},{"value":"TruvideoSdkCameraOrientationPortrait","op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraOrientation~1portrait\/title"},{"value":[{"text":"TruvideoSdkCameraOrientationPortrait","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraOrientation~1portrait\/fragments"},{"value":"TruvideoSdkCameraOrientation","op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraOrientation\/title"},{"value":[{"text":"TruvideoSdkCameraOrientation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraOrientation\/fragments"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraOrientation~1landscapeRight\/title","value":"TruvideoSdkCameraOrientationLandscapeRight","op":"replace"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraOrientation~1landscapeRight\/fragments","op":"replace","value":[{"kind":"identifier","text":"TruvideoSdkCameraOrientationLandscapeRight"}]},{"value":"TruvideoSdkCameraOrientationLandscapeLeft","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraOrientation~1landscapeLeft\/title","op":"replace"},{"value":[{"kind":"identifier","text":"TruvideoSdkCameraOrientationLandscapeLeft"}],"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraOrientation~1landscapeLeft\/fragments","op":"replace"}]}]}