{"topicSections":[{"identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraScannerCodeFormat\/code39","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraScannerCodeFormat\/code93","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraScannerCodeFormat\/codeQR","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraScannerCodeFormat\/dataMatrix"],"title":"Enumeration Cases"},{"identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraScannerCodeFormat\/init(from:)-38plu","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraScannerCodeFormat\/init(rawValue:)"],"title":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraScannerCodeFormat\/rawValue-swift.property"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraScannerCodeFormat\/encode(to:)"]},{"title":"Type Aliases","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraScannerCodeFormat\/RawValue-swift.typealias"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraScannerCodeFormat\/Equatable-Implementations","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraScannerCodeFormat\/RawRepresentable-Implementations"],"generated":true}],"hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera"]]},"kind":"symbol","relationshipsSections":[{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/s12CaseIterableP","doc:\/\/com.truvideo.TruvideoSdkCamera\/Se","doc:\/\/com.truvideo.TruvideoSdkCamera\/SE","doc:\/\/com.truvideo.TruvideoSdkCamera\/SQ","doc:\/\/com.truvideo.TruvideoSdkCamera\/SH","doc:\/\/com.truvideo.TruvideoSdkCamera\/SY"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TruvideoSdkCameraScannerCodeFormat"}]}],"kind":"declarations"},{"content":[{"type":"heading","level":2,"anchor":"overview","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"TruvideoSdkCameraScannerCodeFormat"},{"text":" provides the available barcode types that the ","type":"text"},{"inlineContent":[{"type":"text","text":"Truvideo Scanner Camera"}],"type":"strong"},{"text":" can detect.","type":"text"}]},{"anchor":"Supported-Formats","text":"Supported Formats","level":2,"type":"heading"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"code":"code39","type":"codeVoice"},{"type":"text","text":": "},{"type":"strong","inlineContent":[{"type":"text","text":"Code-39 barcode"}]},{"text":" (commonly used in logistics and inventory systems)","type":"text"}]}]},{"content":[{"inlineContent":[{"code":"code93","type":"codeVoice"},{"type":"text","text":": "},{"type":"strong","inlineContent":[{"type":"text","text":"Code-93 barcode"}]},{"type":"text","text":" (an extended version of Code-39 with higher data density)"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"code":"codeQR","type":"codeVoice"},{"type":"text","text":": "},{"inlineContent":[{"text":"QR Code","type":"text"}],"type":"strong"},{"type":"text","text":" (widely used for mobile transactions, payments, and URLs)"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"dataMatrix"},{"type":"text","text":": "},{"inlineContent":[{"text":"DataMatrix Code","type":"text"}],"type":"strong"},{"type":"text","text":" (used in packaging, manufacturing, and tracking applications)"}]}]}]},{"level":2,"anchor":"Example-Usage","type":"heading","text":"Example Usage"},{"type":"codeListing","syntax":"swift","code":["let scannerConfig = TruvideoSdkScannerCameraConfiguration(","    flashMode: .auto,","    codeFormats: [.codeQR, .dataMatrix]",")"]}],"kind":"content"}],"variants":[{"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcamerascannercodeformat"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcamerascannercodeformat"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraScannerCodeFormat","symbolKind":"enum","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TruvideoSdkCameraScannerCodeFormat","kind":"identifier"}],"roleHeading":"Enumeration","modules":[{"name":"TruvideoSdkCamera"}],"navigatorTitle":[{"kind":"identifier","text":"TruvideoSdkCameraScannerCodeFormat"}],"title":"TruvideoSdkCameraScannerCodeFormat"},"abstract":[{"type":"text","text":"Defines the supported barcode and QR code formats for the scanner."}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraScannerCodeFormat","interfaceLanguage":"swift"},"references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraScannerCodeFormat/code93":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraScannerCodeFormat\/code93","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"code93"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"TruvideoSdkCameraScannerCodeFormatCode93","kind":"identifier"}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcamerascannercodeformat\/code93","abstract":[{"text":"Code-93 barcode format.","type":"text"}],"kind":"symbol","title":"TruvideoSdkCameraScannerCodeFormat.code93"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraScannerCodeFormat/rawValue-swift.property":{"url":"\/documentation\/truvideosdkcamera\/truvideosdkcamerascannercodeformat\/rawvalue-swift.property","kind":"symbol","title":"rawValue","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:17TruvideoSdkCamera0abC17ScannerCodeFormatO8RawValuea","text":"RawValue","kind":"typeIdentifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraScannerCodeFormat\/rawValue-swift.property","abstract":[{"type":"text","text":"The corresponding value of the raw type."}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraScannerCodeFormat/code39":{"title":"TruvideoSdkCameraScannerCodeFormat.code39","kind":"symbol","url":"\/documentation\/truvideosdkcamera\/truvideosdkcamerascannercodeformat\/code39","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"code39"}],"navigatorTitle":[{"kind":"identifier","text":"TruvideoSdkCameraScannerCodeFormatCode39"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraScannerCodeFormat\/code39","abstract":[{"type":"text","text":"Code-39 barcode format."}]},"doc://com.truvideo.TruvideoSdkCamera/Se":{"type":"unresolvable","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/Se","title":"Swift.Decodable"},"doc://com.truvideo.TruvideoSdkCamera/SE":{"type":"unresolvable","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/SE","title":"Swift.Encodable"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraScannerCodeFormat/RawRepresentable-Implementations":{"type":"topic","title":"RawRepresentable Implementations","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraScannerCodeFormat\/RawRepresentable-Implementations","abstract":[],"role":"collectionGroup","url":"\/documentation\/truvideosdkcamera\/truvideosdkcamerascannercodeformat\/rawrepresentable-implementations","kind":"article"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraScannerCodeFormat":{"navigatorTitle":[{"kind":"identifier","text":"TruvideoSdkCameraScannerCodeFormat"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"TruvideoSdkCameraScannerCodeFormat","kind":"identifier"}],"abstract":[{"text":"Defines the supported barcode and QR code formats for the scanner.","type":"text"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraScannerCodeFormat","url":"\/documentation\/truvideosdkcamera\/truvideosdkcamerascannercodeformat","kind":"symbol","title":"TruvideoSdkCameraScannerCodeFormat","type":"topic","role":"symbol"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraScannerCodeFormat/RawValue-swift.typealias":{"title":"TruvideoSdkCameraScannerCodeFormat.RawValue","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraScannerCodeFormat\/RawValue-swift.typealias","type":"topic","url":"\/documentation\/truvideosdkcamera\/truvideosdkcamerascannercodeformat\/rawvalue-swift.typealias","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RawValue"}],"abstract":[{"type":"text","text":"The raw type that can be used to represent all values of the conforming"},{"type":"text","text":" "},{"type":"text","text":"type."}],"navigatorTitle":[{"kind":"identifier","text":"RawValue"}],"role":"symbol","kind":"symbol"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraScannerCodeFormat/Equatable-Implementations":{"title":"Equatable Implementations","role":"collectionGroup","type":"topic","url":"\/documentation\/truvideosdkcamera\/truvideosdkcamerascannercodeformat\/equatable-implementations","abstract":[],"kind":"article","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraScannerCodeFormat\/Equatable-Implementations"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraScannerCodeFormat/init(from:)-38plu":{"url":"\/documentation\/truvideosdkcamera\/truvideosdkcamerascannercodeformat\/init(from:)-38plu","kind":"symbol","title":"init(from:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"text":": ","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Decoder","kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraScannerCodeFormat\/init(from:)-38plu","abstract":[{"type":"text","text":"Creates a new instance by decoding from the given decoder."}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraScannerCodeFormat/init(rawValue:)":{"title":"init(rawValue:)","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraScannerCodeFormat\/init(rawValue:)","type":"topic","url":"\/documentation\/truvideosdkcamera\/truvideosdkcamerascannercodeformat\/init(rawvalue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"RawValue","preciseIdentifier":"s:17TruvideoSdkCamera0abC17ScannerCodeFormatO8RawValuea"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Creates a new instance with the specified raw value."}],"role":"symbol","kind":"symbol"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraScannerCodeFormat/dataMatrix":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraScannerCodeFormat\/dataMatrix","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"dataMatrix","kind":"identifier"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"TruvideoSdkCameraScannerCodeFormatDataMatrix","kind":"identifier"}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcamerascannercodeformat\/datamatrix","abstract":[{"type":"text","text":"DataMatrix barcode format."}],"kind":"symbol","title":"TruvideoSdkCameraScannerCodeFormat.dataMatrix"},"doc://com.truvideo.TruvideoSdkCamera/s12CaseIterableP":{"type":"unresolvable","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/s12CaseIterableP","title":"Swift.CaseIterable"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraScannerCodeFormat/codeQR":{"url":"\/documentation\/truvideosdkcamera\/truvideosdkcamerascannercodeformat\/codeqr","kind":"symbol","title":"TruvideoSdkCameraScannerCodeFormat.codeQR","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"codeQR","kind":"identifier"}],"navigatorTitle":[{"text":"TruvideoSdkCameraScannerCodeFormatCodeQR","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraScannerCodeFormat\/codeQR","abstract":[{"type":"text","text":"QR Code format."}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","title":"TruvideoSdkCamera","role":"collection","type":"topic","url":"\/documentation\/truvideosdkcamera","kind":"symbol","abstract":[{"text":"Store and capture photos and videos using a fully integrated camera system.","type":"text"}]},"doc://com.truvideo.TruvideoSdkCamera/SH":{"type":"unresolvable","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/SH","title":"Swift.Hashable"},"doc://com.truvideo.TruvideoSdkCamera/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/SQ","title":"Swift.Equatable"},"doc://com.truvideo.TruvideoSdkCamera/SY":{"type":"unresolvable","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/SY","title":"Swift.RawRepresentable"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraScannerCodeFormat/encode(to:)":{"url":"\/documentation\/truvideosdkcamera\/truvideosdkcamerascannercodeformat\/encode(to:)","abstract":[{"text":"Encodes this value into the given encoder.","type":"text"}],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"encode","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"keyword","text":"any"},{"kind":"text","text":" "},{"preciseIdentifier":"s:s7EncoderP","kind":"typeIdentifier","text":"Encoder"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"title":"encode(to:)","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraScannerCodeFormat\/encode(to:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"TruvideoSdkCameraScannerCodeFormat"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"TruvideoSdkCameraScannerCodeFormat","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"TruvideoSdkCameraScannerCodeFormat"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraScannerCodeFormat\/code39","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraScannerCodeFormat\/code93","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraScannerCodeFormat\/codeQR","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraScannerCodeFormat\/dataMatrix"],"title":"Enumeration Cases"}]},{"value":null,"path":"\/relationshipsSections","op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"TruvideoSdkCameraScannerCodeFormat","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"TruvideoSdkCameraScannerCodeFormatCode93","op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraScannerCodeFormat~1code93\/title"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraScannerCodeFormat~1code93\/fragments","op":"replace","value":[{"text":"TruvideoSdkCameraScannerCodeFormatCode93","kind":"identifier"}]},{"value":"TruvideoSdkCameraScannerCodeFormatCode39","op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraScannerCodeFormat~1code39\/title"},{"value":[{"kind":"identifier","text":"TruvideoSdkCameraScannerCodeFormatCode39"}],"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraScannerCodeFormat~1code39\/fragments"},{"value":"TruvideoSdkCameraScannerCodeFormat","op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraScannerCodeFormat\/title"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraScannerCodeFormat\/fragments","op":"replace","value":[{"kind":"identifier","text":"TruvideoSdkCameraScannerCodeFormat"}]},{"value":"TruvideoSdkCameraScannerCodeFormatDataMatrix","op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraScannerCodeFormat~1dataMatrix\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraScannerCodeFormat~1dataMatrix\/fragments","value":[{"kind":"identifier","text":"TruvideoSdkCameraScannerCodeFormatDataMatrix"}]},{"value":"TruvideoSdkCameraScannerCodeFormatCodeQR","op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraScannerCodeFormat~1codeQR\/title"},{"value":[{"text":"TruvideoSdkCameraScannerCodeFormatCodeQR","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraScannerCodeFormat~1codeQR\/fragments"}]}]}