{"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraInformation\/backCamera","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraInformation\/frontCamera"],"title":"Instance Properties"}],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"},{"identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/objc(pl)NSObject","doc:\/\/com.truvideo.TruvideoSdkCamera\/s7CVarArgP","doc:\/\/com.truvideo.TruvideoSdkCamera\/s28CustomDebugStringConvertibleP","doc:\/\/com.truvideo.TruvideoSdkCamera\/s23CustomStringConvertibleP","doc:\/\/com.truvideo.TruvideoSdkCamera\/SE","doc:\/\/com.truvideo.TruvideoSdkCamera\/SQ","doc:\/\/com.truvideo.TruvideoSdkCamera\/SH"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TruvideoSdkCameraInformation"}],"title":"TruvideoSdkCameraInformation","role":"symbol","symbolKind":"class","externalID":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraInformation","navigatorTitle":[{"text":"TruvideoSdkCameraInformation","kind":"identifier"}],"roleHeading":"Class","modules":[{"name":"TruvideoSdkCamera"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Provides detailed information about available camera devices.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcamerainformation"]},{"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcamerainformation"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TruvideoSdkCameraInformation"}]}],"kind":"declarations"},{"content":[{"text":"Overview","anchor":"overview","type":"heading","level":2},{"inlineContent":[{"code":"TruvideoSdkCameraInformation","type":"codeVoice"},{"text":" contains references to the ","type":"text"},{"inlineContent":[{"type":"text","text":"front-facing"}],"type":"strong"},{"text":" and ","type":"text"},{"type":"strong","inlineContent":[{"text":"back-facing","type":"text"}]},{"type":"text","text":" cameras available on the device."}],"type":"paragraph"},{"text":"Example Usage","level":2,"anchor":"Example-Usage","type":"heading"},{"code":["let cameraInfo = TruvideoSdkCameraInformation(frontCamera: frontDevice, backCamera: backDevice)","print(\"Front Camera ID: \\(cameraInfo.frontCamera?.id ?? \"N\/A\")\")"],"type":"codeListing","syntax":"swift"}],"kind":"content"}],"sections":[],"identifier":{"url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraInformation","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera"]]},"references":{"doc://com.truvideo.TruvideoSdkCamera/objc(cs)NSObject":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.truvideo.TruvideoSdkCamera/SE":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/SE","type":"unresolvable","title":"Swift.Encodable"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraInformation/backCamera":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"backCamera"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraDevice","text":"TruvideoSdkCameraDevice"},{"text":"?","kind":"text"}],"title":"backCamera","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"backCamera","kind":"identifier"}],"abstract":[{"text":"The back-facing camera device, if available.","type":"text"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraInformation\/backCamera","url":"\/documentation\/truvideosdkcamera\/truvideosdkcamerainformation\/backcamera"},"doc://com.truvideo.TruvideoSdkCamera/s7CVarArgP":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.truvideo.TruvideoSdkCamera/SH":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","title":"TruvideoSdkCamera","role":"collection","type":"topic","url":"\/documentation\/truvideosdkcamera","kind":"symbol","abstract":[{"text":"Store and capture photos and videos using a fully integrated camera system.","type":"text"}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraInformation":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TruvideoSdkCameraInformation"}],"title":"TruvideoSdkCameraInformation","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TruvideoSdkCameraInformation"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraInformation","abstract":[{"text":"Provides detailed information about available camera devices.","type":"text"}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcamerainformation"},"doc://com.truvideo.TruvideoSdkCamera/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.truvideo.TruvideoSdkCamera/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.truvideo.TruvideoSdkCamera/objc(pl)NSObject":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraInformation/frontCamera":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"frontCamera","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraDevice","text":"TruvideoSdkCameraDevice"},{"text":"?","kind":"text"}],"title":"frontCamera","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"frontCamera","kind":"identifier"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraInformation\/frontCamera","abstract":[{"text":"The front-facing camera device, if available.","type":"text"}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcamerainformation\/frontcamera"},"doc://com.truvideo.TruvideoSdkCamera/SQ":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/SQ","type":"unresolvable","title":"Swift.Equatable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"TruvideoSdkCameraInformation"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"TruvideoSdkCameraInformation","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"TruvideoSdkCameraInformation"}],"path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraInformation\/backCamera","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraInformation\/frontCamera"],"title":"Instance Properties"}]},{"value":[{"identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"}],"path":"\/relationshipsSections","op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"TruvideoSdkCameraInformation","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraInformation~1backCamera\/title","value":"backCamera","op":"replace"},{"value":[{"text":"backCamera","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraInformation~1backCamera\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraInformation\/title","value":"TruvideoSdkCameraInformation"},{"value":[{"kind":"identifier","text":"TruvideoSdkCameraInformation"}],"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraInformation\/fragments"},{"value":"frontCamera","op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraInformation~1frontCamera\/title"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraInformation~1frontCamera\/fragments","op":"replace","value":[{"text":"frontCamera","kind":"identifier"}]}]}]}