{"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TruvideoSdkCameraScannerCode"}],"title":"TruvideoSdkCameraScannerCode","role":"symbol","symbolKind":"class","externalID":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraScannerCode","navigatorTitle":[{"text":"TruvideoSdkCameraScannerCode","kind":"identifier"}],"roleHeading":"Class","modules":[{"name":"TruvideoSdkCamera"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcamerascannercode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcamerascannercode"]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TruvideoSdkCameraScannerCode","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"text":"Overview","anchor":"overview","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"The "},{"type":"codeVoice","code":"TruvideoSdkCameraScannerCode"},{"type":"text","text":" class contains "},{"inlineContent":[{"type":"text","text":"raw barcode data"}],"type":"strong"},{"type":"text","text":" and its associated "},{"inlineContent":[{"text":"format type","type":"text"}],"type":"strong"},{"text":".","type":"text"}],"type":"paragraph"},{"level":2,"type":"heading","anchor":"Overview","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"When a barcode or QR code is scanned using the "},{"type":"strong","inlineContent":[{"type":"text","text":"Truvideo Scanner Camera"}]},{"type":"text","text":", this class stores:"}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"strong","inlineContent":[{"text":"scanned code’s data","type":"text"}]},{"type":"text","text":" ("},{"type":"codeVoice","code":"data"},{"text":")","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"The "},{"type":"strong","inlineContent":[{"text":"format of the scanned barcode","type":"text"}]},{"type":"text","text":" ("},{"code":"format","type":"codeVoice"},{"text":")","type":"text"}],"type":"paragraph"}]}],"type":"unorderedList"},{"level":2,"type":"heading","text":"Example Usage","anchor":"Example-Usage"},{"type":"codeListing","code":["let scannedCode = TruvideoSdkCameraScannerCode(data: \"123456789\", format: .codeQR)","print(\"Scanned Data: \\(scannedCode.data)\")","print(\"Format: \\(scannedCode.format)\")"],"syntax":"swift"}]}],"sections":[],"identifier":{"url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraScannerCode","interfaceLanguage":"swift"},"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/objc(pl)NSObject","doc:\/\/com.truvideo.TruvideoSdkCamera\/s7CVarArgP","doc:\/\/com.truvideo.TruvideoSdkCamera\/s28CustomDebugStringConvertibleP","doc:\/\/com.truvideo.TruvideoSdkCamera\/s23CustomStringConvertibleP","doc:\/\/com.truvideo.TruvideoSdkCamera\/SQ","doc:\/\/com.truvideo.TruvideoSdkCamera\/SH"],"title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Represents the result of a barcode or QR code scan."}],"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraScannerCode\/data","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraScannerCode\/format"]}],"references":{"doc://com.truvideo.TruvideoSdkCamera/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/SQ"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraScannerCode/data":{"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"data","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"data","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"data"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraScannerCode\/data","abstract":[{"type":"text","text":"The raw data extracted from the scanned barcode."}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcamerascannercode\/data"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","title":"TruvideoSdkCamera","role":"collection","type":"topic","url":"\/documentation\/truvideosdkcamera","kind":"symbol","abstract":[{"text":"Store and capture photos and videos using a fully integrated camera system.","type":"text"}]},"doc://com.truvideo.TruvideoSdkCamera/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/objc(cs)NSObject"},"doc://com.truvideo.TruvideoSdkCamera/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/s7CVarArgP"},"doc://com.truvideo.TruvideoSdkCamera/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/s28CustomDebugStringConvertibleP"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraScannerCode/format":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"format"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraScannerCodeFormat","text":"TruvideoSdkCameraScannerCodeFormat"}],"title":"format","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"format","kind":"identifier"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraScannerCode\/format","abstract":[{"type":"text","text":"The type of barcode that was scanned."}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcamerascannercode\/format"},"doc://com.truvideo.TruvideoSdkCamera/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/objc(pl)NSObject"},"doc://com.truvideo.TruvideoSdkCamera/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/s23CustomStringConvertibleP"},"doc://com.truvideo.TruvideoSdkCamera/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/SH"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraScannerCode":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraScannerCode","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TruvideoSdkCameraScannerCode","kind":"identifier"}],"type":"topic","abstract":[{"text":"Represents the result of a barcode or QR code scan.","type":"text"}],"title":"TruvideoSdkCameraScannerCode","role":"symbol","url":"\/documentation\/truvideosdkcamera\/truvideosdkcamerascannercode","navigatorTitle":[{"text":"TruvideoSdkCameraScannerCode","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"path":"\/metadata\/title","value":"TruvideoSdkCameraScannerCode","op":"replace"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"TruvideoSdkCameraScannerCode"}]},{"value":[{"text":"TruvideoSdkCameraScannerCode","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraScannerCode\/data","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraScannerCode\/format"],"title":"Instance Properties"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"TruvideoSdkCameraScannerCode","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraScannerCode~1data\/title","op":"replace","value":"data"},{"value":[{"kind":"identifier","text":"data"}],"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraScannerCode~1data\/fragments"},{"value":"format","op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraScannerCode~1format\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraScannerCode~1format\/fragments","value":[{"text":"format","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraScannerCode\/title","value":"TruvideoSdkCameraScannerCode","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraScannerCode\/fragments","value":[{"text":"TruvideoSdkCameraScannerCode","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}