{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera"]]},"abstract":[{"type":"text","text":"Learn how to integrate the AR Camera in "},{"type":"strong","inlineContent":[{"type":"text","text":"TruvideoSdkCamera"}]},{"type":"text","text":" to enable Augmented Reality (AR) experiences, including 3D"},{"type":"text","text":" "},{"text":"object placement, distance measurement, and AR-enhanced video recording.","type":"text"}],"seeAlsoSections":[{"title":"Related Documentation","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/GettingStartedWithCamera","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/UsingCameraScanner"]},{"title":"Essentials","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/GettingStartedWithCamera","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/UsingCameraScanner"],"generated":true}],"metadata":{"modules":[{"name":"TruvideoSdkCamera"}],"role":"article","roleHeading":"Article","title":"Using the AR Camera"},"identifier":{"url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/UsingARCamera","interfaceLanguage":"swift"},"kind":"article","primaryContentSections":[{"content":[{"type":"heading","level":2,"text":"Overview","anchor":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"strong","inlineContent":[{"type":"text","text":"TruvideoSdkCamera"}]},{"text":" framework provides a customizable AR Camera that allows applications to:","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"📍 "},{"inlineContent":[{"text":"Place 3D objects","type":"text"}],"type":"strong"},{"text":" in real-world space","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"📏 ","type":"text"},{"inlineContent":[{"type":"text","text":"Measure distances"}],"type":"strong"},{"type":"text","text":" using a "},{"type":"strong","inlineContent":[{"type":"text","text":"virtual ruler"}]}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"🎥 ","type":"text"},{"inlineContent":[{"type":"text","text":"Capture AR-enhanced videos"}],"type":"strong"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"🔄 "},{"inlineContent":[{"type":"text","text":"Switch between front and rear cameras"}],"type":"strong"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"💡 "},{"type":"strong","inlineContent":[{"text":"Enable or disable flash","type":"text"}]}],"type":"paragraph"}]}]},{"inlineContent":[{"type":"text","text":"This guide explains how to configure and integrate the AR Camera using "},{"inlineContent":[{"type":"text","text":"TruvideoSdkCamera"}],"type":"strong"},{"type":"text","text":"."}],"type":"paragraph"},{"type":"heading","anchor":"Pre-Requisites","level":2,"text":"Pre-Requisites"},{"inlineContent":[{"text":"Before using the camera, ensure the necessary frameworks are imported and the user is ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"authenticated"}]},{"text":".","type":"text"}],"type":"paragraph"},{"text":"Import Required Modules","type":"heading","anchor":"Import-Required-Modules","level":3},{"inlineContent":[{"type":"text","text":"To access AR functionalities, import the following frameworks:"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"TruvideoSdk"}]}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"TruvideoCameraSdk"}]}]}]}],"type":"unorderedList"},{"text":"Configuring the Camera","anchor":"Configuring-the-Camera","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"To configure the AR Camera, create a "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraConfiguration"},{"text":" object with your desired settings.","type":"text"}]},{"code":["let cameraConfig = TruvideoSdkCameraConfiguration(","    flashMode: .auto,","    mode: .videoAndPicture(videoMaxCount: 5, pictureMaxCount: 3, durationLimit: 10),","    orientation: .portrait",")"],"type":"codeListing","syntax":"swift"},{"anchor":"Integrating-the-AR-Camera-in-SwiftUI","level":2,"text":"Integrating the AR Camera in SwiftUI","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"The AR Camera can be embedded in a SwiftUI view using the presentTruvideoSdkARCameraView modifier. This allows users to","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"interact with AR objects and capture AR-enhanced photos and videos."}]},{"type":"paragraph","inlineContent":[{"text":"To present the AR Camera, bind a Boolean state to control visibility and pass in an AR Camera configuration preset.","type":"text"}]},{"type":"codeListing","code":["    var body: some View {","        VStack(spacing: 16) {","            Button(\"Open AR Camera\") {","                showARCamera = true","            }","        }","        .presentTruvideoSdkARCameraView(isPresented: showARCamera, preset: cameraPreset) { result in","            print(result)","        }","    }"],"syntax":"swift"},{"text":"Handling Camera Output","type":"heading","level":2,"anchor":"Handling-Camera-Output"},{"type":"paragraph","inlineContent":[{"text":"When a user captures a photo or records a video, the ","type":"text"},{"type":"codeVoice","code":"onComplete"},{"text":" closure provides a ","type":"text"},{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraResult","type":"reference","isActive":true},{"type":"text","text":" object."},{"type":"text","text":" "},{"type":"text","text":"This result contains one or more AR-enhanced media files, including metadata such as file path and type."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"To handle the camera output, process the result in the "},{"code":"onComplete","type":"codeVoice"},{"type":"text","text":" closure."}]},{"syntax":"swift","type":"codeListing","code":["func processCameraResult(_ result: TruvideoSdkCameraResult) {","    for media in result.media {","        print(\"Captured media: \\(media.filePath)\")","    }","}"]},{"anchor":"Summary","text":"Summary","level":2,"type":"heading"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"Use "},{"inlineContent":[{"text":"presentTruvideoSdkARCameraView","type":"text"}],"type":"strong"},{"type":"text","text":" to integrate the AR Camera in SwiftUI."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Control visibility using a "},{"type":"strong","inlineContent":[{"type":"text","text":"Boolean state"}]},{"text":".","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"Pass a ","type":"text"},{"type":"strong","inlineContent":[{"text":"camera preset","type":"text"}]},{"type":"text","text":" to configure capture settings."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Handle captured media using the ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"onComplete"}]},{"type":"text","text":" callback."}]}]}]}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/truvideosdkcamera\/usingarcamera"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/truvideosdkcamera\/usingarcamera"]}],"references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraResult":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TruvideoSdkCameraResult","kind":"identifier"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraResult","abstract":[{"type":"text","text":"A result of the recording session."}],"title":"TruvideoSdkCameraResult","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraresult","navigatorTitle":[{"text":"TruvideoSdkCameraResult","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","title":"TruvideoSdkCamera","role":"collection","type":"topic","url":"\/documentation\/truvideosdkcamera","kind":"symbol","abstract":[{"text":"Store and capture photos and videos using a fully integrated camera system.","type":"text"}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraConfiguration":{"abstract":[{"text":"A configuration object for setting up the camera in ","type":"text"},{"type":"codeVoice","code":"TruvideoSdkCamera"},{"type":"text","text":"."}],"navigatorTitle":[{"text":"TruvideoSdkCameraConfiguration","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TruvideoSdkCameraConfiguration"}],"type":"topic","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraconfiguration","kind":"symbol","title":"TruvideoSdkCameraConfiguration","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraConfiguration"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/GettingStartedWithCamera":{"title":"Integrating the Camera into Your App","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/GettingStartedWithCamera","type":"topic","url":"\/documentation\/truvideosdkcamera\/gettingstartedwithcamera","role":"article","abstract":[{"type":"text","text":"Learn how to integrate the Camera in "},{"inlineContent":[{"text":"TruvideoSdkCamera","type":"text"}],"type":"strong"},{"text":" for photo and video capturing.","type":"text"}],"kind":"article"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/UsingCameraScanner":{"title":"Using the Camera Scanner","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/UsingCameraScanner","type":"topic","url":"\/documentation\/truvideosdkcamera\/usingcamerascanner","role":"article","abstract":[{"type":"text","text":"Learn how to integrate the Camera Scanner in "},{"inlineContent":[{"text":"TruvideoSdkCamera","type":"text"}],"type":"strong"},{"text":" to enable barcode and QR code","type":"text"},{"type":"text","text":" "},{"type":"text","text":"scanning with flash support, auto-close functionality, and validation capabilities."}],"kind":"article"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/GettingStartedWithCamera","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/UsingCameraScanner"],"title":"Related Documentation"},{"identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/GettingStartedWithCamera","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/UsingCameraScanner"],"generated":true,"title":"Essentials"}],"op":"replace"},{"value":"TruvideoSdkCameraResult","op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraResult\/title"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraResult\/fragments","value":[{"text":"TruvideoSdkCameraResult","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"TruvideoSdkCameraConfiguration","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraConfiguration\/title"},{"value":[{"text":"TruvideoSdkCameraConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraConfiguration\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}