{"primaryContentSections":[{"kind":"content","content":[{"type":"heading","text":"Overview","anchor":"Overview","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"The Scanner Camera in "},{"type":"strong","inlineContent":[{"text":"TruvideoSdkCamera","type":"text"}]},{"type":"text","text":" provides a fast and efficient way to scan various barcode"},{"text":" ","type":"text"},{"text":"formats. It allows applications to:","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"📡 "},{"inlineContent":[{"type":"text","text":"Scan barcodes"}],"type":"strong"},{"type":"text","text":" (Code-39, Code-93)"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"🏷️ "},{"type":"strong","inlineContent":[{"type":"text","text":"Read QR Codes"}]},{"type":"text","text":" for mobile interactions"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"📋 ","type":"text"},{"type":"strong","inlineContent":[{"text":"Detect DataMatrix codes","type":"text"}]},{"type":"text","text":" for logistics and inventory management"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"🔦 ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"Enable or disable flash"}]},{"text":" for scanning in low-light conditions","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"✅ "},{"inlineContent":[{"type":"text","text":"Perform automatic validation"}],"type":"strong"},{"type":"text","text":" before accepting a scan"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"🔄 ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"Auto-close the scanner"}]},{"type":"text","text":" after a successful scan"}],"type":"paragraph"}]}]},{"type":"paragraph","inlineContent":[{"text":"This guide explains how to configure and integrate the Camera using ","type":"text"},{"inlineContent":[{"text":"TruvideoSdkCamera","type":"text"}],"type":"strong"},{"text":".","type":"text"}]},{"text":"Pre-Requisites","level":2,"anchor":"Pre-Requisites","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"Before using the camera, ensure the necessary frameworks are imported and the user is","type":"text"},{"text":" ","type":"text"},{"type":"strong","inlineContent":[{"text":"authenticated","type":"text"}]},{"type":"text","text":"."}]},{"text":"Import Required Modules","anchor":"Import-Required-Modules","type":"heading","level":3},{"inlineContent":[{"type":"text","text":"To access camera functionalities, import the following frameworks:"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"text":"TruvideoSdk","type":"text"}]}]}]},{"content":[{"type":"paragraph","inlineContent":[{"inlineContent":[{"type":"text","text":"TruvideoCameraSdk"}],"type":"strong"}]}]}]},{"type":"heading","text":"Configuring the Camera","level":2,"anchor":"Configuring-the-Camera"},{"type":"paragraph","inlineContent":[{"type":"text","text":"To configure the "},{"inlineContent":[{"text":"Scanner Camera","type":"text"}],"type":"strong"},{"type":"text","text":", create a "},{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkScannerCameraConfiguration","isActive":true,"type":"reference"},{"text":" object with","type":"text"},{"type":"text","text":" "},{"type":"text","text":"your desired settings."}]},{"syntax":"swift","type":"codeListing","code":["    let cameraPreset = TruvideoSdkScannerCameraConfiguration(","        flashMode: .auto,","        orientation: .portrait,","        codeFormats: [.code39, .codeQR],","        validator: { scannedCode in","            return scannedCode.hasPrefix(\"VALID-\")","        },","        autoClose: true","    )"]},{"level":2,"type":"heading","anchor":"Integrating-the-Camera-Scanner-in-SwiftUI","text":"Integrating the Camera Scanner in SwiftUI"},{"inlineContent":[{"type":"text","text":"The Camera Scanner can be embedded in a SwiftUI view using the "},{"type":"strong","inlineContent":[{"text":"presentTruvideoSdkScannerCameraView","type":"text"}]},{"text":"","type":"text"},{"type":"text","text":" "},{"text":"modifier. This allows users to scan barcodes and QR codes directly within a SwiftUI-based application.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"To present the camera scanner, bind a ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"Boolean state"}]},{"type":"text","text":" to control visibility and pass in a camera configuration preset."}],"type":"paragraph"},{"syntax":"swift","code":["    var body: some View {","        VStack(spacing: 16) {","            Button(\"Open Scanner\") {","                showScanner = true","            }","        }","        .presentTruvideoSdkScannerCameraView(isPresented: $showScanner, preset: cameraPreset) { result in","            print(result)","        }","    }"],"type":"codeListing"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"article","seeAlsoSections":[{"identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/GettingStartedWithCamera","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/UsingARCamera"],"title":"Essentials","generated":true}],"sections":[],"variants":[{"paths":["\/documentation\/truvideosdkcamera\/usingcamerascanner"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/truvideosdkcamera\/usingcamerascanner"]}],"hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera"]]},"metadata":{"modules":[{"name":"TruvideoSdkCamera"}],"role":"article","title":"Using the Camera Scanner","roleHeading":"Article"},"abstract":[{"type":"text","text":"Learn how to integrate the Camera Scanner in "},{"type":"strong","inlineContent":[{"type":"text","text":"TruvideoSdkCamera"}]},{"text":" to enable barcode and QR code","type":"text"},{"type":"text","text":" "},{"text":"scanning with flash support, auto-close functionality, and validation capabilities.","type":"text"}],"identifier":{"url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/UsingCameraScanner","interfaceLanguage":"swift"},"references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/GettingStartedWithCamera":{"title":"Integrating the Camera into Your App","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/GettingStartedWithCamera","type":"topic","url":"\/documentation\/truvideosdkcamera\/gettingstartedwithcamera","role":"article","abstract":[{"type":"text","text":"Learn how to integrate the Camera in "},{"inlineContent":[{"text":"TruvideoSdkCamera","type":"text"}],"type":"strong"},{"text":" for photo and video capturing.","type":"text"}],"kind":"article"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/UsingARCamera":{"title":"Using the AR Camera","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/UsingARCamera","type":"topic","url":"\/documentation\/truvideosdkcamera\/usingarcamera","role":"article","abstract":[{"text":"Learn how to integrate the AR Camera in ","type":"text"},{"inlineContent":[{"text":"TruvideoSdkCamera","type":"text"}],"type":"strong"},{"type":"text","text":" to enable Augmented Reality (AR) experiences, including 3D"},{"type":"text","text":" "},{"type":"text","text":"object placement, distance measurement, and AR-enhanced video recording."}],"kind":"article"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","title":"TruvideoSdkCamera","role":"collection","type":"topic","url":"\/documentation\/truvideosdkcamera","kind":"symbol","abstract":[{"text":"Store and capture photos and videos using a fully integrated camera system.","type":"text"}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkScannerCameraConfiguration":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"TruvideoSdkScannerCameraConfiguration","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TruvideoSdkScannerCameraConfiguration"}],"abstract":[{"type":"text","text":"Configuration settings for the "},{"type":"strong","inlineContent":[{"text":"Truvideo Scanner Camera","type":"text"}]},{"type":"text","text":"."}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkscannercameraconfiguration","kind":"symbol","title":"TruvideoSdkScannerCameraConfiguration","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkScannerCameraConfiguration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/GettingStartedWithCamera","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/UsingARCamera"],"generated":true,"title":"Essentials"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkScannerCameraConfiguration\/title","op":"replace","value":"TruvideoSdkScannerCameraConfiguration"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkScannerCameraConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"TruvideoSdkScannerCameraConfiguration"}]}]}]}