{"relationshipsSections":[{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/SQ","doc:\/\/com.truvideo.TruvideoSdkCamera\/SY","doc:\/\/com.truvideo.TruvideoSdkCamera\/s8SendableP"]}],"hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"VertexAttributes"}]}]}],"kind":"symbol","metadata":{"roleHeading":"Structure","externalID":"c:@E@VertexAttributes","title":"VertexAttributes","symbolKind":"struct","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VertexAttributes","kind":"identifier"}],"modules":[{"name":"TruvideoSdkCamera"}],"navigatorTitle":[{"kind":"identifier","text":"VertexAttributes"}],"role":"symbol"},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/VertexAttributes"},"topicSections":[{"title":"Variables","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/kVertexAttributePosition","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/kVertexAttributeTexcoord"]},{"title":"Initializers","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/VertexAttributes\/init(_:)","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/VertexAttributes\/init(rawValue:)"]},{"identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/VertexAttributes\/rawValue"],"title":"Instance Properties"},{"title":"Default Implementations","generated":true,"identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/VertexAttributes\/Equatable-Implementations"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/truvideosdkcamera\/vertexattributes"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/truvideosdkcamera\/vertexattributes"]}],"references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/VertexAttributes/Equatable-Implementations":{"abstract":[],"role":"collectionGroup","type":"topic","title":"Equatable Implementations","url":"\/documentation\/truvideosdkcamera\/vertexattributes\/equatable-implementations","kind":"article","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/VertexAttributes\/Equatable-Implementations"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/VertexAttributes":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VertexAttributes","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"VertexAttributes"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/VertexAttributes","title":"VertexAttributes","role":"symbol","type":"topic","url":"\/documentation\/truvideosdkcamera\/vertexattributes","kind":"symbol","abstract":[]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","title":"TruvideoSdkCamera","role":"collection","type":"topic","url":"\/documentation\/truvideosdkcamera","kind":"symbol","abstract":[{"text":"Store and capture photos and videos using a fully integrated camera system.","type":"text"}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/VertexAttributes/rawValue":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/VertexAttributes\/rawValue","title":"rawValue","type":"topic","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"rawValue","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt32","preciseIdentifier":"s:s6UInt32V"}],"url":"\/documentation\/truvideosdkcamera\/vertexattributes\/rawvalue","kind":"symbol"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/VertexAttributes/init(_:)":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/VertexAttributes\/init(_:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s6UInt32V","text":"UInt32"},{"kind":"text","text":")"}],"kind":"symbol","title":"init(_:)","type":"topic","url":"\/documentation\/truvideosdkcamera\/vertexattributes\/init(_:)","abstract":[],"role":"symbol"},"doc://com.truvideo.TruvideoSdkCamera/SQ":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/kVertexAttributeTexcoord":{"title":"kVertexAttributeTexcoord","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/kVertexAttributeTexcoord","type":"topic","url":"\/documentation\/truvideosdkcamera\/kvertexattributetexcoord","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"kVertexAttributeTexcoord","kind":"identifier"},{"kind":"text","text":": "},{"text":"VertexAttributes","kind":"typeIdentifier","preciseIdentifier":"c:@E@VertexAttributes"}],"abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"kVertexAttributeTexcoord"}]},"doc://com.truvideo.TruvideoSdkCamera/s8SendableP":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/s8SendableP","title":"Swift.Sendable","type":"unresolvable"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/kVertexAttributePosition":{"kind":"symbol","navigatorTitle":[{"text":"kVertexAttributePosition","kind":"identifier"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/kVertexAttributePosition","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"kVertexAttributePosition"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@VertexAttributes","text":"VertexAttributes"}],"title":"kVertexAttributePosition","url":"\/documentation\/truvideosdkcamera\/kvertexattributeposition","abstract":[],"role":"symbol","type":"topic"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/VertexAttributes/init(rawValue:)":{"abstract":[],"title":"init(rawValue:)","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/VertexAttributes\/init(rawValue:)","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s6UInt32V","kind":"typeIdentifier","text":"UInt32"},{"kind":"text","text":")"}],"url":"\/documentation\/truvideosdkcamera\/vertexattributes\/init(rawvalue:)","role":"symbol","type":"topic"},"doc://com.truvideo.TruvideoSdkCamera/SY":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/SY","title":"Swift.RawRepresentable","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"path":"\/metadata\/title","op":"replace","value":"VertexAttributes"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"VertexAttributes","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"VertexAttributes"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/kVertexAttributePosition","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/kVertexAttributeTexcoord"]}]},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"typedef"},{"kind":"text","text":" "},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"VertexAttributes"},{"text":": ","kind":"text"},{"text":"unsigned int","kind":"typeIdentifier","preciseIdentifier":"c:i"},{"kind":"text","text":" { ... } "},{"kind":"identifier","text":"VertexAttributes"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1VertexAttributes\/title","value":"VertexAttributes"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1VertexAttributes\/fragments","value":[{"kind":"identifier","text":"VertexAttributes"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1kVertexAttributeTexcoord\/title","value":"kVertexAttributeTexcoord","op":"replace"},{"value":[{"kind":"identifier","text":"kVertexAttributeTexcoord"}],"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1kVertexAttributeTexcoord\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1kVertexAttributePosition\/title","op":"replace","value":"kVertexAttributePosition"},{"value":[{"text":"kVertexAttributePosition","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1kVertexAttributePosition\/fragments"}]}]}