{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraDevice\/resolutions"},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"The list of supported resolutions for this camera device."}],"kind":"symbol","metadata":{"title":"resolutions","modules":[{"name":"TruvideoSdkCamera"}],"roleHeading":"Instance Property","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"resolutions","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"TruvideoSdkCameraResolution","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraResolution"},{"text":"]","kind":"text"}],"externalID":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraDevice(py)resolutions","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"resolutions"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraDevice"]]},"variants":[{"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcameradevice\/resolutions"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcameradevice\/resolutions"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"resolutions"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraResolution","text":"TruvideoSdkCameraResolution","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraResolution","kind":"typeIdentifier"},{"kind":"text","text":"]"}]}]},{"content":[{"text":"Discussion","anchor":"discussion","level":2,"type":"heading"},{"inlineContent":[{"text":"Each resolution represents a width-height pair that defines the camera’s image capture capabilities.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraResolution":{"kind":"symbol","abstract":[],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraresolution","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TruvideoSdkCameraResolution","kind":"identifier"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraResolution","title":"TruvideoSdkCameraResolution","type":"topic","navigatorTitle":[{"text":"TruvideoSdkCameraResolution","kind":"identifier"}],"role":"symbol"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"kind":"symbol","abstract":[{"type":"text","text":"Store and capture photos and videos using a fully integrated camera system."}],"url":"\/documentation\/truvideosdkcamera","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","title":"TruvideoSdkCamera","type":"topic","role":"collection"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraDevice":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TruvideoSdkCameraDevice","kind":"identifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"TruvideoSdkCameraDevice","kind":"identifier"}],"abstract":[{"type":"text","text":"Represents a camera device available on the system."}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameradevice","type":"topic","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraDevice","title":"TruvideoSdkCameraDevice"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraDevice/resolutions":{"abstract":[{"type":"text","text":"The list of supported resolutions for this camera device."}],"title":"resolutions","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameradevice\/resolutions","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"resolutions","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraResolution","text":"TruvideoSdkCameraResolution"},{"kind":"text","text":"]"}],"kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"resolutions"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraDevice\/resolutions"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"resolutions","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"resolutions","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSArray<TruvideoSdkCameraResolution *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"resolutions","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"TruvideoSdkCameraResolution","op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraResolution\/title"},{"op":"replace","value":[{"text":"TruvideoSdkCameraResolution","kind":"identifier"}],"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraResolution\/fragments"},{"value":"TruvideoSdkCameraDevice","op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraDevice\/title"},{"value":[{"text":"TruvideoSdkCameraDevice","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraDevice\/fragments"},{"op":"replace","value":"resolutions","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraDevice~1resolutions\/title"},{"op":"replace","value":[{"kind":"identifier","text":"resolutions"}],"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraDevice~1resolutions\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}