{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sensorOrientation"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}]}]},{"kind":"content","content":[{"level":2,"anchor":"discussion","type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Represents the natural orientation of the camera sensor relative to the device’s display."}]}]}],"variants":[{"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcameradevice\/sensororientation"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcameradevice\/sensororientation"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraDevice"]]},"metadata":{"roleHeading":"Instance Property","externalID":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraDevice(py)sensorOrientation","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"sensorOrientation"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"sensorOrientation","kind":"identifier"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"title":"sensorOrientation","role":"symbol","modules":[{"name":"TruvideoSdkCamera"}]},"sections":[],"identifier":{"url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraDevice\/sensorOrientation","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"text":"The sensor orientation of the camera, in degrees.","type":"text"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraDevice":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TruvideoSdkCameraDevice","kind":"identifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"TruvideoSdkCameraDevice","kind":"identifier"}],"abstract":[{"type":"text","text":"Represents a camera device available on the system."}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameradevice","type":"topic","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraDevice","title":"TruvideoSdkCameraDevice"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"kind":"symbol","abstract":[{"type":"text","text":"Store and capture photos and videos using a fully integrated camera system."}],"url":"\/documentation\/truvideosdkcamera","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","title":"TruvideoSdkCamera","type":"topic","role":"collection"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraDevice/sensorOrientation":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraDevice\/sensorOrientation","kind":"symbol","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sensorOrientation","kind":"identifier"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"title":"sensorOrientation","abstract":[{"text":"The sensor orientation of the camera, in degrees.","type":"text"}],"role":"symbol","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameradevice\/sensororientation","navigatorTitle":[{"text":"sensorOrientation","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"sensorOrientation"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"sensorOrientation","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sensorOrientation"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraDevice\/title","op":"replace","value":"TruvideoSdkCameraDevice"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraDevice\/fragments","value":[{"kind":"identifier","text":"TruvideoSdkCameraDevice"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraDevice~1sensorOrientation\/title","op":"replace","value":"sensorOrientation"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraDevice~1sensorOrientation\/fragments","value":[{"text":"sensorOrientation","kind":"identifier"}]}]}]}