{"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"metadata":{"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NSSinglePicture"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraMediaMode","kind":"typeIdentifier","text":"TruvideoSdkCameraMediaMode"}],"title":"NSSinglePicture()","navigatorTitle":[{"kind":"identifier","text":"NSSinglePicture"}],"roleHeading":"Type Method","role":"symbol","modules":[{"name":"TruvideoSdkCamera"}],"symbolKind":"method","externalID":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraMediaMode(cm)NSSinglePicture"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSSinglePicture"},{"text":"() -> ","kind":"text"},{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraMediaMode","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraMediaMode","kind":"typeIdentifier","text":"TruvideoSdkCameraMediaMode"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraMediaMode"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraMediaMode\/NSSinglePicture()"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcameramediamode\/nssinglepicture()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcameramediamode\/nssinglepicture()"]}],"references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraMediaMode":{"title":"TruvideoSdkCameraMediaMode","role":"symbol","abstract":[],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TruvideoSdkCameraMediaMode"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraMediaMode","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameramediamode","navigatorTitle":[{"text":"TruvideoSdkCameraMediaMode","kind":"identifier"}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"kind":"symbol","abstract":[{"type":"text","text":"Store and capture photos and videos using a fully integrated camera system."}],"url":"\/documentation\/truvideosdkcamera","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","title":"TruvideoSdkCamera","type":"topic","role":"collection"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraMediaMode/NSSinglePicture()":{"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameramediamode\/nssinglepicture()","navigatorTitle":[{"kind":"identifier","text":"NSSinglePicture"}],"abstract":[],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraMediaMode\/NSSinglePicture()","role":"symbol","title":"NSSinglePicture()","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSSinglePicture"},{"text":"() -> ","kind":"text"},{"text":"TruvideoSdkCameraMediaMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraMediaMode"}],"type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"NSSinglePicture"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"NSSinglePicture"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraMediaMode","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraMediaMode","kind":"typeIdentifier","text":"TruvideoSdkCameraMediaMode"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"NSSinglePicture"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraMediaMode\/title","value":"TruvideoSdkCameraMediaMode"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraMediaMode\/fragments","value":[{"text":"TruvideoSdkCameraMediaMode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraMediaMode~1NSSinglePicture()\/title","value":"NSSinglePicture"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraMediaMode~1NSSinglePicture()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"NSSinglePicture","kind":"identifier"}],"op":"replace"}]}]}