{"metadata":{"title":"NSVideoAndPicture(videoCount:pictureCount:videoDuration:)","modules":[{"name":"TruvideoSdkCamera"}],"roleHeading":"Type Method","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSVideoAndPicture","kind":"identifier"},{"text":"(","kind":"text"},{"text":"videoCount","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?, "},{"text":"pictureCount","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"?, ","kind":"text"},{"text":"videoDuration","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"TruvideoSdkCameraMediaMode","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraMediaMode"}],"externalID":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraMediaMode(cm)NSVideoAndPictureWithVideoCount:pictureCount:videoDuration:","symbolKind":"method","navigatorTitle":[{"text":"NSVideoAndPictureWithVideoCount:pictureCount:videoDuration:","kind":"identifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraMediaMode\/NSVideoAndPicture(videoCount:pictureCount:videoDuration:)"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSVideoAndPicture"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"videoCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"? = nil, ","kind":"text"},{"text":"pictureCount","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"videoDuration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"text":"? = nil) -> ","kind":"text"},{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraMediaMode","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraMediaMode","text":"TruvideoSdkCameraMediaMode","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraMediaMode"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcameramediamode\/nsvideoandpicture(videocount:picturecount:videoduration:)"]},{"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcameramediamode\/nsvideoandpicture(videocount:picturecount:videoduration:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraMediaMode":{"title":"TruvideoSdkCameraMediaMode","role":"symbol","abstract":[],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TruvideoSdkCameraMediaMode"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraMediaMode","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameramediamode","navigatorTitle":[{"text":"TruvideoSdkCameraMediaMode","kind":"identifier"}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"kind":"symbol","abstract":[{"type":"text","text":"Store and capture photos and videos using a fully integrated camera system."}],"url":"\/documentation\/truvideosdkcamera","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","title":"TruvideoSdkCamera","type":"topic","role":"collection"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraMediaMode/NSVideoAndPicture(videoCount:pictureCount:videoDuration:)":{"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameramediamode\/nsvideoandpicture(videocount:picturecount:videoduration:)","navigatorTitle":[{"kind":"identifier","text":"NSVideoAndPictureWithVideoCount:pictureCount:videoDuration:"}],"abstract":[],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraMediaMode\/NSVideoAndPicture(videoCount:pictureCount:videoDuration:)","role":"symbol","title":"NSVideoAndPicture(videoCount:pictureCount:videoDuration:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSVideoAndPicture"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"videoCount"},{"text":": ","kind":"text"},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"pictureCount"},{"kind":"text","text":": "},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"videoDuration"},{"kind":"text","text":": "},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraMediaMode","kind":"typeIdentifier","text":"TruvideoSdkCameraMediaMode"}],"type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"path":"\/metadata\/title","value":"NSVideoAndPictureWithVideoCount:pictureCount:videoDuration:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"NSVideoAndPictureWithVideoCount:pictureCount:videoDuration:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraMediaMode","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraMediaMode","kind":"typeIdentifier","text":"TruvideoSdkCameraMediaMode"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"NSVideoAndPictureWithVideoCount:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":" *) "},{"text":"videoCount","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"pictureCount:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"pictureCount"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoDuration:"},{"kind":"text","text":"("},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":" *) ","kind":"text"},{"text":"videoDuration","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraMediaMode\/title","value":"TruvideoSdkCameraMediaMode"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraMediaMode\/fragments","value":[{"kind":"identifier","text":"TruvideoSdkCameraMediaMode"}],"op":"replace"},{"value":"NSVideoAndPictureWithVideoCount:pictureCount:videoDuration:","op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraMediaMode~1NSVideoAndPicture(videoCount:pictureCount:videoDuration:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraMediaMode~1NSVideoAndPicture(videoCount:pictureCount:videoDuration:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"NSVideoAndPictureWithVideoCount:pictureCount:videoDuration:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}