{"sections":[],"identifier":{"url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraProvider\/shared","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"shared","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(pl)TruvideoSdkCameraInterface","text":"TruvideoSdkCameraInterface","kind":"typeIdentifier","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraInterface"}]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Discussion","anchor":"discussion","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This instance provides access to all SDK camera features."}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcameraprovider\/shared"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcameraprovider\/shared"]}],"abstract":[{"type":"text","text":"The shared instance for accessing "},{"code":"TruvideoSdkCamera","type":"codeVoice"},{"type":"text","text":" functionalities."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"roleHeading":"Type Property","externalID":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraProvider(cpy)shared","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"shared"},{"text":": ","kind":"text"},{"text":"TruvideoSdkCameraInterface","kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(pl)TruvideoSdkCameraInterface"}],"symbolKind":"property","modules":[{"name":"TruvideoSdkCamera"}],"title":"shared","role":"symbol","navigatorTitle":[{"text":"shared","kind":"identifier"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraProvider"]]},"references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"kind":"symbol","abstract":[{"type":"text","text":"Store and capture photos and videos using a fully integrated camera system."}],"url":"\/documentation\/truvideosdkcamera","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","title":"TruvideoSdkCamera","type":"topic","role":"collection"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraProvider/shared":{"navigatorTitle":[{"kind":"identifier","text":"shared"}],"abstract":[{"type":"text","text":"The shared instance for accessing "},{"type":"codeVoice","code":"TruvideoSdkCamera"},{"type":"text","text":" functionalities."}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"shared","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(pl)TruvideoSdkCameraInterface","kind":"typeIdentifier","text":"TruvideoSdkCameraInterface"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraProvider\/shared","kind":"symbol","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraprovider\/shared","title":"shared","type":"topic","role":"symbol"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraProvider":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TruvideoSdkCameraProvider","kind":"identifier"}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraprovider","title":"TruvideoSdkCameraProvider","abstract":[{"type":"text","text":"Provides a shared instance for accessing "},{"type":"codeVoice","code":"TruvideoSdkCamera"},{"text":" functionalities.","type":"text"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraProvider","navigatorTitle":[{"text":"TruvideoSdkCameraProvider","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraInterface":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"TruvideoSdkCameraInterface","kind":"identifier"}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcamerainterface","title":"TruvideoSdkCameraInterface","abstract":[{"type":"text","text":"Defines the interface for accessing "},{"code":"TruvideoSdkCamera","type":"codeVoice"},{"type":"text","text":" functionalities."}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraInterface","navigatorTitle":[{"text":"TruvideoSdkCameraInterface","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Property"},{"op":"replace","path":"\/metadata\/title","value":"shared"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"shared","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Qo@M@TruvideoSdkCamera@objc(pl)TruvideoSdkCameraInterface","text":"id<TruvideoSdkCameraInterface>","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"shared"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraProvider~1shared\/title","op":"replace","value":"shared"},{"value":[{"text":"shared","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraProvider~1shared\/fragments"},{"value":"TruvideoSdkCameraProvider","op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraProvider\/title"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraProvider\/fragments","value":[{"text":"TruvideoSdkCameraProvider","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"TruvideoSdkCameraInterface","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraInterface\/title"},{"value":[{"text":"TruvideoSdkCameraInterface","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraInterface\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}