{"metadata":{"symbolKind":"property","externalID":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraScannerCode(py)format","modules":[{"name":"TruvideoSdkCamera"}],"roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"format"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraScannerCodeFormat","text":"TruvideoSdkCameraScannerCodeFormat","kind":"typeIdentifier"}],"title":"format","navigatorTitle":[{"kind":"identifier","text":"format"}],"role":"symbol"},"sections":[],"abstract":[{"text":"The type of barcode that was scanned.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraScannerCode\/format"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcamerascannercode\/format"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcamerascannercode\/format"]}],"hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraScannerCode"]]},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"format"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraScannerCodeFormat","text":"TruvideoSdkCameraScannerCodeFormat","preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraScannerCodeFormat","kind":"typeIdentifier"}]}]}],"references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"kind":"symbol","url":"\/documentation\/truvideosdkcamera","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","type":"topic","abstract":[{"text":"Store and capture photos and videos using a fully integrated camera system.","type":"text"}],"title":"TruvideoSdkCamera","role":"collection"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraScannerCode/format":{"type":"topic","abstract":[{"type":"text","text":"The type of barcode that was scanned."}],"title":"format","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"format","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraScannerCodeFormat","text":"TruvideoSdkCameraScannerCodeFormat"}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcamerascannercode\/format","kind":"symbol","navigatorTitle":[{"text":"format","kind":"identifier"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraScannerCode\/format","role":"symbol"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraScannerCodeFormat":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"TruvideoSdkCameraScannerCodeFormat","kind":"identifier"}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcamerascannercodeformat","abstract":[{"text":"Defines the supported barcode and QR code formats for the scanner.","type":"text"}],"title":"TruvideoSdkCameraScannerCodeFormat","type":"topic","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraScannerCodeFormat","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"TruvideoSdkCameraScannerCodeFormat","kind":"identifier"}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraScannerCode":{"type":"topic","abstract":[{"text":"Represents the result of a barcode or QR code scan.","type":"text"}],"title":"TruvideoSdkCameraScannerCode","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TruvideoSdkCameraScannerCode","kind":"identifier"}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcamerascannercode","kind":"symbol","navigatorTitle":[{"text":"TruvideoSdkCameraScannerCode","kind":"identifier"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraScannerCode","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"format","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"format"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraScannerCodeFormat","text":"TruvideoSdkCameraScannerCodeFormat","preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraScannerCodeFormat","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"format"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"value":"format","op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraScannerCode~1format\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraScannerCode~1format\/fragments","value":[{"kind":"identifier","text":"format"}]},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraScannerCodeFormat\/title","value":"TruvideoSdkCameraScannerCodeFormat"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraScannerCodeFormat\/fragments","value":[{"kind":"identifier","text":"TruvideoSdkCameraScannerCodeFormat"}]},{"value":"TruvideoSdkCameraScannerCode","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraScannerCode\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraScannerCode\/fragments","value":[{"text":"TruvideoSdkCameraScannerCode","kind":"identifier"}]}]}]}