{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraMedia"]]},"kind":"symbol","metadata":{"roleHeading":"Instance Property","externalID":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraMedia(py)createdAt","symbolKind":"property","navigatorTitle":[{"text":"createdAt","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"createdAt","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"title":"createdAt","role":"symbol","modules":[{"name":"TruvideoSdkCamera"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcameramedia\/createdat"]},{"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcameramedia\/createdat"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"createdAt"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraMedia\/createdAt","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"The timestamp when the media was created.","type":"text"}],"references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"kind":"symbol","abstract":[{"type":"text","text":"Store and capture photos and videos using a fully integrated camera system."}],"url":"\/documentation\/truvideosdkcamera","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","title":"TruvideoSdkCamera","type":"topic","role":"collection"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraMedia":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TruvideoSdkCameraMedia","kind":"identifier"}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameramedia","title":"TruvideoSdkCameraMedia","abstract":[{"type":"text","text":"A class representing a media file captured by the Truvideo SDK camera."}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraMedia","navigatorTitle":[{"text":"TruvideoSdkCameraMedia","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraMedia/createdAt":{"kind":"symbol","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraMedia\/createdAt","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"createdAt"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"title":"createdAt","abstract":[{"text":"The timestamp when the media was created.","type":"text"}],"role":"symbol","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameramedia\/createdat","navigatorTitle":[{"text":"createdAt","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"createdAt"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"kind":"identifier","text":"createdAt"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"double","preciseIdentifier":"c:d","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"createdAt"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"value":"TruvideoSdkCameraMedia","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraMedia\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraMedia\/fragments","value":[{"text":"TruvideoSdkCameraMedia","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraMedia~1createdAt\/title","value":"createdAt","op":"replace"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraMedia~1createdAt\/fragments","op":"replace","value":[{"text":"createdAt","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}