{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"landscapeRight","kind":"identifier"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcameraorientation\/landscaperight"]},{"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcameraorientation\/landscaperight"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Case","symbolKind":"case","externalID":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraOrientation@TruvideoSdkCameraOrientationLandscapeRight","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"landscapeRight","kind":"identifier"}],"navigatorTitle":[{"text":"TruvideoSdkCameraOrientationLandscapeRight","kind":"identifier"}],"title":"TruvideoSdkCameraOrientation.landscapeRight","role":"symbol","modules":[{"name":"TruvideoSdkCamera"}]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraOrientation\/landscapeRight"},"hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraOrientation"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","abstract":[{"text":"Landscape mode with the device rotated right.","type":"text"}],"references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraOrientation/landscapeRight":{"role":"symbol","type":"topic","abstract":[{"text":"Landscape mode with the device rotated right.","type":"text"}],"title":"TruvideoSdkCameraOrientation.landscapeRight","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"landscapeRight","kind":"identifier"}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraorientation\/landscaperight","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraOrientation\/landscapeRight","navigatorTitle":[{"text":"TruvideoSdkCameraOrientationLandscapeRight","kind":"identifier"}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"kind":"symbol","url":"\/documentation\/truvideosdkcamera","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","type":"topic","abstract":[{"text":"Store and capture photos and videos using a fully integrated camera system.","type":"text"}],"title":"TruvideoSdkCamera","role":"collection"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraOrientation":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"TruvideoSdkCameraOrientation","kind":"identifier"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraOrientation","role":"symbol","type":"topic","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraorientation","title":"TruvideoSdkCameraOrientation","abstract":[{"type":"text","text":"Defines the camera orientation for media capture."}],"kind":"symbol","navigatorTitle":[{"text":"TruvideoSdkCameraOrientation","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"TruvideoSdkCameraOrientationLandscapeRight"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"TruvideoSdkCameraOrientationLandscapeRight","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"TruvideoSdkCameraOrientationLandscapeRight"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraOrientation~1landscapeRight\/title","value":"TruvideoSdkCameraOrientationLandscapeRight"},{"op":"replace","value":[{"text":"TruvideoSdkCameraOrientationLandscapeRight","kind":"identifier"}],"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraOrientation~1landscapeRight\/fragments"},{"value":"TruvideoSdkCameraOrientation","op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraOrientation\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraOrientation\/fragments","value":[{"kind":"identifier","text":"TruvideoSdkCameraOrientation"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}