{"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"autoClose"}],"roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"autoClose"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"modules":[{"name":"TruvideoSdkCamera"}],"symbolKind":"property","externalID":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkScannerCameraConfiguration(py)autoClose","title":"autoClose","role":"symbol"},"abstract":[{"text":"Determines whether the scanner ","type":"text"},{"inlineContent":[{"text":"automatically closes","type":"text"}],"type":"strong"},{"type":"text","text":" after a successful scan."}],"kind":"symbol","variants":[{"paths":["\/documentation\/truvideosdkcamera\/truvideosdkscannercameraconfiguration\/autoclose"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/truvideosdkcamera\/truvideosdkscannercameraconfiguration\/autoclose"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"autoClose","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkScannerCameraConfiguration\/autoClose","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkScannerCameraConfiguration"]]},"references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","title":"TruvideoSdkCamera","role":"collection","type":"topic","url":"\/documentation\/truvideosdkcamera","kind":"symbol","abstract":[{"text":"Store and capture photos and videos using a fully integrated camera system.","type":"text"}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkScannerCameraConfiguration/autoClose":{"title":"autoClose","type":"topic","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkScannerCameraConfiguration\/autoClose","role":"symbol","abstract":[{"text":"Determines whether the scanner ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"automatically closes"}]},{"text":" after a successful scan.","type":"text"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"autoClose","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"autoClose"}],"kind":"symbol","url":"\/documentation\/truvideosdkcamera\/truvideosdkscannercameraconfiguration\/autoclose"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkScannerCameraConfiguration":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"TruvideoSdkScannerCameraConfiguration","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TruvideoSdkScannerCameraConfiguration"}],"abstract":[{"type":"text","text":"Configuration settings for the "},{"type":"strong","inlineContent":[{"text":"Truvideo Scanner Camera","type":"text"}]},{"type":"text","text":"."}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkscannercameraconfiguration","kind":"symbol","title":"TruvideoSdkScannerCameraConfiguration","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkScannerCameraConfiguration"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"autoClose","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"autoClose","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"text":" ","kind":"text"},{"kind":"identifier","text":"autoClose"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace"},{"op":"replace","value":"autoClose","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkScannerCameraConfiguration~1autoClose\/title"},{"value":[{"text":"autoClose","kind":"identifier"}],"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkScannerCameraConfiguration~1autoClose\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkScannerCameraConfiguration\/title","op":"replace","value":"TruvideoSdkScannerCameraConfiguration"},{"value":[{"text":"TruvideoSdkScannerCameraConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkScannerCameraConfiguration\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}