{"metadata":{"externalID":"c:@M@TruvideoSdkCamera@objc(pl)TruvideoSdkCameraInterface(py)camera","symbolKind":"property","modules":[{"name":"TruvideoSdkCamera"}],"required":true,"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"camera"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(pl)TruvideoSdkCameraDelegate","text":"TruvideoSdkCameraDelegate","kind":"typeIdentifier"}],"title":"camera","navigatorTitle":[{"text":"camera","kind":"identifier"}],"role":"symbol"},"identifier":{"url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraInterface\/camera","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcamerainterface\/camera"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcamerainterface\/camera"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"camera"},{"text":": ","kind":"text"},{"text":"TruvideoSdkCameraDelegate","kind":"typeIdentifier","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraDelegate","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(pl)TruvideoSdkCameraDelegate"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraInterface"]]},"abstract":[{"type":"text","text":"Provides the main camera delegate, responsible for handling SDK camera operations."}],"kind":"symbol","references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraInterface/camera":{"url":"\/documentation\/truvideosdkcamera\/truvideosdkcamerainterface\/camera","role":"symbol","required":true,"navigatorTitle":[{"kind":"identifier","text":"camera"}],"abstract":[{"text":"Provides the main camera delegate, responsible for handling SDK camera operations.","type":"text"}],"kind":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"camera","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(pl)TruvideoSdkCameraDelegate","text":"TruvideoSdkCameraDelegate","kind":"typeIdentifier"}],"title":"camera","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraInterface\/camera"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraDelegate":{"abstract":[{"text":"Defines the delegate responsible for retrieving camera information.","type":"text"}],"title":"TruvideoSdkCameraDelegate","navigatorTitle":[{"text":"TruvideoSdkCameraDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"TruvideoSdkCameraDelegate","kind":"identifier"}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameradelegate","kind":"symbol","type":"topic","role":"symbol"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraInterface":{"url":"\/documentation\/truvideosdkcamera\/truvideosdkcamerainterface","role":"symbol","navigatorTitle":[{"text":"TruvideoSdkCameraInterface","kind":"identifier"}],"abstract":[{"type":"text","text":"Defines the interface for accessing "},{"code":"TruvideoSdkCamera","type":"codeVoice"},{"text":" functionalities.","type":"text"}],"kind":"symbol","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TruvideoSdkCameraInterface"}],"title":"TruvideoSdkCameraInterface","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraInterface"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"kind":"symbol","url":"\/documentation\/truvideosdkcamera","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","type":"topic","abstract":[{"text":"Store and capture photos and videos using a fully integrated camera system.","type":"text"}],"title":"TruvideoSdkCamera","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"camera","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"camera","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Qo@M@TruvideoSdkCamera@objc(pl)TruvideoSdkCameraDelegate","text":"id<TruvideoSdkCameraDelegate>","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"camera","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"value":"camera","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraInterface~1camera\/title","op":"replace"},{"value":[{"text":"camera","kind":"identifier"}],"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraInterface~1camera\/fragments","op":"replace"},{"value":"TruvideoSdkCameraDelegate","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraDelegate\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraDelegate\/fragments","value":[{"text":"TruvideoSdkCameraDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraInterface\/title","value":"TruvideoSdkCameraInterface"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraInterface\/fragments","value":[{"text":"TruvideoSdkCameraInterface","kind":"identifier"}],"op":"replace"}]}]}