{"hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraInformation"]]},"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"backCamera"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraDevice","text":"TruvideoSdkCameraDevice","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraDevice"},{"text":"?","kind":"text"}],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraInformation\/backCamera"},"abstract":[{"text":"The back-facing camera device, if available.","type":"text"}],"variants":[{"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcamerainformation\/backcamera"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcamerainformation\/backcamera"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"backCamera"}],"role":"symbol","modules":[{"name":"TruvideoSdkCamera"}],"symbolKind":"property","externalID":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraInformation(py)backCamera","roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"backCamera","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TruvideoSdkCameraDevice","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraDevice"},{"text":"?","kind":"text"}],"title":"backCamera"},"references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"kind":"symbol","url":"\/documentation\/truvideosdkcamera","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","type":"topic","abstract":[{"text":"Store and capture photos and videos using a fully integrated camera system.","type":"text"}],"title":"TruvideoSdkCamera","role":"collection"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraInformation/backCamera":{"navigatorTitle":[{"kind":"identifier","text":"backCamera"}],"kind":"symbol","role":"symbol","type":"topic","title":"backCamera","abstract":[{"type":"text","text":"The back-facing camera device, if available."}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcamerainformation\/backcamera","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraInformation\/backCamera","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"backCamera","kind":"identifier"},{"kind":"text","text":": "},{"text":"TruvideoSdkCameraDevice","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraDevice","kind":"typeIdentifier"},{"kind":"text","text":"?"}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraInformation":{"navigatorTitle":[{"kind":"identifier","text":"TruvideoSdkCameraInformation"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraInformation","type":"topic","title":"TruvideoSdkCameraInformation","url":"\/documentation\/truvideosdkcamera\/truvideosdkcamerainformation","abstract":[{"type":"text","text":"Provides detailed information about available camera devices."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TruvideoSdkCameraInformation","kind":"identifier"}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraDevice":{"title":"TruvideoSdkCameraDevice","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameradevice","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TruvideoSdkCameraDevice"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraDevice","kind":"symbol","abstract":[{"type":"text","text":"Represents a camera device available on the system."}],"navigatorTitle":[{"text":"TruvideoSdkCameraDevice","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"backCamera"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"backCamera"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraDevice","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraDevice","text":"TruvideoSdkCameraDevice"},{"kind":"text","text":" * "},{"kind":"identifier","text":"backCamera"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"value":"backCamera","op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraInformation~1backCamera\/title"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraInformation~1backCamera\/fragments","op":"replace","value":[{"kind":"identifier","text":"backCamera"}]},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraInformation\/title","value":"TruvideoSdkCameraInformation","op":"replace"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraInformation\/fragments","value":[{"kind":"identifier","text":"TruvideoSdkCameraInformation"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraDevice\/title","op":"replace","value":"TruvideoSdkCameraDevice"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraDevice\/fragments","value":[{"text":"TruvideoSdkCameraDevice","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}