{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"configureTruvideoSdkAppDelegate"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"appDelegate"},{"kind":"text","text":": "},{"text":"TruvideoSdkCameraAppDelegate","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraAppDelegate","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(pl)TruvideoSdkCameraAppDelegate","kind":"typeIdentifier"},{"kind":"text","text":")"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The ","type":"text"},{"code":"TruvideoSdkCameraAppDelegate","type":"codeVoice"},{"type":"text","text":" instance handling app-wide camera events."}],"type":"paragraph"}],"name":"appDelegate"}]},{"content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"inlineContent":[{"type":"text","text":"This method should be called during application setup to "},{"inlineContent":[{"type":"text","text":"initialize the camera SDK"}],"type":"strong"},{"type":"text","text":"."}],"type":"paragraph"}],"kind":"content"}],"abstract":[{"text":"Configures the Truvideo SDK with an application delegate.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraInterface"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraInterface\/configureTruvideoSdkAppDelegate(_:)","interfaceLanguage":"swift"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcamerainterface\/configuretruvideosdkappdelegate(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcamerainterface\/configuretruvideosdkappdelegate(_:)"]}],"metadata":{"symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"TruvideoSdkCamera"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"configureTruvideoSdkAppDelegate","kind":"identifier"},{"kind":"text","text":"("},{"text":"TruvideoSdkCameraAppDelegate","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(pl)TruvideoSdkCameraAppDelegate","kind":"typeIdentifier"},{"text":")","kind":"text"}],"required":true,"title":"configureTruvideoSdkAppDelegate(_:)","navigatorTitle":[{"kind":"identifier","text":"configureTruvideoSdkAppDelegate:"}],"externalID":"c:@M@TruvideoSdkCamera@objc(pl)TruvideoSdkCameraInterface(im)configureTruvideoSdkAppDelegate:","role":"symbol"},"kind":"symbol","references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraInterface/configureTruvideoSdkAppDelegate(_:)":{"kind":"symbol","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraInterface\/configureTruvideoSdkAppDelegate(_:)","navigatorTitle":[{"kind":"identifier","text":"configureTruvideoSdkAppDelegate:"}],"abstract":[{"text":"Configures the Truvideo SDK with an application delegate.","type":"text"}],"required":true,"title":"configureTruvideoSdkAppDelegate(_:)","url":"\/documentation\/truvideosdkcamera\/truvideosdkcamerainterface\/configuretruvideosdkappdelegate(_:)","type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"configureTruvideoSdkAppDelegate"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(pl)TruvideoSdkCameraAppDelegate","text":"TruvideoSdkCameraAppDelegate"},{"text":")","kind":"text"}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraInterface":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"TruvideoSdkCameraInterface","kind":"identifier"}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcamerainterface","title":"TruvideoSdkCameraInterface","abstract":[{"type":"text","text":"Defines the interface for accessing "},{"code":"TruvideoSdkCamera","type":"codeVoice"},{"type":"text","text":" functionalities."}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraInterface","navigatorTitle":[{"text":"TruvideoSdkCameraInterface","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraAppDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"TruvideoSdkCameraAppDelegate","kind":"identifier"}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraappdelegate","title":"TruvideoSdkCameraAppDelegate","abstract":[{"type":"text","text":"Defines the application delegate for handling camera-related configurations."}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraAppDelegate","navigatorTitle":[{"text":"TruvideoSdkCameraAppDelegate","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"kind":"symbol","abstract":[{"type":"text","text":"Store and capture photos and videos using a fully integrated camera system."}],"url":"\/documentation\/truvideosdkcamera","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","title":"TruvideoSdkCamera","type":"topic","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"configureTruvideoSdkAppDelegate:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"configureTruvideoSdkAppDelegate:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"configureTruvideoSdkAppDelegate:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@TruvideoSdkCamera@objc(pl)TruvideoSdkCameraAppDelegate","text":"id<TruvideoSdkCameraAppDelegate>"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"appDelegate"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"configureTruvideoSdkAppDelegate:","op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraInterface~1configureTruvideoSdkAppDelegate(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraInterface~1configureTruvideoSdkAppDelegate(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"configureTruvideoSdkAppDelegate:"}]},{"value":"TruvideoSdkCameraInterface","op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraInterface\/title"},{"value":[{"kind":"identifier","text":"TruvideoSdkCameraInterface"}],"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraInterface\/fragments"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraAppDelegate\/title","op":"replace","value":"TruvideoSdkCameraAppDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraAppDelegate\/fragments","value":[{"text":"TruvideoSdkCameraAppDelegate","kind":"identifier"}]}]}]}