{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"instantiate"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"lensFacing","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"TruvideoSdkCameraLensFacing","kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraLensFacing","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraLensFacing"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"flashMode"},{"text":": ","kind":"text"},{"text":"TruvideoSdkCameraFlashMode","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraFlashMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraFlashMode"},{"text":", ","kind":"text"},{"text":"orientation","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraOrientation","text":"TruvideoSdkCameraOrientation","preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraOrientation","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"outputPath","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"frontResolutions"},{"kind":"text","text":": ["},{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraResolution","text":"TruvideoSdkCameraResolution","kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraResolution"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"frontResolution"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TruvideoSdkCameraResolution","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraResolution","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraResolution"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"backResolutions"},{"kind":"text","text":": ["},{"text":"TruvideoSdkCameraResolution","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraResolution","kind":"typeIdentifier","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraResolution"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"backResolution"},{"kind":"text","text":": "},{"text":"TruvideoSdkCameraResolution","kind":"typeIdentifier","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraResolution","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraResolution"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"mode"},{"kind":"text","text":": "},{"text":"TruvideoSdkCameraMediaMode","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraMediaMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraMediaMode"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraConfiguration","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraConfiguration","kind":"typeIdentifier","text":"TruvideoSdkCameraConfiguration"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"text":"Return Value","level":2,"anchor":"return-value","type":"heading"},{"inlineContent":[{"type":"text","text":"A new "},{"code":"TruvideoSdkCameraConfiguration","type":"codeVoice"},{"type":"text","text":" instance."}],"type":"paragraph"}],"kind":"content"}],"metadata":{"modules":[{"name":"TruvideoSdkCamera"}],"title":"instantiate(with:flashMode:orientation:outputPath:frontResolutions:frontResolution:backResolutions:backResolution:mode:)","symbolKind":"method","roleHeading":"Type Method","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"instantiate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"text":"TruvideoSdkCameraLensFacing","kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraLensFacing"},{"text":", ","kind":"text"},{"text":"flashMode","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraFlashMode","text":"TruvideoSdkCameraFlashMode"},{"text":", ","kind":"text"},{"text":"orientation","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TruvideoSdkCameraOrientation","preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraOrientation","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"outputPath","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"frontResolutions"},{"kind":"text","text":": ["},{"text":"TruvideoSdkCameraResolution","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraResolution","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"frontResolution"},{"kind":"text","text":": "},{"text":"TruvideoSdkCameraResolution","kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraResolution"},{"text":"?, ","kind":"text"},{"text":"backResolutions","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraResolution","kind":"typeIdentifier","text":"TruvideoSdkCameraResolution"},{"text":"], ","kind":"text"},{"text":"backResolution","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraResolution","kind":"typeIdentifier","text":"TruvideoSdkCameraResolution"},{"kind":"text","text":"?, "},{"text":"mode","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TruvideoSdkCameraMediaMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraMediaMode"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraConfiguration","text":"TruvideoSdkCameraConfiguration","kind":"typeIdentifier"}],"externalID":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraConfiguration(cm)instantiateWith:flashMode:orientation:outputPath:frontResolutions:frontResolution:backResolutions:backResolution:mode:","navigatorTitle":[{"text":"instantiateWith:flashMode:orientation:outputPath:frontResolutions:frontResolution:backResolutions:backResolution:mode:","kind":"identifier"}]},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcameraconfiguration\/instantiate(with:flashmode:orientation:outputpath:frontresolutions:frontresolution:backresolutions:backresolution:mode:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcameraconfiguration\/instantiate(with:flashmode:orientation:outputpath:frontresolutions:frontresolution:backresolutions:backresolution:mode:)"]}],"identifier":{"url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraConfiguration\/instantiate(with:flashMode:orientation:outputPath:frontResolutions:frontResolution:backResolutions:backResolution:mode:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraConfiguration"]]},"sections":[],"abstract":[{"type":"text","text":"Instantiates a new "},{"type":"codeVoice","code":"TruvideoSdkCameraConfiguration"},{"type":"text","text":" using static method syntax."}],"references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraConfiguration/instantiate(with:flashMode:orientation:outputPath:frontResolutions:frontResolution:backResolutions:backResolution:mode:)":{"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraconfiguration\/instantiate(with:flashmode:orientation:outputpath:frontresolutions:frontresolution:backresolutions:backresolution:mode:)","type":"topic","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraConfiguration\/instantiate(with:flashMode:orientation:outputPath:frontResolutions:frontResolution:backResolutions:backResolution:mode:)","abstract":[{"text":"Instantiates a new ","type":"text"},{"code":"TruvideoSdkCameraConfiguration","type":"codeVoice"},{"text":" using static method syntax.","type":"text"}],"title":"instantiate(with:flashMode:orientation:outputPath:frontResolutions:frontResolution:backResolutions:backResolution:mode:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"instantiate","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TruvideoSdkCameraLensFacing","preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraLensFacing"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"flashMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TruvideoSdkCameraFlashMode","preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraFlashMode"},{"kind":"text","text":", "},{"kind":"externalParam","text":"orientation"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraOrientation","text":"TruvideoSdkCameraOrientation","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"outputPath","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"frontResolutions","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraResolution","text":"TruvideoSdkCameraResolution","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"frontResolution","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraResolution","text":"TruvideoSdkCameraResolution"},{"text":"?, ","kind":"text"},{"text":"backResolutions","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"TruvideoSdkCameraResolution","kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraResolution"},{"kind":"text","text":"], "},{"text":"backResolution","kind":"externalParam"},{"kind":"text","text":": "},{"text":"TruvideoSdkCameraResolution","kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraResolution"},{"text":"?, ","kind":"text"},{"text":"mode","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraMediaMode","text":"TruvideoSdkCameraMediaMode","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraConfiguration","text":"TruvideoSdkCameraConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"instantiateWith:flashMode:orientation:outputPath:frontResolutions:frontResolution:backResolutions:backResolution:mode:"}],"kind":"symbol","role":"symbol"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraOrientation":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"TruvideoSdkCameraOrientation","kind":"identifier"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraOrientation","role":"symbol","type":"topic","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraorientation","title":"TruvideoSdkCameraOrientation","abstract":[{"type":"text","text":"Defines the camera orientation for media capture."}],"kind":"symbol","navigatorTitle":[{"text":"TruvideoSdkCameraOrientation","kind":"identifier"}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraLensFacing":{"type":"topic","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraLensFacing","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"TruvideoSdkCameraLensFacing","kind":"identifier"}],"abstract":[{"type":"text","text":"Defines the camera lens direction used for capturing media."}],"kind":"symbol","title":"TruvideoSdkCameraLensFacing","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameralensfacing","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TruvideoSdkCameraLensFacing"}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraResolution":{"role":"symbol","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraresolution","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraResolution","title":"TruvideoSdkCameraResolution","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TruvideoSdkCameraResolution"}],"abstract":[],"navigatorTitle":[{"text":"TruvideoSdkCameraResolution","kind":"identifier"}],"type":"topic"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraConfiguration":{"navigatorTitle":[{"kind":"identifier","text":"TruvideoSdkCameraConfiguration"}],"kind":"symbol","title":"TruvideoSdkCameraConfiguration","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TruvideoSdkCameraConfiguration","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraconfiguration","abstract":[{"type":"text","text":"A configuration object for setting up the camera in "},{"code":"TruvideoSdkCamera","type":"codeVoice"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraConfiguration"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraMediaMode":{"type":"topic","title":"TruvideoSdkCameraMediaMode","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TruvideoSdkCameraMediaMode"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraMediaMode","role":"symbol","navigatorTitle":[{"text":"TruvideoSdkCameraMediaMode","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameramediamode"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraFlashMode":{"title":"TruvideoSdkCameraFlashMode","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraFlashMode","kind":"symbol","abstract":[{"type":"text","text":"Defines the flash mode settings for the camera."}],"role":"symbol","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraflashmode","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TruvideoSdkCameraFlashMode"}],"navigatorTitle":[{"kind":"identifier","text":"TruvideoSdkCameraFlashMode"}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"kind":"symbol","url":"\/documentation\/truvideosdkcamera","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","type":"topic","abstract":[{"text":"Store and capture photos and videos using a fully integrated camera system.","type":"text"}],"title":"TruvideoSdkCamera","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"value":"instantiateWith:flashMode:orientation:outputPath:frontResolutions:frontResolution:backResolutions:backResolution:mode:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"instantiateWith:flashMode:orientation:outputPath:frontResolutions:frontResolution:backResolutions:backResolution:mode:","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraConfiguration","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraConfiguration","text":"TruvideoSdkCameraConfiguration"},{"text":" *) ","kind":"text"},{"text":"instantiateWith:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraLensFacing","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraLensFacing","text":"TruvideoSdkCameraLensFacing","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"lensFacing","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"flashMode:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"TruvideoSdkCameraFlashMode","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraFlashMode","preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraFlashMode","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"flashMode","kind":"internalParam"},{"kind":"text","text":" "},{"text":"orientation:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"TruvideoSdkCameraOrientation","kind":"typeIdentifier","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraOrientation","preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraOrientation"},{"kind":"text","text":") "},{"kind":"internalParam","text":"orientation"},{"kind":"text","text":" "},{"text":"outputPath:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"text":"outputPath","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"frontResolutions:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<TruvideoSdkCameraResolution *>"},{"kind":"text","text":" *) "},{"text":"frontResolutions","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"frontResolution:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraResolution","kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraResolution","text":"TruvideoSdkCameraResolution"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"frontResolution"},{"text":" ","kind":"text"},{"kind":"identifier","text":"backResolutions:"},{"text":"(","kind":"text"},{"text":"NSArray<TruvideoSdkCameraResolution *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"text":"backResolutions","kind":"internalParam"},{"kind":"text","text":" "},{"text":"backResolution:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraResolution","text":"TruvideoSdkCameraResolution","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraResolution","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"backResolution"},{"text":" ","kind":"text"},{"text":"mode:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraMediaMode","kind":"typeIdentifier","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraMediaMode","text":"TruvideoSdkCameraMediaMode"},{"text":" *) ","kind":"text"},{"text":"mode","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"instantiateWith:flashMode:orientation:outputPath:frontResolutions:frontResolution:backResolutions:backResolution:mode:","op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraConfiguration~1instantiate(with:flashMode:orientation:outputPath:frontResolutions:frontResolution:backResolutions:backResolution:mode:)\/title"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"text":"instantiateWith:flashMode:orientation:outputPath:frontResolutions:frontResolution:backResolutions:backResolution:mode:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraConfiguration~1instantiate(with:flashMode:orientation:outputPath:frontResolutions:frontResolution:backResolutions:backResolution:mode:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraOrientation\/title","value":"TruvideoSdkCameraOrientation"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraOrientation\/fragments","op":"replace","value":[{"text":"TruvideoSdkCameraOrientation","kind":"identifier"}]},{"value":"TruvideoSdkCameraLensFacing","op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraLensFacing\/title"},{"op":"replace","value":[{"kind":"identifier","text":"TruvideoSdkCameraLensFacing"}],"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraLensFacing\/fragments"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraResolution\/title","op":"replace","value":"TruvideoSdkCameraResolution"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraResolution\/fragments","value":[{"kind":"identifier","text":"TruvideoSdkCameraResolution"}],"op":"replace"},{"value":"TruvideoSdkCameraConfiguration","op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraConfiguration\/title"},{"value":[{"text":"TruvideoSdkCameraConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraConfiguration\/fragments"},{"value":"TruvideoSdkCameraMediaMode","op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraMediaMode\/title"},{"value":[{"text":"TruvideoSdkCameraMediaMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraMediaMode\/fragments"},{"value":"TruvideoSdkCameraFlashMode","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraFlashMode\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraFlashMode\/fragments","op":"replace","value":[{"text":"TruvideoSdkCameraFlashMode","kind":"identifier"}]}]}]}