{"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","metadata":{"symbolKind":"property","externalID":"c:@SA@SharedUniforms@FI@projectionMatrix","navigatorTitle":[{"kind":"identifier","text":"projectionMatrix"}],"roleHeading":"Instance Property","title":"projectionMatrix","role":"symbol","modules":[{"name":"TruvideoSdkCamera"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"projectionMatrix"},{"kind":"text","text":": "},{"text":"matrix_float4x4","kind":"typeIdentifier","preciseIdentifier":"c:@T@matrix_float4x4"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"projectionMatrix","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@matrix_float4x4","text":"matrix_float4x4"}],"languages":["swift"]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/SharedUniforms"]]},"identifier":{"url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/SharedUniforms\/projectionMatrix","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/truvideosdkcamera\/shareduniforms\/projectionmatrix"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/truvideosdkcamera\/shareduniforms\/projectionmatrix"]}],"references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/SharedUniforms/projectionMatrix":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"projectionMatrix"}],"url":"\/documentation\/truvideosdkcamera\/shareduniforms\/projectionmatrix","title":"projectionMatrix","role":"symbol","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/SharedUniforms\/projectionMatrix","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"projectionMatrix","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@matrix_float4x4","kind":"typeIdentifier","text":"matrix_float4x4"}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/SharedUniforms":{"type":"topic","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/SharedUniforms","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"SharedUniforms","kind":"identifier"}],"abstract":[],"url":"\/documentation\/truvideosdkcamera\/shareduniforms","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SharedUniforms"}],"title":"SharedUniforms"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"kind":"symbol","url":"\/documentation\/truvideosdkcamera","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","type":"topic","abstract":[{"text":"Store and capture photos and videos using a fully integrated camera system.","type":"text"}],"title":"TruvideoSdkCamera","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"projectionMatrix"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"projectionMatrix"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"matrix_float4x4","kind":"typeIdentifier","preciseIdentifier":"c:@T@matrix_float4x4"},{"kind":"text","text":" "},{"kind":"identifier","text":"projectionMatrix"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1SharedUniforms~1projectionMatrix\/title","op":"replace","value":"projectionMatrix"},{"value":[{"kind":"identifier","text":"projectionMatrix"}],"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1SharedUniforms~1projectionMatrix\/fragments"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1SharedUniforms\/title","value":"SharedUniforms","op":"replace"}]}]}