{"kind":"symbol","metadata":{"role":"symbol","roleHeading":"Instance Method","title":"application(_:supportedInterfaceOrientationsFor:)","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"application:supportedInterfaceOrientationsForWindow:"}],"required":true,"externalID":"c:@M@TruvideoSdkCamera@objc(pl)TruvideoSdkCameraAppDelegate(im)application:supportedInterfaceOrientationsForWindow:","modules":[{"name":"TruvideoSdkCamera"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"application","kind":"identifier"},{"kind":"text","text":"("},{"text":"UIApplication","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIApplication"},{"text":", ","kind":"text"},{"text":"supportedInterfaceOrientationsFor","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIWindow","preciseIdentifier":"c:objc(cs)UIWindow"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"c:@E@UIInterfaceOrientationMask","text":"UIInterfaceOrientationMask","kind":"typeIdentifier"}]},"identifier":{"url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraAppDelegate\/application(_:supportedInterfaceOrientationsFor:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraAppDelegate"]]},"abstract":[{"type":"text","text":"Determines the supported interface orientations for the application."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"application","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"application"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIApplication","text":"UIApplication","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"supportedInterfaceOrientationsFor","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"window"},{"text":": ","kind":"text"},{"text":"UIWindow","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIWindow"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"c:@E@UIInterfaceOrientationMask","kind":"typeIdentifier","text":"UIInterfaceOrientationMask"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"application","content":[{"inlineContent":[{"type":"text","text":"The running application instance."}],"type":"paragraph"}]},{"name":"window","content":[{"inlineContent":[{"text":"The main application window.","type":"text"}],"type":"paragraph"}]}]},{"kind":"content","content":[{"anchor":"return-value","text":"Return Value","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"text":"A ","type":"text"},{"code":"UIInterfaceOrientationMask","type":"codeVoice"},{"text":" specifying the supported orientations.","type":"text"}]}]},{"content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"This method allows the app to specify ","type":"text"},{"inlineContent":[{"type":"text","text":"which orientations"}],"type":"strong"},{"type":"text","text":" are permitted for a given window."}]}],"kind":"content"}],"variants":[{"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcameraappdelegate\/application(_:supportedinterfaceorientationsfor:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcameraappdelegate\/application(_:supportedinterfaceorientationsfor:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"kind":"symbol","abstract":[{"type":"text","text":"Store and capture photos and videos using a fully integrated camera system."}],"url":"\/documentation\/truvideosdkcamera","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","title":"TruvideoSdkCamera","type":"topic","role":"collection"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraAppDelegate/application(_:supportedInterfaceOrientationsFor:)":{"required":true,"kind":"symbol","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraAppDelegate\/application(_:supportedInterfaceOrientationsFor:)","navigatorTitle":[{"kind":"identifier","text":"application:supportedInterfaceOrientationsForWindow:"}],"abstract":[{"type":"text","text":"Determines the supported interface orientations for the application."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"application","kind":"identifier"},{"kind":"text","text":"("},{"text":"UIApplication","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":", "},{"kind":"externalParam","text":"supportedInterfaceOrientationsFor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIWindow","preciseIdentifier":"c:objc(cs)UIWindow"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"UIInterfaceOrientationMask","preciseIdentifier":"c:@E@UIInterfaceOrientationMask"}],"type":"topic","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraappdelegate\/application(_:supportedinterfaceorientationsfor:)","role":"symbol","title":"application(_:supportedInterfaceOrientationsFor:)"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraAppDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"TruvideoSdkCameraAppDelegate","kind":"identifier"}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraappdelegate","title":"TruvideoSdkCameraAppDelegate","abstract":[{"type":"text","text":"Defines the application delegate for handling camera-related configurations."}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraAppDelegate","navigatorTitle":[{"text":"TruvideoSdkCameraAppDelegate","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"application:supportedInterfaceOrientationsForWindow:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"text":"application:supportedInterfaceOrientationsForWindow:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"UIInterfaceOrientationMask","preciseIdentifier":"c:@E@UIInterfaceOrientationMask"},{"text":") ","kind":"text"},{"kind":"identifier","text":"application:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIApplication","text":"UIApplication","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"application","kind":"internalParam"},{"kind":"text","text":" "},{"text":"supportedInterfaceOrientationsForWindow:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIWindow","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIWindow"},{"kind":"text","text":" *) "},{"text":"window","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraAppDelegate~1application(_:supportedInterfaceOrientationsFor:)\/title","value":"application:supportedInterfaceOrientationsForWindow:"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraAppDelegate~1application(_:supportedInterfaceOrientationsFor:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"application:supportedInterfaceOrientationsForWindow:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraAppDelegate\/title","value":"TruvideoSdkCameraAppDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraAppDelegate\/fragments","value":[{"text":"TruvideoSdkCameraAppDelegate","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}