{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"orientationLock"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UIInterfaceOrientationMask","text":"UIInterfaceOrientationMask"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}]}]}],"sections":[],"metadata":{"required":true,"title":"orientationLock","modules":[{"name":"TruvideoSdkCamera"}],"roleHeading":"Instance Property","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"orientationLock"},{"text":": ","kind":"text"},{"text":"UIInterfaceOrientationMask","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIInterfaceOrientationMask"}],"externalID":"c:@M@TruvideoSdkCamera@objc(pl)TruvideoSdkCameraAppDelegate(py)orientationLock","symbolKind":"property","navigatorTitle":[{"text":"orientationLock","kind":"identifier"}]},"abstract":[{"text":"The current orientation lock for the application.","type":"text"}],"variants":[{"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcameraappdelegate\/orientationlock"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcameraappdelegate\/orientationlock"]}],"hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraAppDelegate"]]},"identifier":{"url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraAppDelegate\/orientationLock","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraAppDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"TruvideoSdkCameraAppDelegate","kind":"identifier"}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraappdelegate","title":"TruvideoSdkCameraAppDelegate","abstract":[{"type":"text","text":"Defines the application delegate for handling camera-related configurations."}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraAppDelegate","navigatorTitle":[{"text":"TruvideoSdkCameraAppDelegate","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"kind":"symbol","abstract":[{"type":"text","text":"Store and capture photos and videos using a fully integrated camera system."}],"url":"\/documentation\/truvideosdkcamera","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","title":"TruvideoSdkCamera","type":"topic","role":"collection"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraAppDelegate/orientationLock":{"abstract":[{"type":"text","text":"The current orientation lock for the application."}],"title":"orientationLock","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraappdelegate\/orientationlock","required":true,"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"orientationLock","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIInterfaceOrientationMask","preciseIdentifier":"c:@E@UIInterfaceOrientationMask"}],"type":"topic","navigatorTitle":[{"text":"orientationLock","kind":"identifier"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraAppDelegate\/orientationLock"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"orientationLock"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"kind":"identifier","text":"orientationLock"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@E@UIInterfaceOrientationMask","kind":"typeIdentifier","text":"UIInterfaceOrientationMask"},{"text":" ","kind":"text"},{"kind":"identifier","text":"orientationLock"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"TruvideoSdkCameraAppDelegate","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraAppDelegate\/title","op":"replace"},{"value":[{"text":"TruvideoSdkCameraAppDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraAppDelegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraAppDelegate~1orientationLock\/title","value":"orientationLock"},{"value":[{"text":"orientationLock","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraAppDelegate~1orientationLock\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}