{"metadata":{"roleHeading":"Case","title":"TruvideoSdkCameraFlashMode.on","externalID":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraFlashMode@TruvideoSdkCameraFlashModeOn","modules":[{"name":"TruvideoSdkCamera"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"on","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"TruvideoSdkCameraFlashModeOn"}],"role":"symbol","symbolKind":"case"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraFlashMode\/on"},"abstract":[{"text":"Flash is always enabled.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"on"}],"platforms":["iOS"]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraFlashMode"]]},"variants":[{"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcameraflashmode\/on"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcameraflashmode\/on"]}],"references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"kind":"symbol","url":"\/documentation\/truvideosdkcamera","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","type":"topic","abstract":[{"text":"Store and capture photos and videos using a fully integrated camera system.","type":"text"}],"title":"TruvideoSdkCamera","role":"collection"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraFlashMode/on":{"kind":"symbol","title":"TruvideoSdkCameraFlashMode.on","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"on"}],"abstract":[{"type":"text","text":"Flash is always enabled."}],"navigatorTitle":[{"kind":"identifier","text":"TruvideoSdkCameraFlashModeOn"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraFlashMode\/on","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraflashmode\/on"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraFlashMode":{"title":"TruvideoSdkCameraFlashMode","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraFlashMode","kind":"symbol","abstract":[{"type":"text","text":"Defines the flash mode settings for the camera."}],"role":"symbol","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraflashmode","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TruvideoSdkCameraFlashMode"}],"navigatorTitle":[{"kind":"identifier","text":"TruvideoSdkCameraFlashMode"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"TruvideoSdkCameraFlashModeOn"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"TruvideoSdkCameraFlashModeOn"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"TruvideoSdkCameraFlashModeOn"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraFlashMode~1on\/title","value":"TruvideoSdkCameraFlashModeOn"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraFlashMode~1on\/fragments","value":[{"kind":"identifier","text":"TruvideoSdkCameraFlashModeOn"}]},{"value":"TruvideoSdkCameraFlashMode","op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraFlashMode\/title"},{"value":[{"text":"TruvideoSdkCameraFlashMode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraFlashMode\/fragments","op":"replace"}]}]}