{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraLensFacing\/front"},"hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraLensFacing"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Uses the front-facing camera (selfie mode)."}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcameralensfacing\/front"]},{"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcameralensfacing\/front"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"front","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","metadata":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"front"}],"title":"TruvideoSdkCameraLensFacing.front","role":"symbol","symbolKind":"case","externalID":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraLensFacing@TruvideoSdkCameraLensFacingFront","navigatorTitle":[{"kind":"identifier","text":"TruvideoSdkCameraLensFacingFront"}],"roleHeading":"Case","modules":[{"name":"TruvideoSdkCamera"}]},"references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraLensFacing/front":{"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameralensfacing\/front","navigatorTitle":[{"text":"TruvideoSdkCameraLensFacingFront","kind":"identifier"}],"abstract":[{"text":"Uses the front-facing camera (selfie mode).","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"front","kind":"identifier"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraLensFacing\/front","role":"symbol","kind":"symbol","title":"TruvideoSdkCameraLensFacing.front","type":"topic"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","title":"TruvideoSdkCamera","role":"collection","type":"topic","url":"\/documentation\/truvideosdkcamera","kind":"symbol","abstract":[{"text":"Store and capture photos and videos using a fully integrated camera system.","type":"text"}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraLensFacing":{"type":"topic","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraLensFacing","title":"TruvideoSdkCameraLensFacing","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TruvideoSdkCameraLensFacing"}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameralensfacing","navigatorTitle":[{"text":"TruvideoSdkCameraLensFacing","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Defines the camera lens direction used for capturing media.","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"TruvideoSdkCameraLensFacingFront","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"TruvideoSdkCameraLensFacingFront","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"TruvideoSdkCameraLensFacingFront","kind":"identifier"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraLensFacing~1front\/title","op":"replace","value":"TruvideoSdkCameraLensFacingFront"},{"op":"replace","value":[{"text":"TruvideoSdkCameraLensFacingFront","kind":"identifier"}],"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraLensFacing~1front\/fragments"},{"op":"replace","value":"TruvideoSdkCameraLensFacing","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraLensFacing\/title"},{"value":[{"kind":"identifier","text":"TruvideoSdkCameraLensFacing"}],"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraLensFacing\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}