{"variants":[{"paths":["\/documentation\/truvideosdkcamera\/shareduniforms\/directionallightcolor"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/truvideosdkcamera\/shareduniforms\/directionallightcolor"]}],"kind":"symbol","metadata":{"roleHeading":"Instance Property","externalID":"c:@SA@SharedUniforms@FI@directionalLightColor","title":"directionalLightColor","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"directionalLightColor"}],"modules":[{"name":"TruvideoSdkCamera"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"directionalLightColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@vector_float3","text":"vector_float3"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/SharedUniforms\/directionalLightColor"},"hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/SharedUniforms"]]},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"directionalLightColor","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@vector_float3","kind":"typeIdentifier","text":"vector_float3"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","title":"TruvideoSdkCamera","role":"collection","type":"topic","url":"\/documentation\/truvideosdkcamera","kind":"symbol","abstract":[{"text":"Store and capture photos and videos using a fully integrated camera system.","type":"text"}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/SharedUniforms":{"url":"\/documentation\/truvideosdkcamera\/shareduniforms","kind":"symbol","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/SharedUniforms","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"SharedUniforms","kind":"identifier"}],"title":"SharedUniforms","navigatorTitle":[{"text":"SharedUniforms","kind":"identifier"}],"role":"symbol"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/SharedUniforms/directionalLightColor":{"url":"\/documentation\/truvideosdkcamera\/shareduniforms\/directionallightcolor","kind":"symbol","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/SharedUniforms\/directionalLightColor","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"directionalLightColor"},{"text":": ","kind":"text"},{"text":"vector_float3","kind":"typeIdentifier","preciseIdentifier":"c:@T@vector_float3"}],"title":"directionalLightColor","navigatorTitle":[{"text":"directionalLightColor","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"directionalLightColor"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"directionalLightColor","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"typeIdentifier","text":"vector_float3","preciseIdentifier":"c:@T@vector_float3"},{"kind":"text","text":" "},{"kind":"identifier","text":"directionalLightColor"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1SharedUniforms\/title","value":"SharedUniforms","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1SharedUniforms~1directionalLightColor\/title","value":"directionalLightColor"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1SharedUniforms~1directionalLightColor\/fragments","value":[{"text":"directionalLightColor","kind":"identifier"}]}]}]}