{"abstract":[{"type":"text","text":"Creates a new instance of "},{"type":"codeVoice","code":"TruvideoSdkARCameraConfiguration"},{"text":" with customizable settings.","type":"text"}],"metadata":{"roleHeading":"Initializer","externalID":"s:17TruvideoSdkCamera0aB21ARCameraConfigurationC9flashMode4mode11orientationAcA0abc5FlashG0O_AA0abc5MediaG0CAA0abC11OrientationOSgtcfc","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"flashMode","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraFlashMode","text":"TruvideoSdkCameraFlashMode","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mode"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraMediaMode","text":"TruvideoSdkCameraMediaMode","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"orientation"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraOrientation","text":"TruvideoSdkCameraOrientation"},{"kind":"text","text":"?)"}],"symbolKind":"init","modules":[{"name":"TruvideoSdkCamera"}],"title":"init(flashMode:mode:orientation:)","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkARCameraConfiguration"]]},"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"flashMode"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraFlashMode","kind":"typeIdentifier","text":"TruvideoSdkCameraFlashMode","preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraFlashMode"},{"text":" = .off, ","kind":"text"},{"text":"mode","kind":"externalParam"},{"kind":"text","text":": "},{"text":"TruvideoSdkCameraMediaMode","kind":"typeIdentifier","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraMediaMode","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraMediaMode"},{"text":" = .videoAndPicture(), ","kind":"text"},{"text":"orientation","kind":"externalParam"},{"kind":"text","text":": "},{"text":"TruvideoSdkCameraOrientation","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraOrientation","kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraOrientation"},{"text":"? = nil)","kind":"text"}],"platforms":["iOS"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The desired flash setting (default: "},{"type":"codeVoice","code":".off"},{"type":"text","text":")."}]}],"name":"flashMode"},{"content":[{"inlineContent":[{"type":"text","text":"The media capture mode (default: "},{"code":".videoAndPicture()","type":"codeVoice"},{"type":"text","text":")."}],"type":"paragraph"}],"name":"mode"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The camera’s orientation (default: device’s current orientation)."}]}],"name":"orientation"}],"kind":"parameters"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/truvideosdkcamera\/truvideosdkarcameraconfiguration\/init(flashmode:mode:orientation:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkARCameraConfiguration\/init(flashMode:mode:orientation:)","interfaceLanguage":"swift"},"references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraFlashMode":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TruvideoSdkCameraFlashMode"}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraflashmode","title":"TruvideoSdkCameraFlashMode","abstract":[{"type":"text","text":"Defines the flash mode settings for the camera."}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraFlashMode","navigatorTitle":[{"text":"TruvideoSdkCameraFlashMode","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraMediaMode":{"title":"TruvideoSdkCameraMediaMode","role":"symbol","abstract":[],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TruvideoSdkCameraMediaMode"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraMediaMode","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameramediamode","navigatorTitle":[{"text":"TruvideoSdkCameraMediaMode","kind":"identifier"}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"kind":"symbol","abstract":[{"type":"text","text":"Store and capture photos and videos using a fully integrated camera system."}],"url":"\/documentation\/truvideosdkcamera","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","title":"TruvideoSdkCamera","type":"topic","role":"collection"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraOrientation":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"TruvideoSdkCameraOrientation","kind":"identifier"}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraorientation","title":"TruvideoSdkCameraOrientation","abstract":[{"type":"text","text":"Defines the camera orientation for media capture."}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraOrientation","navigatorTitle":[{"kind":"identifier","text":"TruvideoSdkCameraOrientation"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkARCameraConfiguration/init(flashMode:mode:orientation:)":{"abstract":[{"text":"Creates a new instance of ","type":"text"},{"code":"TruvideoSdkARCameraConfiguration","type":"codeVoice"},{"text":" with customizable settings.","type":"text"}],"title":"init(flashMode:mode:orientation:)","url":"\/documentation\/truvideosdkcamera\/truvideosdkarcameraconfiguration\/init(flashmode:mode:orientation:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"flashMode","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraFlashMode","text":"TruvideoSdkCameraFlashMode","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"mode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraMediaMode","text":"TruvideoSdkCameraMediaMode"},{"kind":"text","text":", "},{"text":"orientation","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TruvideoSdkCameraOrientation","preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraOrientation"},{"kind":"text","text":"?)"}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkARCameraConfiguration\/init(flashMode:mode:orientation:)"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkARCameraConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TruvideoSdkARCameraConfiguration"}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkarcameraconfiguration","title":"TruvideoSdkARCameraConfiguration","abstract":[{"type":"text","text":"A configuration object for setting up the AR Camera in "},{"code":"TruvideoSdkCamera","type":"codeVoice"},{"text":".","type":"text"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkARCameraConfiguration","navigatorTitle":[{"text":"TruvideoSdkARCameraConfiguration","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"TruvideoSdkCameraFlashMode","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraFlashMode\/title","op":"replace"},{"value":[{"kind":"identifier","text":"TruvideoSdkCameraFlashMode"}],"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraFlashMode\/fragments"},{"op":"replace","value":"TruvideoSdkCameraMediaMode","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraMediaMode\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraMediaMode\/fragments","value":[{"text":"TruvideoSdkCameraMediaMode","kind":"identifier"}]},{"op":"replace","value":"TruvideoSdkCameraOrientation","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraOrientation\/title"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraOrientation\/fragments","op":"replace","value":[{"text":"TruvideoSdkCameraOrientation","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkARCameraConfiguration\/title","value":"TruvideoSdkARCameraConfiguration"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkARCameraConfiguration\/fragments","value":[{"kind":"identifier","text":"TruvideoSdkARCameraConfiguration"}],"op":"replace"}]}]}