{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/truvideosdkcamera\/truvideosdkscannercameraconfiguration\/orientation"]},{"paths":["\/documentation\/truvideosdkcamera\/truvideosdkscannercameraconfiguration\/orientation"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Defines the ","type":"text"},{"inlineContent":[{"type":"text","text":"camera orientation"}],"type":"strong"},{"type":"text","text":" during scanning."}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkScannerCameraConfiguration"]]},"identifier":{"url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkScannerCameraConfiguration\/orientation","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"orientation","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TruvideoSdkCameraOrientation","kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraOrientation"}],"title":"orientation","externalID":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkScannerCameraConfiguration(py)orientation","navigatorTitle":[{"text":"orientation","kind":"identifier"}],"modules":[{"name":"TruvideoSdkCamera"}],"symbolKind":"property","role":"symbol","roleHeading":"Instance Property"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"orientation"},{"kind":"text","text":": "},{"text":"TruvideoSdkCameraOrientation","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraOrientation","kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraOrientation"}]}],"kind":"declarations"}],"references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkScannerCameraConfiguration/orientation":{"abstract":[{"text":"Defines the ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"camera orientation"}]},{"type":"text","text":" during scanning."}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkscannercameraconfiguration\/orientation","type":"topic","kind":"symbol","role":"symbol","title":"orientation","navigatorTitle":[{"text":"orientation","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"orientation","kind":"identifier"},{"kind":"text","text":": "},{"text":"TruvideoSdkCameraOrientation","kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraOrientation"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkScannerCameraConfiguration\/orientation"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"kind":"symbol","abstract":[{"type":"text","text":"Store and capture photos and videos using a fully integrated camera system."}],"url":"\/documentation\/truvideosdkcamera","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","title":"TruvideoSdkCamera","type":"topic","role":"collection"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkScannerCameraConfiguration":{"title":"TruvideoSdkScannerCameraConfiguration","role":"symbol","abstract":[{"text":"Configuration settings for the ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"Truvideo Scanner Camera"}]},{"type":"text","text":"."}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TruvideoSdkScannerCameraConfiguration"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkScannerCameraConfiguration","url":"\/documentation\/truvideosdkcamera\/truvideosdkscannercameraconfiguration","navigatorTitle":[{"text":"TruvideoSdkScannerCameraConfiguration","kind":"identifier"}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraOrientation":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"TruvideoSdkCameraOrientation","kind":"identifier"}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraorientation","title":"TruvideoSdkCameraOrientation","abstract":[{"type":"text","text":"Defines the camera orientation for media capture."}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraOrientation","navigatorTitle":[{"kind":"identifier","text":"TruvideoSdkCameraOrientation"}],"kind":"symbol","role":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"orientation","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"orientation","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraOrientation","preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraOrientation","kind":"typeIdentifier","text":"TruvideoSdkCameraOrientation"},{"kind":"text","text":" "},{"text":"orientation","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"value":"orientation","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkScannerCameraConfiguration~1orientation\/title","op":"replace"},{"value":[{"kind":"identifier","text":"orientation"}],"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkScannerCameraConfiguration~1orientation\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkScannerCameraConfiguration\/title","value":"TruvideoSdkScannerCameraConfiguration"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkScannerCameraConfiguration\/fragments","value":[{"text":"TruvideoSdkScannerCameraConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraOrientation\/title","op":"replace","value":"TruvideoSdkCameraOrientation"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraOrientation\/fragments","op":"replace","value":[{"text":"TruvideoSdkCameraOrientation","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}