{"hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/UIKit","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/UIKit\/UIViewController"]]},"abstract":[{"type":"text","text":"Presents the Standard Camera view in full-screen mode."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/truvideosdkcamera\/uikit\/uiviewcontroller\/presenttruvideosdkcameraview(preset:oncomplete:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/UIKit\/UIViewController\/presentTruvideoSdkCameraView(preset:onComplete:)"},"sections":[],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"title":"presentTruvideoSdkCameraView(preset:onComplete:)","modules":[{"relatedModules":["UIKit"],"name":"TruvideoSdkCamera"}],"roleHeading":"Instance Method","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"presentTruvideoSdkCameraView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"preset","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraConfiguration","kind":"typeIdentifier","text":"TruvideoSdkCameraConfiguration"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"onComplete"},{"text":": (","kind":"text"},{"text":"TruvideoSdkCameraResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraResult"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"extendedModule":"UIKit","externalID":"c:@CM@TruvideoSdkCamera@@objc(cs)UIViewController(im)presentTruvideoSdkCameraViewWithPreset:onComplete:","symbolKind":"method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"presentTruvideoSdkCameraView"},{"text":"(","kind":"text"},{"text":"preset","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TruvideoSdkCameraConfiguration","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraConfiguration"},{"kind":"text","text":" = .init(\n            lensFacing: .back,\n            flashMode: .off,\n            orientation: nil,\n            outputPath: \"\",\n            frontResolutions: [],\n            frontResolution: nil,\n            backResolutions: [],\n            backResolution: nil,\n            mode: .videoAndPicture()\n        ), "},{"text":"onComplete","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraResult","text":"TruvideoSdkCameraResult","kind":"typeIdentifier","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraResult"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"preset","content":[{"type":"paragraph","inlineContent":[{"text":"A ","type":"text"},{"type":"codeVoice","code":"TruvideoSdkCameraConfiguration"},{"text":" object that defines the configuration for the camera.","type":"text"}]}]},{"name":"onComplete","content":[{"inlineContent":[{"type":"text","text":"A callback function that receives a "},{"type":"codeVoice","code":"TruvideoSdkCameraResult"},{"type":"text","text":" containing captured media."}],"type":"paragraph"}]}]},{"kind":"content","content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This method displays the "},{"type":"strong","inlineContent":[{"type":"text","text":"TruvideoSdkCamera"}]},{"type":"text","text":", allowing users to "},{"type":"strong","inlineContent":[{"text":"capture photos and record videos","type":"text"}]},{"text":" based on the provided","type":"text"},{"type":"text","text":" "},{"text":"camera configuration.","type":"text"}]}]}],"references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraConfiguration":{"title":"TruvideoSdkCameraConfiguration","role":"symbol","abstract":[{"type":"text","text":"A configuration object for setting up the camera in "},{"code":"TruvideoSdkCamera","type":"codeVoice"},{"text":".","type":"text"}],"type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TruvideoSdkCameraConfiguration","kind":"identifier"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraConfiguration","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraconfiguration","navigatorTitle":[{"kind":"identifier","text":"TruvideoSdkCameraConfiguration"}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/UIKit/UIViewController/presentTruvideoSdkCameraView(preset:onComplete:)":{"abstract":[{"text":"Presents the Standard Camera view in full-screen mode.","type":"text"}],"title":"presentTruvideoSdkCameraView(preset:onComplete:)","url":"\/documentation\/truvideosdkcamera\/uikit\/uiviewcontroller\/presenttruvideosdkcameraview(preset:oncomplete:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"presentTruvideoSdkCameraView","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"preset"},{"text":": ","kind":"text"},{"text":"TruvideoSdkCameraConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onComplete"},{"kind":"text","text":": ("},{"text":"TruvideoSdkCameraResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraResult"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")"}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/UIKit\/UIViewController\/presentTruvideoSdkCameraView(preset:onComplete:)"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"kind":"symbol","abstract":[{"type":"text","text":"Store and capture photos and videos using a fully integrated camera system."}],"url":"\/documentation\/truvideosdkcamera","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","title":"TruvideoSdkCamera","type":"topic","role":"collection"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/UIKit":{"url":"\/documentation\/truvideosdkcamera\/uikit","title":"UIKit","abstract":[],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/UIKit","kind":"symbol","role":"collection","type":"topic"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/UIKit/UIViewController":{"abstract":[],"title":"UIViewController","url":"\/documentation\/truvideosdkcamera\/uikit\/uiviewcontroller","fragments":[{"kind":"keyword","text":"extension"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"text":"UIViewController","kind":"identifier"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/UIKit\/UIViewController"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraResult":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TruvideoSdkCameraResult"}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraresult","title":"TruvideoSdkCameraResult","abstract":[{"type":"text","text":"A result of the recording session."}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraResult","navigatorTitle":[{"kind":"identifier","text":"TruvideoSdkCameraResult"}],"kind":"symbol","role":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"value":"TruvideoSdkCameraConfiguration","op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"TruvideoSdkCameraConfiguration"}],"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraConfiguration\/fragments"},{"op":"replace","value":"TruvideoSdkCameraResult","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraResult\/title"},{"value":[{"text":"TruvideoSdkCameraResult","kind":"identifier"}],"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraResult\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}