{"abstract":[{"type":"text","text":"The output file path where the recorded media will be saved."}],"metadata":{"roleHeading":"Instance Property","role":"symbol","title":"outputPath","modules":[{"name":"TruvideoSdkCamera"}],"externalID":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraConfiguration(py)outputPath","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"outputPath","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"outputPath"}]},"hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraConfiguration"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"outputPath"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"anchor":"discussion","text":"Discussion","type":"heading"},{"inlineContent":[{"type":"text","text":"Defines the storage location of the "},{"type":"strong","inlineContent":[{"type":"text","text":"captured photos or recorded videos"}]},{"type":"text","text":"."}],"type":"paragraph"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcameraconfiguration\/outputpath"]},{"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcameraconfiguration\/outputpath"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraConfiguration\/outputPath"},"sections":[],"references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraConfiguration":{"title":"TruvideoSdkCameraConfiguration","role":"symbol","abstract":[{"type":"text","text":"A configuration object for setting up the camera in "},{"code":"TruvideoSdkCamera","type":"codeVoice"},{"text":".","type":"text"}],"type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TruvideoSdkCameraConfiguration","kind":"identifier"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraConfiguration","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraconfiguration","navigatorTitle":[{"kind":"identifier","text":"TruvideoSdkCameraConfiguration"}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraConfiguration/outputPath":{"navigatorTitle":[{"kind":"identifier","text":"outputPath"}],"abstract":[{"type":"text","text":"The output file path where the recorded media will be saved."}],"title":"outputPath","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraConfiguration\/outputPath","type":"topic","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"outputPath","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"kind":"symbol","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraconfiguration\/outputpath"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"kind":"symbol","abstract":[{"type":"text","text":"Store and capture photos and videos using a fully integrated camera system."}],"url":"\/documentation\/truvideosdkcamera","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","title":"TruvideoSdkCamera","type":"topic","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"outputPath"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"outputPath"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"outputPath"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraConfiguration\/title","op":"replace","value":"TruvideoSdkCameraConfiguration"},{"value":[{"kind":"identifier","text":"TruvideoSdkCameraConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraConfiguration\/fragments"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraConfiguration~1outputPath\/title","op":"replace","value":"outputPath"},{"value":[{"text":"outputPath","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraConfiguration~1outputPath\/fragments"}]}]}