{"metadata":{"required":true,"symbolKind":"method","roleHeading":"Instance Method","externalID":"c:@M@TruvideoSdkCamera@objc(pl)TruvideoSdkCameraDelegate(im)getTruvideoSdkCameraInformation","title":"getTruvideoSdkCameraInformation()","navigatorTitle":[{"text":"getTruvideoSdkCameraInformation","kind":"identifier"}],"modules":[{"name":"TruvideoSdkCamera"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"getTruvideoSdkCameraInformation","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraInformation","text":"TruvideoSdkCameraInformation"}]},"hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraDelegate"]]},"kind":"symbol","abstract":[{"text":"Retrieves all available camera information for both ","type":"text"},{"type":"strong","inlineContent":[{"text":"front","type":"text"}]},{"text":" and ","type":"text"},{"inlineContent":[{"text":"back","type":"text"}],"type":"strong"},{"text":" cameras.","type":"text"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getTruvideoSdkCameraInformation"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraInformation","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraInformation","text":"TruvideoSdkCameraInformation"}]}]},{"kind":"content","content":[{"text":"Return Value","type":"heading","level":2,"anchor":"return-value"},{"inlineContent":[{"type":"text","text":"A "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraInformation"},{"type":"text","text":" object containing detailed camera specifications."}],"type":"paragraph"}]}],"variants":[{"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcameradelegate\/gettruvideosdkcamerainformation()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcameradelegate\/gettruvideosdkcamerainformation()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraDelegate\/getTruvideoSdkCameraInformation()","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraDelegate":{"kind":"symbol","abstract":[{"type":"text","text":"Defines the delegate responsible for retrieving camera information."}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameradelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TruvideoSdkCameraDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraDelegate","title":"TruvideoSdkCameraDelegate","type":"topic","navigatorTitle":[{"text":"TruvideoSdkCameraDelegate","kind":"identifier"}],"role":"symbol"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraDelegate/getTruvideoSdkCameraInformation()":{"required":true,"kind":"symbol","abstract":[{"type":"text","text":"Retrieves all available camera information for both "},{"inlineContent":[{"text":"front","type":"text"}],"type":"strong"},{"text":" and ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"back"}]},{"type":"text","text":" cameras."}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameradelegate\/gettruvideosdkcamerainformation()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getTruvideoSdkCameraInformation"},{"kind":"text","text":"() -> "},{"text":"TruvideoSdkCameraInformation","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraInformation","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraDelegate\/getTruvideoSdkCameraInformation()","title":"getTruvideoSdkCameraInformation()","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getTruvideoSdkCameraInformation"}],"role":"symbol"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"kind":"symbol","abstract":[{"type":"text","text":"Store and capture photos and videos using a fully integrated camera system."}],"url":"\/documentation\/truvideosdkcamera","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","title":"TruvideoSdkCamera","type":"topic","role":"collection"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraInformation":{"title":"TruvideoSdkCameraInformation","role":"symbol","abstract":[{"type":"text","text":"Provides detailed information about available camera devices."}],"type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TruvideoSdkCameraInformation","kind":"identifier"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraInformation","url":"\/documentation\/truvideosdkcamera\/truvideosdkcamerainformation","navigatorTitle":[{"kind":"identifier","text":"TruvideoSdkCameraInformation"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"getTruvideoSdkCameraInformation","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getTruvideoSdkCameraInformation"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"TruvideoSdkCameraInformation","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraInformation","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraInformation"},{"kind":"text","text":" *) "},{"text":"getTruvideoSdkCameraInformation","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"value":"TruvideoSdkCameraDelegate","op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraDelegate\/fragments","value":[{"text":"TruvideoSdkCameraDelegate","kind":"identifier"}]},{"value":"getTruvideoSdkCameraInformation","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraDelegate~1getTruvideoSdkCameraInformation()\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraDelegate~1getTruvideoSdkCameraInformation()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"getTruvideoSdkCameraInformation"}],"op":"replace"},{"value":"TruvideoSdkCameraInformation","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraInformation\/title","op":"replace"},{"op":"replace","value":[{"text":"TruvideoSdkCameraInformation","kind":"identifier"}],"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraInformation\/fragments"}]}]}