{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/InstanceUniforms"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"modelMatrix","kind":"identifier"},{"kind":"text","text":": "},{"text":"matrix_float4x4","kind":"typeIdentifier","preciseIdentifier":"c:@T@matrix_float4x4"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/truvideosdkcamera\/instanceuniforms\/modelmatrix"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/truvideosdkcamera\/instanceuniforms\/modelmatrix"]}],"sections":[],"identifier":{"url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/InstanceUniforms\/modelMatrix","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Instance Property","role":"symbol","title":"modelMatrix","externalID":"c:@SA@InstanceUniforms@FI@modelMatrix","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"modelMatrix"}],"modules":[{"name":"TruvideoSdkCamera"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"modelMatrix","kind":"identifier"},{"kind":"text","text":": "},{"text":"matrix_float4x4","kind":"typeIdentifier","preciseIdentifier":"c:@T@matrix_float4x4"}]},"references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/InstanceUniforms/modelMatrix":{"url":"\/documentation\/truvideosdkcamera\/instanceuniforms\/modelmatrix","type":"topic","abstract":[],"role":"symbol","title":"modelMatrix","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/InstanceUniforms\/modelMatrix","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"modelMatrix"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"modelMatrix","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@matrix_float4x4","text":"matrix_float4x4","kind":"typeIdentifier"}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","title":"TruvideoSdkCamera","role":"collection","type":"topic","url":"\/documentation\/truvideosdkcamera","kind":"symbol","abstract":[{"text":"Store and capture photos and videos using a fully integrated camera system.","type":"text"}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/InstanceUniforms":{"title":"InstanceUniforms","type":"topic","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/InstanceUniforms","role":"symbol","abstract":[],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"InstanceUniforms"}],"navigatorTitle":[{"text":"InstanceUniforms","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/truvideosdkcamera\/instanceuniforms"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"modelMatrix","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"kind":"identifier","text":"modelMatrix"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"preciseIdentifier":"c:@T@matrix_float4x4","kind":"typeIdentifier","text":"matrix_float4x4"},{"kind":"text","text":" "},{"text":"modelMatrix","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"modelMatrix","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1InstanceUniforms~1modelMatrix\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1InstanceUniforms~1modelMatrix\/fragments","op":"replace","value":[{"kind":"identifier","text":"modelMatrix"}]},{"op":"replace","value":"InstanceUniforms","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1InstanceUniforms\/title"}]}]}