{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"truvideoSdkCameraEventRecordingPaused","kind":"identifier"},{"text":"(","kind":"text"},{"text":"resolution","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraResolution","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraResolution","kind":"typeIdentifier","text":"TruvideoSdkCameraResolution"},{"text":", ","kind":"text"},{"text":"orientation","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraOrientation","preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraOrientation","kind":"typeIdentifier","text":"TruvideoSdkCameraOrientation"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"lensFacing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraLensFacing","text":"TruvideoSdkCameraLensFacing","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraLensFacing"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The current recording resolution."}]}],"name":"resolution"},{"content":[{"inlineContent":[{"type":"text","text":"The current camera orientation."}],"type":"paragraph"}],"name":"orientation"},{"name":"lensFacing","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The current lens direction."}]}]}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcameraeventtype\/truvideosdkcameraeventrecordingpaused(resolution:orientation:lensfacing:)"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraEventType"]]},"metadata":{"modules":[{"name":"TruvideoSdkCamera"}],"title":"TruvideoSdkCameraEventType.truvideoSdkCameraEventRecordingPaused(resolution:orientation:lensFacing:)","externalID":"s:17TruvideoSdkCamera0abC9EventTypeO08truvideobcD15RecordingPausedyAcA0abC10ResolutionC_AA0abC11OrientationOAA0abC10LensFacingOtcACmF","roleHeading":"Case","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"truvideoSdkCameraEventRecordingPaused"},{"text":"(","kind":"text"},{"text":"resolution","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraResolution","text":"TruvideoSdkCameraResolution","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"orientation","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TruvideoSdkCameraOrientation","preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraOrientation"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"lensFacing"},{"text":": ","kind":"text"},{"text":"TruvideoSdkCameraLensFacing","kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraLensFacing"},{"kind":"text","text":")"}],"symbolKind":"case"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraEventType\/truvideoSdkCameraEventRecordingPaused(resolution:orientation:lensFacing:)"},"abstract":[{"text":"Triggered when ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"video recording is paused"}]},{"type":"text","text":"."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraEventType":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TruvideoSdkCameraEventType"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TruvideoSdkCameraEventType"}],"role":"symbol","type":"topic","title":"TruvideoSdkCameraEventType","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraeventtype","abstract":[{"type":"text","text":"Defines the different types of events emitted by "},{"code":"TruvideoSdkCamera","type":"codeVoice"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraEventType"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"kind":"symbol","url":"\/documentation\/truvideosdkcamera","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","type":"topic","abstract":[{"text":"Store and capture photos and videos using a fully integrated camera system.","type":"text"}],"title":"TruvideoSdkCamera","role":"collection"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraResolution":{"role":"symbol","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraresolution","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraResolution","title":"TruvideoSdkCameraResolution","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TruvideoSdkCameraResolution"}],"abstract":[],"navigatorTitle":[{"text":"TruvideoSdkCameraResolution","kind":"identifier"}],"type":"topic"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraEventType/truvideoSdkCameraEventRecordingPaused(resolution:orientation:lensFacing:)":{"title":"TruvideoSdkCameraEventType.truvideoSdkCameraEventRecordingPaused(resolution:orientation:lensFacing:)","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraEventType\/truvideoSdkCameraEventRecordingPaused(resolution:orientation:lensFacing:)","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"truvideoSdkCameraEventRecordingPaused"},{"kind":"text","text":"("},{"text":"resolution","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraResolution","text":"TruvideoSdkCameraResolution"},{"kind":"text","text":", "},{"kind":"externalParam","text":"orientation"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraOrientation","kind":"typeIdentifier","text":"TruvideoSdkCameraOrientation"},{"kind":"text","text":", "},{"text":"lensFacing","kind":"externalParam"},{"kind":"text","text":": "},{"text":"TruvideoSdkCameraLensFacing","preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraLensFacing","kind":"typeIdentifier"},{"kind":"text","text":")"}],"type":"topic","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraeventtype\/truvideosdkcameraeventrecordingpaused(resolution:orientation:lensfacing:)","abstract":[{"text":"Triggered when ","type":"text"},{"inlineContent":[{"text":"video recording is paused","type":"text"}],"type":"strong"},{"type":"text","text":"."}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraOrientation":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"TruvideoSdkCameraOrientation","kind":"identifier"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraOrientation","role":"symbol","type":"topic","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraorientation","title":"TruvideoSdkCameraOrientation","abstract":[{"type":"text","text":"Defines the camera orientation for media capture."}],"kind":"symbol","navigatorTitle":[{"text":"TruvideoSdkCameraOrientation","kind":"identifier"}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraLensFacing":{"type":"topic","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraLensFacing","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"TruvideoSdkCameraLensFacing","kind":"identifier"}],"abstract":[{"type":"text","text":"Defines the camera lens direction used for capturing media."}],"kind":"symbol","title":"TruvideoSdkCameraLensFacing","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameralensfacing","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TruvideoSdkCameraLensFacing"}]}},"variantOverrides":[{"patch":[{"value":"TruvideoSdkCameraResolution","op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraResolution\/title"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraResolution\/fragments","op":"replace","value":[{"text":"TruvideoSdkCameraResolution","kind":"identifier"}]},{"value":"TruvideoSdkCameraOrientation","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraOrientation\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"TruvideoSdkCameraOrientation"}],"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraOrientation\/fragments"},{"value":"TruvideoSdkCameraLensFacing","op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraLensFacing\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraLensFacing\/fragments","value":[{"text":"TruvideoSdkCameraLensFacing","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}