{"kind":"symbol","sections":[],"abstract":[{"text":"QR Code format.","type":"text"}],"identifier":{"url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraScannerCodeFormat\/codeQR","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"codeQR"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"codeQR","kind":"identifier"}],"title":"TruvideoSdkCameraScannerCodeFormat.codeQR","modules":[{"name":"TruvideoSdkCamera"}],"role":"symbol","symbolKind":"case","externalID":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraScannerCodeFormat@TruvideoSdkCameraScannerCodeFormatCodeQR","navigatorTitle":[{"kind":"identifier","text":"TruvideoSdkCameraScannerCodeFormatCodeQR"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcamerascannercodeformat\/codeqr"]},{"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcamerascannercodeformat\/codeqr"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraScannerCodeFormat"]]},"references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"kind":"symbol","abstract":[{"type":"text","text":"Store and capture photos and videos using a fully integrated camera system."}],"url":"\/documentation\/truvideosdkcamera","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","title":"TruvideoSdkCamera","type":"topic","role":"collection"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraScannerCodeFormat/codeQR":{"url":"\/documentation\/truvideosdkcamera\/truvideosdkcamerascannercodeformat\/codeqr","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraScannerCodeFormat\/codeQR","navigatorTitle":[{"kind":"identifier","text":"TruvideoSdkCameraScannerCodeFormatCodeQR"}],"role":"symbol","title":"TruvideoSdkCameraScannerCodeFormat.codeQR","type":"topic","kind":"symbol","abstract":[{"text":"QR Code format.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"codeQR","kind":"identifier"}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraScannerCodeFormat":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TruvideoSdkCameraScannerCodeFormat"}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcamerascannercodeformat","title":"TruvideoSdkCameraScannerCodeFormat","abstract":[{"text":"Defines the supported barcode and QR code formats for the scanner.","type":"text"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraScannerCodeFormat","navigatorTitle":[{"text":"TruvideoSdkCameraScannerCodeFormat","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"value":"TruvideoSdkCameraScannerCodeFormatCodeQR","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"value":[{"text":"TruvideoSdkCameraScannerCodeFormatCodeQR","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"TruvideoSdkCameraScannerCodeFormatCodeQR"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"TruvideoSdkCameraScannerCodeFormatCodeQR","op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraScannerCodeFormat~1codeQR\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraScannerCodeFormat~1codeQR\/fragments","value":[{"text":"TruvideoSdkCameraScannerCodeFormatCodeQR","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraScannerCodeFormat\/title","op":"replace","value":"TruvideoSdkCameraScannerCodeFormat"},{"value":[{"kind":"identifier","text":"TruvideoSdkCameraScannerCodeFormat"}],"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraScannerCodeFormat\/fragments"}]}]}