{"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"DataMatrix barcode format."}],"identifier":{"url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraScannerCodeFormat\/dataMatrix","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"dataMatrix","kind":"identifier"}],"title":"TruvideoSdkCameraScannerCodeFormat.dataMatrix","modules":[{"name":"TruvideoSdkCamera"}],"role":"symbol","symbolKind":"case","externalID":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraScannerCodeFormat@TruvideoSdkCameraScannerCodeFormatDataMatrix","navigatorTitle":[{"text":"TruvideoSdkCameraScannerCodeFormatDataMatrix","kind":"identifier"}]},"variants":[{"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcamerascannercodeformat\/datamatrix"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcamerascannercodeformat\/datamatrix"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraScannerCodeFormat"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"dataMatrix","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"kind":"symbol","abstract":[{"type":"text","text":"Store and capture photos and videos using a fully integrated camera system."}],"url":"\/documentation\/truvideosdkcamera","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","title":"TruvideoSdkCamera","type":"topic","role":"collection"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraScannerCodeFormat":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TruvideoSdkCameraScannerCodeFormat"}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcamerascannercodeformat","title":"TruvideoSdkCameraScannerCodeFormat","abstract":[{"text":"Defines the supported barcode and QR code formats for the scanner.","type":"text"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraScannerCodeFormat","navigatorTitle":[{"text":"TruvideoSdkCameraScannerCodeFormat","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraScannerCodeFormat/dataMatrix":{"url":"\/documentation\/truvideosdkcamera\/truvideosdkcamerascannercodeformat\/datamatrix","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraScannerCodeFormat\/dataMatrix","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dataMatrix","kind":"identifier"}],"title":"TruvideoSdkCameraScannerCodeFormat.dataMatrix","kind":"symbol","abstract":[{"type":"text","text":"DataMatrix barcode format."}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TruvideoSdkCameraScannerCodeFormatDataMatrix"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"TruvideoSdkCameraScannerCodeFormatDataMatrix"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"TruvideoSdkCameraScannerCodeFormatDataMatrix"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"TruvideoSdkCameraScannerCodeFormatDataMatrix"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraScannerCodeFormat\/title","op":"replace","value":"TruvideoSdkCameraScannerCodeFormat"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraScannerCodeFormat\/fragments","value":[{"text":"TruvideoSdkCameraScannerCodeFormat","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraScannerCodeFormat~1dataMatrix\/title","value":"TruvideoSdkCameraScannerCodeFormatDataMatrix"},{"value":[{"text":"TruvideoSdkCameraScannerCodeFormatDataMatrix","kind":"identifier"}],"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraScannerCodeFormat~1dataMatrix\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}