{"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"The list of "},{"inlineContent":[{"text":"barcode formats","type":"text"}],"type":"strong"},{"type":"text","text":" that the scanner will detect."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"codeFormats"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraScannerCodeFormat","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraScannerCodeFormat","kind":"typeIdentifier","text":"TruvideoSdkCameraScannerCodeFormat"},{"text":"]","kind":"text"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"inlineContent":[{"type":"text","text":"By default, "},{"inlineContent":[{"type":"text","text":"all formats are enabled"}],"type":"strong"},{"text":".","type":"text"}],"type":"paragraph"}]}],"hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkScannerCameraConfiguration"]]},"sections":[],"kind":"symbol","metadata":{"roleHeading":"Instance Property","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"codeFormats","kind":"identifier"},{"text":": [","kind":"text"},{"text":"TruvideoSdkCameraScannerCodeFormat","kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraScannerCodeFormat"},{"text":"]","kind":"text"}],"externalID":"s:17TruvideoSdkCamera0ab7ScannerC13ConfigurationC11codeFormatsSayAA0abcD10CodeFormatOGvp","modules":[{"name":"TruvideoSdkCamera"}],"symbolKind":"property","title":"codeFormats"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/truvideosdkcamera\/truvideosdkscannercameraconfiguration\/codeformats"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkScannerCameraConfiguration\/codeFormats"},"references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkScannerCameraConfiguration":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkScannerCameraConfiguration","title":"TruvideoSdkScannerCameraConfiguration","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TruvideoSdkScannerCameraConfiguration"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TruvideoSdkScannerCameraConfiguration"}],"type":"topic","url":"\/documentation\/truvideosdkcamera\/truvideosdkscannercameraconfiguration","abstract":[{"text":"Configuration settings for the ","type":"text"},{"type":"strong","inlineContent":[{"text":"Truvideo Scanner Camera","type":"text"}]},{"text":".","type":"text"}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"kind":"symbol","url":"\/documentation\/truvideosdkcamera","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","type":"topic","abstract":[{"text":"Store and capture photos and videos using a fully integrated camera system.","type":"text"}],"title":"TruvideoSdkCamera","role":"collection"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkScannerCameraConfiguration/codeFormats":{"type":"topic","abstract":[{"type":"text","text":"The list of "},{"inlineContent":[{"text":"barcode formats","type":"text"}],"type":"strong"},{"text":" that the scanner will detect.","type":"text"}],"role":"symbol","url":"\/documentation\/truvideosdkcamera\/truvideosdkscannercameraconfiguration\/codeformats","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"codeFormats"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"TruvideoSdkCameraScannerCodeFormat","preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraScannerCodeFormat"},{"kind":"text","text":"]"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkScannerCameraConfiguration\/codeFormats","kind":"symbol","title":"codeFormats"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraScannerCodeFormat":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"TruvideoSdkCameraScannerCodeFormat","kind":"identifier"}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcamerascannercodeformat","abstract":[{"text":"Defines the supported barcode and QR code formats for the scanner.","type":"text"}],"title":"TruvideoSdkCameraScannerCodeFormat","type":"topic","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraScannerCodeFormat","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"TruvideoSdkCameraScannerCodeFormat","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkScannerCameraConfiguration\/title","op":"replace","value":"TruvideoSdkScannerCameraConfiguration"},{"value":[{"kind":"identifier","text":"TruvideoSdkScannerCameraConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkScannerCameraConfiguration\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraScannerCodeFormat\/title","value":"TruvideoSdkCameraScannerCodeFormat"},{"value":[{"text":"TruvideoSdkCameraScannerCodeFormat","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraScannerCodeFormat\/fragments"}]}]}