{"sections":[],"identifier":{"url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkScannerCameraConfiguration\/init(flashMode:orientation:codeFormats:autoClose:validator:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkScannerCameraConfiguration"]]},"metadata":{"modules":[{"name":"TruvideoSdkCamera"}],"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"flashMode","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraFlashMode","text":"TruvideoSdkCameraFlashMode","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"orientation"},{"text":": ","kind":"text"},{"text":"TruvideoSdkCameraOrientation","kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraOrientation"},{"text":"?, ","kind":"text"},{"text":"codeFormats","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"TruvideoSdkCameraScannerCodeFormat","preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraScannerCodeFormat"},{"text":"], ","kind":"text"},{"text":"autoClose","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"validator"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TruvideoSdkCameraScannerValidation","preciseIdentifier":"s:17TruvideoSdkCamera0abC17ScannerValidationa"},{"text":"?)","kind":"text"}],"externalID":"s:17TruvideoSdkCamera0ab7ScannerC13ConfigurationC9flashMode11orientation11codeFormats9autoClose9validatorAcA0abc5FlashG0O_AA0abC11OrientationOSgSayAA0abcD10CodeFormatOGSbAA0abcD16ValidationResultVAA0abcdP0CcSgtcfc","symbolKind":"init","title":"init(flashMode:orientation:codeFormats:autoClose:validator:)","roleHeading":"Initializer"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"flashMode","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraFlashMode","text":"TruvideoSdkCameraFlashMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraFlashMode"},{"text":", ","kind":"text"},{"text":"orientation","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraOrientation","preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraOrientation","text":"TruvideoSdkCameraOrientation"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"codeFormats"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraScannerCodeFormat","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraScannerCodeFormat","text":"TruvideoSdkCameraScannerCodeFormat"},{"text":"] = TruvideoSdkCameraScannerCodeFormat.allCases, ","kind":"text"},{"kind":"externalParam","text":"autoClose"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":" = false, ","kind":"text"},{"kind":"externalParam","text":"validator"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraScannerValidation","preciseIdentifier":"s:17TruvideoSdkCamera0abC17ScannerValidationa","text":"TruvideoSdkCameraScannerValidation","kind":"typeIdentifier"},{"text":"? = nil)","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"flashMode","content":[{"inlineContent":[{"type":"text","text":"The initial flash mode setting."}],"type":"paragraph"}]},{"name":"orientation","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The initial camera orientation."}]}]},{"name":"codeFormats","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The barcode formats to recognize."}]}]},{"name":"autoClose","content":[{"inlineContent":[{"type":"text","text":"Whether the scanner should close after a successful scan."}],"type":"paragraph"}]},{"name":"validator","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An optional validation function for barcode scanning."}]}]}]},{"kind":"content","content":[{"type":"heading","anchor":"discussion","text":"Discussion","level":2},{"syntax":"swift","type":"codeListing","code":["let config = TruvideoSdkScannerCameraConfiguration(","    flashMode: .auto,","    orientation: .portrait,","    codeFormats: [.codeQR, .dataMatrix],","    autoClose: true",")"]}]}],"kind":"symbol","abstract":[{"text":"Initializes a scanner configuration with custom settings.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/truvideosdkcamera\/truvideosdkscannercameraconfiguration\/init(flashmode:orientation:codeformats:autoclose:validator:)"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"kind":"symbol","url":"\/documentation\/truvideosdkcamera","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","type":"topic","abstract":[{"text":"Store and capture photos and videos using a fully integrated camera system.","type":"text"}],"title":"TruvideoSdkCamera","role":"collection"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraOrientation":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"TruvideoSdkCameraOrientation","kind":"identifier"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraOrientation","role":"symbol","type":"topic","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraorientation","title":"TruvideoSdkCameraOrientation","abstract":[{"type":"text","text":"Defines the camera orientation for media capture."}],"kind":"symbol","navigatorTitle":[{"text":"TruvideoSdkCameraOrientation","kind":"identifier"}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraFlashMode":{"title":"TruvideoSdkCameraFlashMode","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraFlashMode","kind":"symbol","abstract":[{"type":"text","text":"Defines the flash mode settings for the camera."}],"role":"symbol","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraflashmode","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TruvideoSdkCameraFlashMode"}],"navigatorTitle":[{"kind":"identifier","text":"TruvideoSdkCameraFlashMode"}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkScannerCameraConfiguration/init(flashMode:orientation:codeFormats:autoClose:validator:)":{"type":"topic","role":"symbol","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkScannerCameraConfiguration\/init(flashMode:orientation:codeFormats:autoClose:validator:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"flashMode"},{"kind":"text","text":": "},{"text":"TruvideoSdkCameraFlashMode","preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraFlashMode","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"orientation","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraOrientation","kind":"typeIdentifier","text":"TruvideoSdkCameraOrientation"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"codeFormats"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraScannerCodeFormat","kind":"typeIdentifier","text":"TruvideoSdkCameraScannerCodeFormat"},{"text":"], ","kind":"text"},{"text":"autoClose","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"validator"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TruvideoSdkCameraScannerValidation","preciseIdentifier":"s:17TruvideoSdkCamera0abC17ScannerValidationa"},{"kind":"text","text":"?)"}],"title":"init(flashMode:orientation:codeFormats:autoClose:validator:)","kind":"symbol","abstract":[{"type":"text","text":"Initializes a scanner configuration with custom settings."}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkscannercameraconfiguration\/init(flashmode:orientation:codeformats:autoclose:validator:)"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkScannerCameraConfiguration":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkScannerCameraConfiguration","title":"TruvideoSdkScannerCameraConfiguration","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TruvideoSdkScannerCameraConfiguration"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TruvideoSdkScannerCameraConfiguration"}],"type":"topic","url":"\/documentation\/truvideosdkcamera\/truvideosdkscannercameraconfiguration","abstract":[{"text":"Configuration settings for the ","type":"text"},{"type":"strong","inlineContent":[{"text":"Truvideo Scanner Camera","type":"text"}]},{"text":".","type":"text"}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraScannerValidation":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"TruvideoSdkCameraScannerValidation","kind":"identifier"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraScannerValidation","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TruvideoSdkCameraScannerValidation"}],"title":"TruvideoSdkCameraScannerValidation","kind":"symbol","abstract":[{"type":"text","text":"A function signature for validating scanned barcodes."}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcamerascannervalidation"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraScannerCodeFormat":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"TruvideoSdkCameraScannerCodeFormat","kind":"identifier"}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcamerascannercodeformat","abstract":[{"text":"Defines the supported barcode and QR code formats for the scanner.","type":"text"}],"title":"TruvideoSdkCameraScannerCodeFormat","type":"topic","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraScannerCodeFormat","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"TruvideoSdkCameraScannerCodeFormat","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"TruvideoSdkCameraOrientation","op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraOrientation\/title"},{"value":[{"text":"TruvideoSdkCameraOrientation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraOrientation\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraFlashMode\/title","value":"TruvideoSdkCameraFlashMode"},{"value":[{"text":"TruvideoSdkCameraFlashMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraFlashMode\/fragments"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkScannerCameraConfiguration\/title","op":"replace","value":"TruvideoSdkScannerCameraConfiguration"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkScannerCameraConfiguration\/fragments","op":"replace","value":[{"text":"TruvideoSdkScannerCameraConfiguration","kind":"identifier"}]},{"value":"TruvideoSdkCameraScannerCodeFormat","op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraScannerCodeFormat\/title"},{"value":[{"kind":"identifier","text":"TruvideoSdkCameraScannerCodeFormat"}],"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraScannerCodeFormat\/fragments"}]}]}