{"hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraScannerCodeFormat"]]},"sections":[],"abstract":[{"type":"text","text":"Code-93 barcode format."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"code93"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcamerascannercodeformat\/code93"]},{"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcamerascannercodeformat\/code93"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraScannerCodeFormat\/code93"},"metadata":{"modules":[{"name":"TruvideoSdkCamera"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"code93","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"TruvideoSdkCameraScannerCodeFormatCode93","kind":"identifier"}],"externalID":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraScannerCodeFormat@TruvideoSdkCameraScannerCodeFormatCode93","symbolKind":"case","roleHeading":"Case","title":"TruvideoSdkCameraScannerCodeFormat.code93"},"references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","title":"TruvideoSdkCamera","role":"collection","type":"topic","url":"\/documentation\/truvideosdkcamera","kind":"symbol","abstract":[{"text":"Store and capture photos and videos using a fully integrated camera system.","type":"text"}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraScannerCodeFormat/code93":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraScannerCodeFormat\/code93","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"code93"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"TruvideoSdkCameraScannerCodeFormatCode93","kind":"identifier"}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcamerascannercodeformat\/code93","abstract":[{"text":"Code-93 barcode format.","type":"text"}],"kind":"symbol","title":"TruvideoSdkCameraScannerCodeFormat.code93"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraScannerCodeFormat":{"navigatorTitle":[{"kind":"identifier","text":"TruvideoSdkCameraScannerCodeFormat"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"TruvideoSdkCameraScannerCodeFormat","kind":"identifier"}],"abstract":[{"text":"Defines the supported barcode and QR code formats for the scanner.","type":"text"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraScannerCodeFormat","url":"\/documentation\/truvideosdkcamera\/truvideosdkcamerascannercodeformat","kind":"symbol","title":"TruvideoSdkCameraScannerCodeFormat","type":"topic","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"TruvideoSdkCameraScannerCodeFormatCode93","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"TruvideoSdkCameraScannerCodeFormatCode93","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"TruvideoSdkCameraScannerCodeFormatCode93"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraScannerCodeFormat~1code93\/title","value":"TruvideoSdkCameraScannerCodeFormatCode93"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraScannerCodeFormat~1code93\/fragments","value":[{"text":"TruvideoSdkCameraScannerCodeFormatCode93","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraScannerCodeFormat\/title","value":"TruvideoSdkCameraScannerCodeFormat"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraScannerCodeFormat\/fragments","value":[{"text":"TruvideoSdkCameraScannerCodeFormat","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}