{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"orientation","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraOrientation","preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraOrientation","text":"TruvideoSdkCameraOrientation","kind":"typeIdentifier"}],"languages":["swift"]}]},{"content":[{"anchor":"discussion","text":"Discussion","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Determines whether the camera operates in portrait or landscape mode."}]}],"kind":"content"}],"kind":"symbol","abstract":[{"text":"The camera orientation used when capturing AR content.","type":"text"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/truvideosdkcamera\/truvideosdkarcameraconfiguration\/orientation"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/truvideosdkcamera\/truvideosdkarcameraconfiguration\/orientation"]}],"identifier":{"url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkARCameraConfiguration\/orientation","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Instance Property","externalID":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkARCameraConfiguration(py)orientation","title":"orientation","role":"symbol","modules":[{"name":"TruvideoSdkCamera"}],"symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"orientation"},{"text":": ","kind":"text"},{"text":"TruvideoSdkCameraOrientation","kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraOrientation"}],"navigatorTitle":[{"text":"orientation","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkARCameraConfiguration"]]},"references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkARCameraConfiguration/orientation":{"role":"symbol","type":"topic","url":"\/documentation\/truvideosdkcamera\/truvideosdkarcameraconfiguration\/orientation","kind":"symbol","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkARCameraConfiguration\/orientation","abstract":[{"type":"text","text":"The camera orientation used when capturing AR content."}],"title":"orientation","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"orientation"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraOrientation","text":"TruvideoSdkCameraOrientation","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"orientation"}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkARCameraConfiguration":{"abstract":[{"type":"text","text":"A configuration object for setting up the AR Camera in "},{"code":"TruvideoSdkCamera","type":"codeVoice"},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TruvideoSdkARCameraConfiguration","kind":"identifier"}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkarcameraconfiguration","type":"topic","role":"symbol","navigatorTitle":[{"text":"TruvideoSdkARCameraConfiguration","kind":"identifier"}],"kind":"symbol","title":"TruvideoSdkARCameraConfiguration","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkARCameraConfiguration"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"kind":"symbol","url":"\/documentation\/truvideosdkcamera","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","type":"topic","abstract":[{"text":"Store and capture photos and videos using a fully integrated camera system.","type":"text"}],"title":"TruvideoSdkCamera","role":"collection"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraOrientation":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"TruvideoSdkCameraOrientation","kind":"identifier"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraOrientation","role":"symbol","type":"topic","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraorientation","title":"TruvideoSdkCameraOrientation","abstract":[{"type":"text","text":"Defines the camera orientation for media capture."}],"kind":"symbol","navigatorTitle":[{"text":"TruvideoSdkCameraOrientation","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"orientation","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"orientation","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TruvideoSdkCameraOrientation","preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraOrientation","kind":"typeIdentifier","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraOrientation"},{"kind":"text","text":" "},{"text":"orientation","kind":"identifier"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkARCameraConfiguration~1orientation\/title","value":"orientation","op":"replace"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkARCameraConfiguration~1orientation\/fragments","value":[{"text":"orientation","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"TruvideoSdkARCameraConfiguration","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkARCameraConfiguration\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkARCameraConfiguration\/fragments","value":[{"kind":"identifier","text":"TruvideoSdkARCameraConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraOrientation\/title","value":"TruvideoSdkCameraOrientation"},{"value":[{"text":"TruvideoSdkCameraOrientation","kind":"identifier"}],"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraOrientation\/fragments","op":"replace"}]}]}