{"metadata":{"symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"TruvideoSdkCamera"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ambientLightColor"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@vector_float3","kind":"typeIdentifier","text":"vector_float3"}],"title":"ambientLightColor","navigatorTitle":[{"text":"ambientLightColor","kind":"identifier"}],"role":"symbol","externalID":"c:@SA@SharedUniforms@FI@ambientLightColor"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ambientLightColor"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@vector_float3","text":"vector_float3","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/SharedUniforms"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/SharedUniforms\/ambientLightColor"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/truvideosdkcamera\/shareduniforms\/ambientlightcolor"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/truvideosdkcamera\/shareduniforms\/ambientlightcolor"]}],"references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/SharedUniforms":{"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SharedUniforms"}],"url":"\/documentation\/truvideosdkcamera\/shareduniforms","title":"SharedUniforms","abstract":[],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/SharedUniforms","navigatorTitle":[{"text":"SharedUniforms","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"kind":"symbol","abstract":[{"type":"text","text":"Store and capture photos and videos using a fully integrated camera system."}],"url":"\/documentation\/truvideosdkcamera","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","title":"TruvideoSdkCamera","type":"topic","role":"collection"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/SharedUniforms/ambientLightColor":{"abstract":[],"title":"ambientLightColor","url":"\/documentation\/truvideosdkcamera\/shareduniforms\/ambientlightcolor","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"ambientLightColor","kind":"identifier"},{"kind":"text","text":": "},{"text":"vector_float3","preciseIdentifier":"c:@T@vector_float3","kind":"typeIdentifier"}],"kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"text":"ambientLightColor","kind":"identifier"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/SharedUniforms\/ambientLightColor"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"ambientLightColor"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"ambientLightColor","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"typeIdentifier","text":"vector_float3","preciseIdentifier":"c:@T@vector_float3"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ambientLightColor"}]}]},"path":"\/primaryContentSections\/0"},{"value":"SharedUniforms","op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1SharedUniforms\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1SharedUniforms~1ambientLightColor\/title","value":"ambientLightColor"},{"op":"replace","value":[{"kind":"identifier","text":"ambientLightColor"}],"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1SharedUniforms~1ambientLightColor\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}