{"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"title":"position","modules":[{"name":"TruvideoSdkCamera"}],"externalID":"c:@SA@MeasureUniforms@FI@position","roleHeading":"Instance Property","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"position"},{"kind":"text","text":": "},{"text":"simd_float4","kind":"typeIdentifier","preciseIdentifier":"c:@T@simd_float4"}],"navigatorTitle":[{"kind":"identifier","text":"position"}],"symbolKind":"property"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"position","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@simd_float4","kind":"typeIdentifier","text":"simd_float4"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/MeasureUniforms\/position"},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/MeasureUniforms"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/truvideosdkcamera\/measureuniforms\/position"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/truvideosdkcamera\/measureuniforms\/position"]}],"references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/MeasureUniforms/position":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/MeasureUniforms\/position","type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"position"},{"text":": ","kind":"text"},{"text":"simd_float4","kind":"typeIdentifier","preciseIdentifier":"c:@T@simd_float4"}],"url":"\/documentation\/truvideosdkcamera\/measureuniforms\/position","abstract":[],"title":"position","navigatorTitle":[{"kind":"identifier","text":"position"}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/MeasureUniforms":{"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MeasureUniforms"}],"url":"\/documentation\/truvideosdkcamera\/measureuniforms","title":"MeasureUniforms","abstract":[],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/MeasureUniforms","navigatorTitle":[{"text":"MeasureUniforms","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"kind":"symbol","abstract":[{"type":"text","text":"Store and capture photos and videos using a fully integrated camera system."}],"url":"\/documentation\/truvideosdkcamera","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","title":"TruvideoSdkCamera","type":"topic","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"position","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"position","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"simd_float4","kind":"typeIdentifier","preciseIdentifier":"c:@T@simd_float4"},{"text":" ","kind":"text"},{"kind":"identifier","text":"position"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1MeasureUniforms~1position\/title","op":"replace","value":"position"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1MeasureUniforms~1position\/fragments","value":[{"kind":"identifier","text":"position"}]},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1MeasureUniforms\/title","value":"MeasureUniforms"}]}]}