{"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"createdAt"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"filePath"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"type"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraMediaType","kind":"typeIdentifier","text":"TruvideoSdkCameraMediaType"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"cameraLensFacing"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraLensFacing","text":"TruvideoSdkCameraLensFacing","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"rotation","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraOrientation","text":"TruvideoSdkCameraOrientation","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"resolution","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraResolution","text":"TruvideoSdkCameraResolution"},{"text":", ","kind":"text"},{"text":"duration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int64","preciseIdentifier":"s:s5Int64V","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(createdAt:filePath:type:cameraLensFacing:rotation:resolution:duration:)","role":"symbol","symbolKind":"init","externalID":"s:17TruvideoSdkCamera0abC5MediaC9createdAt8filePath4type16cameraLensFacing8rotation10resolution8durationACSd_SSAA0abcD4TypeOAA0abckL0OAA0abC11OrientationOAA0abC10ResolutionCs5Int64Vtcfc","roleHeading":"Initializer","modules":[{"name":"TruvideoSdkCamera"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Initializes a ","type":"text"},{"type":"codeVoice","code":"TruvideoSdkCameraMedia"},{"type":"text","text":" instance with the provided media attributes."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcameramedia\/init(createdat:filepath:type:cameralensfacing:rotation:resolution:duration:)"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"text":"createdAt","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":", ","kind":"text"},{"text":"filePath","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"text":"TruvideoSdkCameraMediaType","kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraMediaType","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraMediaType"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"cameraLensFacing"},{"kind":"text","text":": "},{"text":"TruvideoSdkCameraLensFacing","kind":"typeIdentifier","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraLensFacing","preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraLensFacing"},{"text":", ","kind":"text"},{"text":"rotation","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraOrientation","text":"TruvideoSdkCameraOrientation","kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraOrientation"},{"kind":"text","text":", "},{"text":"resolution","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraResolution","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraResolution","kind":"typeIdentifier","text":"TruvideoSdkCameraResolution"},{"text":", ","kind":"text"},{"text":"duration","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int64","kind":"typeIdentifier","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The timestamp (in seconds) when the media was created.","type":"text"}],"type":"paragraph"}],"name":"createdAt"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The file path where the media is stored."}]}],"name":"filePath"},{"name":"type","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The type of media (clip or photo)."}]}]},{"name":"cameraLensFacing","content":[{"inlineContent":[{"type":"text","text":"The camera lens direction when captured."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The orientation of the camera when captured."}]}],"name":"rotation"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The resolution of the captured media.","type":"text"}]}],"name":"resolution"},{"content":[{"inlineContent":[{"text":"The duration of the media in milliseconds (applicable for video clips).","type":"text"}],"type":"paragraph"}],"name":"duration"}]}],"sections":[],"identifier":{"url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraMedia\/init(createdAt:filePath:type:cameraLensFacing:rotation:resolution:duration:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraMedia"]]},"references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraLensFacing":{"type":"topic","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraLensFacing","title":"TruvideoSdkCameraLensFacing","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TruvideoSdkCameraLensFacing"}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameralensfacing","navigatorTitle":[{"text":"TruvideoSdkCameraLensFacing","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Defines the camera lens direction used for capturing media.","type":"text"}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraMediaType":{"navigatorTitle":[{"text":"TruvideoSdkCameraMediaType","kind":"identifier"}],"type":"topic","title":"TruvideoSdkCameraMediaType","kind":"symbol","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameramediatype","role":"symbol","abstract":[{"type":"text","text":"An enumeration representing the different media types supported by the Truvideo SDK camera."}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraMediaType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TruvideoSdkCameraMediaType"}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","title":"TruvideoSdkCamera","role":"collection","type":"topic","url":"\/documentation\/truvideosdkcamera","kind":"symbol","abstract":[{"text":"Store and capture photos and videos using a fully integrated camera system.","type":"text"}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraOrientation":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TruvideoSdkCameraOrientation"}],"title":"TruvideoSdkCameraOrientation","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TruvideoSdkCameraOrientation"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraOrientation","abstract":[{"type":"text","text":"Defines the camera orientation for media capture."}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraorientation"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraMedia":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TruvideoSdkCameraMedia","kind":"identifier"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraMedia","abstract":[{"text":"A class representing a media file captured by the Truvideo SDK camera.","type":"text"}],"title":"TruvideoSdkCameraMedia","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameramedia","navigatorTitle":[{"kind":"identifier","text":"TruvideoSdkCameraMedia"}],"kind":"symbol","type":"topic","role":"symbol"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraResolution":{"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraresolution","kind":"symbol","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraResolution","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TruvideoSdkCameraResolution"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"TruvideoSdkCameraResolution"}],"title":"TruvideoSdkCameraResolution","abstract":[]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraMedia/init(createdAt:filePath:type:cameraLensFacing:rotation:resolution:duration:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"createdAt","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"filePath"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"type"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraMediaType","text":"TruvideoSdkCameraMediaType"},{"text":", ","kind":"text"},{"text":"cameraLensFacing","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraLensFacing","text":"TruvideoSdkCameraLensFacing","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"rotation","kind":"externalParam"},{"kind":"text","text":": "},{"text":"TruvideoSdkCameraOrientation","kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraOrientation"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"resolution"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TruvideoSdkCameraResolution","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraResolution"},{"text":", ","kind":"text"},{"text":"duration","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":")"}],"title":"init(createdAt:filePath:type:cameraLensFacing:rotation:resolution:duration:)","type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraMedia\/init(createdAt:filePath:type:cameraLensFacing:rotation:resolution:duration:)","abstract":[{"text":"Initializes a ","type":"text"},{"code":"TruvideoSdkCameraMedia","type":"codeVoice"},{"type":"text","text":" instance with the provided media attributes."}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameramedia\/init(createdat:filepath:type:cameralensfacing:rotation:resolution:duration:)"}},"variantOverrides":[{"patch":[{"value":"TruvideoSdkCameraLensFacing","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraLensFacing\/title","op":"replace"},{"value":[{"text":"TruvideoSdkCameraLensFacing","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraLensFacing\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraMediaType\/title","value":"TruvideoSdkCameraMediaType"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraMediaType\/fragments","value":[{"kind":"identifier","text":"TruvideoSdkCameraMediaType"}]},{"value":"TruvideoSdkCameraOrientation","op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraOrientation\/title"},{"value":[{"text":"TruvideoSdkCameraOrientation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraOrientation\/fragments"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraMedia\/title","value":"TruvideoSdkCameraMedia","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraMedia\/fragments","value":[{"text":"TruvideoSdkCameraMedia","kind":"identifier"}]},{"op":"replace","value":"TruvideoSdkCameraResolution","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraResolution\/title"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraResolution\/fragments","op":"replace","value":[{"text":"TruvideoSdkCameraResolution","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}