{"topicSections":[{"identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/kBufferIndexMeshGenerics","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/kBufferIndexMeshPositions","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/kBufferIndexSharedUniforms"],"title":"Variables"},{"title":"Initializers","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/BufferIndices\/init(_:)","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/BufferIndices\/init(rawValue:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/BufferIndices\/rawValue"]},{"identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/BufferIndices\/Equatable-Implementations"],"title":"Default Implementations","generated":true}],"metadata":{"roleHeading":"Structure","modules":[{"name":"TruvideoSdkCamera"}],"navigatorTitle":[{"text":"BufferIndices","kind":"identifier"}],"symbolKind":"struct","role":"symbol","title":"BufferIndices","externalID":"c:@E@BufferIndices","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BufferIndices"}]},"identifier":{"url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/BufferIndices","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/truvideosdkcamera\/bufferindices"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/truvideosdkcamera\/bufferindices"]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"BufferIndices","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"relationshipsSections":[{"title":"Conforms To","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/SQ","doc:\/\/com.truvideo.TruvideoSdkCamera\/SY","doc:\/\/com.truvideo.TruvideoSdkCamera\/s8SendableP"],"type":"conformsTo","kind":"relationships"}],"references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/BufferIndices/Equatable-Implementations":{"url":"\/documentation\/truvideosdkcamera\/bufferindices\/equatable-implementations","role":"collectionGroup","title":"Equatable Implementations","abstract":[],"type":"topic","kind":"article","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/BufferIndices\/Equatable-Implementations"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/kBufferIndexMeshGenerics":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"kBufferIndexMeshGenerics","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@BufferIndices","kind":"typeIdentifier","text":"BufferIndices"}],"kind":"symbol","url":"\/documentation\/truvideosdkcamera\/kbufferindexmeshgenerics","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/kBufferIndexMeshGenerics","title":"kBufferIndexMeshGenerics","abstract":[],"role":"symbol","navigatorTitle":[{"text":"kBufferIndexMeshGenerics","kind":"identifier"}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/BufferIndices/init(rawValue:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s6UInt32V","kind":"typeIdentifier","text":"UInt32"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/BufferIndices\/init(rawValue:)","role":"symbol","abstract":[],"kind":"symbol","type":"topic","url":"\/documentation\/truvideosdkcamera\/bufferindices\/init(rawvalue:)","title":"init(rawValue:)"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/BufferIndices":{"abstract":[],"type":"topic","navigatorTitle":[{"text":"BufferIndices","kind":"identifier"}],"title":"BufferIndices","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/BufferIndices","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"BufferIndices"}],"url":"\/documentation\/truvideosdkcamera\/bufferindices","kind":"symbol"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/kBufferIndexMeshPositions":{"abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"kBufferIndexMeshPositions"},{"kind":"text","text":": "},{"text":"BufferIndices","preciseIdentifier":"c:@E@BufferIndices","kind":"typeIdentifier"}],"role":"symbol","kind":"symbol","url":"\/documentation\/truvideosdkcamera\/kbufferindexmeshpositions","type":"topic","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/kBufferIndexMeshPositions","navigatorTitle":[{"text":"kBufferIndexMeshPositions","kind":"identifier"}],"title":"kBufferIndexMeshPositions"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"kind":"symbol","url":"\/documentation\/truvideosdkcamera","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","type":"topic","abstract":[{"text":"Store and capture photos and videos using a fully integrated camera system.","type":"text"}],"title":"TruvideoSdkCamera","role":"collection"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/BufferIndices/rawValue":{"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"rawValue","kind":"identifier"},{"kind":"text","text":": "},{"text":"UInt32","preciseIdentifier":"s:s6UInt32V","kind":"typeIdentifier"}],"url":"\/documentation\/truvideosdkcamera\/bufferindices\/rawvalue","abstract":[],"title":"rawValue","role":"symbol","type":"topic","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/BufferIndices\/rawValue"},"doc://com.truvideo.TruvideoSdkCamera/SQ":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.truvideo.TruvideoSdkCamera/s8SendableP":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/s8SendableP","title":"Swift.Sendable","type":"unresolvable"},"doc://com.truvideo.TruvideoSdkCamera/SY":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/kBufferIndexSharedUniforms":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"kBufferIndexSharedUniforms"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BufferIndices","preciseIdentifier":"c:@E@BufferIndices"}],"navigatorTitle":[{"kind":"identifier","text":"kBufferIndexSharedUniforms"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/kBufferIndexSharedUniforms","role":"symbol","abstract":[],"kind":"symbol","type":"topic","url":"\/documentation\/truvideosdkcamera\/kbufferindexshareduniforms","title":"kBufferIndexSharedUniforms"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/BufferIndices/init(_:)":{"abstract":[],"type":"topic","title":"init(_:)","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/BufferIndices\/init(_:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:s6UInt32V","text":"UInt32"},{"text":")","kind":"text"}],"url":"\/documentation\/truvideosdkcamera\/bufferindices\/init(_:)","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration","op":"replace","path":"\/metadata\/roleHeading"},{"value":"BufferIndices","op":"replace","path":"\/metadata\/title"},{"value":"enum","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"BufferIndices","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"BufferIndices","kind":"identifier"}],"op":"replace"},{"value":[{"identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/kBufferIndexMeshGenerics","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/kBufferIndexMeshPositions","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/kBufferIndexSharedUniforms"],"title":"Enumeration Cases"}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"typedef","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"BufferIndices","kind":"identifier"},{"kind":"text","text":": "},{"text":"unsigned int","preciseIdentifier":"c:i","kind":"typeIdentifier"},{"kind":"text","text":" { ... } "},{"text":"BufferIndices","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1kBufferIndexMeshGenerics\/title","value":"kBufferIndexMeshGenerics","op":"replace"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1kBufferIndexMeshGenerics\/fragments","op":"replace","value":[{"text":"kBufferIndexMeshGenerics","kind":"identifier"}]},{"op":"replace","value":"BufferIndices","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1BufferIndices\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1BufferIndices\/fragments","value":[{"text":"BufferIndices","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1kBufferIndexMeshPositions\/title","value":"kBufferIndexMeshPositions"},{"value":[{"text":"kBufferIndexMeshPositions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1kBufferIndexMeshPositions\/fragments"},{"value":"kBufferIndexSharedUniforms","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1kBufferIndexSharedUniforms\/title","op":"replace"},{"value":[{"text":"kBufferIndexSharedUniforms","kind":"identifier"}],"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1kBufferIndexSharedUniforms\/fragments","op":"replace"}]}]}