{"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"article","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/GettingStartedWithCamera"},"seeAlsoSections":[{"identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/UsingARCamera"],"title":"Related Documentation"},{"generated":true,"title":"Essentials","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/UsingARCamera","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/UsingCameraScanner"]}],"primaryContentSections":[{"content":[{"level":2,"type":"heading","text":"Overview","anchor":"Overview"},{"inlineContent":[{"text":"The ","type":"text"},{"type":"strong","inlineContent":[{"text":"TruvideoSdkCamera","type":"text"}]},{"type":"text","text":" framework provides a customizable Camera that allows applications to:"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"📸 "},{"type":"strong","inlineContent":[{"type":"text","text":"Take high-resolution photos"}]}]}]},{"content":[{"inlineContent":[{"text":"🎥 ","type":"text"},{"type":"strong","inlineContent":[{"text":"Record videos with configurable duration","type":"text"}]}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"🔄 "},{"type":"strong","inlineContent":[{"type":"text","text":"Switch between front and rear cameras"}]}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"💡 ","type":"text"},{"inlineContent":[{"type":"text","text":"Enable or disable flash"}],"type":"strong"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"📐 ","type":"text"},{"type":"strong","inlineContent":[{"text":"Control camera orientation and resolution","type":"text"}]}]}]}],"type":"unorderedList"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This guide explains how to configure and integrate the Camera using "},{"type":"strong","inlineContent":[{"type":"text","text":"TruvideoSdkCamera"}]},{"type":"text","text":"."}]},{"type":"heading","level":2,"text":"Pre-Requisites","anchor":"Pre-Requisites"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Before using the camera, ensure the necessary frameworks are imported and the user is "},{"type":"strong","inlineContent":[{"text":"authenticated","type":"text"}]},{"text":".","type":"text"}]},{"anchor":"Import-Required-Modules","type":"heading","level":3,"text":"Import Required Modules"},{"type":"paragraph","inlineContent":[{"text":"To access camera functionalities, import the following frameworks:","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"TruvideoSdk"}]}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"TruvideoCameraSdk"}]}]}]}]},{"anchor":"Configuring-the-Camera","type":"heading","level":2,"text":"Configuring the Camera"},{"inlineContent":[{"text":"To configure the camera, create a ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraConfiguration","isActive":true},{"text":" object with your desired settings.","type":"text"}],"type":"paragraph"},{"type":"codeListing","syntax":"swift","code":["    let cameraPreset = TruvideoSdkCameraConfiguration(","        flashMode: .auto,","        mode: .videoAndPicture(videoMaxCount: 5, pictureMaxCount: 3, durationLimit: 10),","        orientation: .portrait","    )"]},{"level":2,"type":"heading","anchor":"Integrating-the-Camera-in-SwiftUI","text":"Integrating the Camera in SwiftUI"},{"type":"paragraph","inlineContent":[{"text":"The Standard Camera can be embedded in a SwiftUI view using the ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"presentTruvideoSdkCameraView"}]},{"type":"text","text":" modifier. This allows users"},{"text":" ","type":"text"},{"type":"text","text":"to capture photos and videos directly within your SwiftUI-based application."}]},{"type":"paragraph","inlineContent":[{"text":"To present the camera, bind a ","type":"text"},{"inlineContent":[{"type":"text","text":"Boolean state"}],"type":"strong"},{"text":" to control visibility and pass in a camera configuration preset.","type":"text"}]},{"code":["    var body: some View {","        VStack(spacing: 16) {","            Button(\"Open Camera\") {","                $showCamera = true","            }","        }","        .presentTruvideoSdkCameraView(isPresented: $showCamera, preset: cameraPreset) { result in","            print(result)","        }","    }"],"syntax":"swift","type":"codeListing"},{"type":"heading","level":2,"text":"Handling Camera Output","anchor":"Handling-Camera-Output"},{"inlineContent":[{"text":"When a user captures a photo or records a video, the ","type":"text"},{"code":"onComplete","type":"codeVoice"},{"type":"text","text":" closure provides a "},{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraResult","type":"reference","isActive":true},{"type":"text","text":" object."},{"text":" ","type":"text"},{"type":"text","text":"This result contains one or more media files, including metadata such as file path and type."}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"text","text":"To handle the camera output, process the result in the "},{"type":"codeVoice","code":"onComplete"},{"type":"text","text":" closure."}]},{"code":["func processCameraResult(_ result: TruvideoSdkCameraResult) {","    for media in result.media {","        print(\"Captured media: \\(media.filePath)\")","    }","}"],"type":"codeListing","syntax":"swift"},{"text":"Summary","type":"heading","level":2,"anchor":"Summary"},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"Use "},{"type":"strong","inlineContent":[{"type":"text","text":"presentTruvideoSdkCameraView"}]},{"text":" to ","type":"text"},{"inlineContent":[{"text":"integrate the camera in SwiftUI","type":"text"}],"type":"strong"},{"text":".","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Control visibility using a ","type":"text"},{"inlineContent":[{"text":"Boolean state","type":"text"}],"type":"strong"},{"text":".","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Pass a ","type":"text"},{"type":"strong","inlineContent":[{"text":"camera preset","type":"text"}]},{"text":" to configure capture settings.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Handle captured media using the "},{"type":"strong","inlineContent":[{"type":"text","text":"onComplete"}]},{"type":"text","text":" callback."}]}]}],"type":"unorderedList"}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera"]]},"metadata":{"roleHeading":"Article","title":"Integrating the Camera into Your App","modules":[{"name":"TruvideoSdkCamera"}],"role":"article"},"variants":[{"paths":["\/documentation\/truvideosdkcamera\/gettingstartedwithcamera"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/truvideosdkcamera\/gettingstartedwithcamera"]}],"sections":[],"abstract":[{"text":"Learn how to integrate the Camera in ","type":"text"},{"inlineContent":[{"type":"text","text":"TruvideoSdkCamera"}],"type":"strong"},{"text":" for photo and video capturing.","type":"text"}],"references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"kind":"symbol","url":"\/documentation\/truvideosdkcamera","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","type":"topic","abstract":[{"text":"Store and capture photos and videos using a fully integrated camera system.","type":"text"}],"title":"TruvideoSdkCamera","role":"collection"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraConfiguration":{"navigatorTitle":[{"kind":"identifier","text":"TruvideoSdkCameraConfiguration"}],"kind":"symbol","title":"TruvideoSdkCameraConfiguration","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TruvideoSdkCameraConfiguration","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraconfiguration","abstract":[{"type":"text","text":"A configuration object for setting up the camera in "},{"code":"TruvideoSdkCamera","type":"codeVoice"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraConfiguration"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraResult":{"navigatorTitle":[{"text":"TruvideoSdkCameraResult","kind":"identifier"}],"kind":"symbol","title":"TruvideoSdkCameraResult","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TruvideoSdkCameraResult"}],"type":"topic","role":"symbol","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraresult","abstract":[{"text":"A result of the recording session.","type":"text"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraResult"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/UsingCameraScanner":{"kind":"article","title":"Using the Camera Scanner","type":"topic","role":"article","url":"\/documentation\/truvideosdkcamera\/usingcamerascanner","abstract":[{"type":"text","text":"Learn how to integrate the Camera Scanner in "},{"type":"strong","inlineContent":[{"text":"TruvideoSdkCamera","type":"text"}]},{"type":"text","text":" to enable barcode and QR code"},{"text":" ","type":"text"},{"text":"scanning with flash support, auto-close functionality, and validation capabilities.","type":"text"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/UsingCameraScanner"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/UsingARCamera":{"abstract":[{"type":"text","text":"Learn how to integrate the AR Camera in "},{"inlineContent":[{"type":"text","text":"TruvideoSdkCamera"}],"type":"strong"},{"text":" to enable Augmented Reality (AR) experiences, including 3D","type":"text"},{"type":"text","text":" "},{"type":"text","text":"object placement, distance measurement, and AR-enhanced video recording."}],"role":"article","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/UsingARCamera","kind":"article","title":"Using the AR Camera","url":"\/documentation\/truvideosdkcamera\/usingarcamera","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":null,"op":"add","path":"\/topicSections"},{"value":[{"title":"Related Documentation","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/UsingARCamera"]},{"identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/UsingARCamera","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/UsingCameraScanner"],"title":"Essentials","generated":true}],"path":"\/seeAlsoSections","op":"replace"},{"value":"TruvideoSdkCameraConfiguration","op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraConfiguration\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraConfiguration\/fragments","value":[{"kind":"identifier","text":"TruvideoSdkCameraConfiguration"}]},{"value":"TruvideoSdkCameraResult","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraResult\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraResult\/fragments","value":[{"kind":"identifier","text":"TruvideoSdkCameraResult"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}