{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"kTextureIndexCbCr","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@TextureIndices","text":"TextureIndices","kind":"typeIdentifier","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TextureIndices"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/truvideosdkcamera\/ktextureindexcbcr"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/truvideosdkcamera\/ktextureindexcbcr"]}],"sections":[],"metadata":{"externalID":"c:@E@TextureIndices@kTextureIndexCbCr","roleHeading":"Global Variable","title":"kTextureIndexCbCr","role":"symbol","symbolKind":"var","modules":[{"name":"TruvideoSdkCamera"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"kTextureIndexCbCr"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TextureIndices","preciseIdentifier":"c:@E@TextureIndices"}],"navigatorTitle":[{"kind":"identifier","text":"kTextureIndexCbCr"}]},"kind":"symbol","identifier":{"url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/kTextureIndexCbCr","interfaceLanguage":"swift"},"references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/kTextureIndexCbCr":{"navigatorTitle":[{"text":"kTextureIndexCbCr","kind":"identifier"}],"url":"\/documentation\/truvideosdkcamera\/ktextureindexcbcr","abstract":[],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"kTextureIndexCbCr"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@TextureIndices","text":"TextureIndices"}],"type":"topic","title":"kTextureIndexCbCr","kind":"symbol","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/kTextureIndexCbCr"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TextureIndices":{"title":"TextureIndices","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TextureIndices","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"TextureIndices","kind":"identifier"}],"abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"TextureIndices"}],"url":"\/documentation\/truvideosdkcamera\/textureindices","kind":"symbol","role":"symbol"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"kind":"symbol","url":"\/documentation\/truvideosdkcamera","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","type":"topic","abstract":[{"text":"Store and capture photos and videos using a fully integrated camera system.","type":"text"}],"title":"TruvideoSdkCamera","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"kTextureIndexCbCr","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"kTextureIndexCbCr","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"kTextureIndexCbCr"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1kTextureIndexCbCr\/title","op":"replace","value":"kTextureIndexCbCr"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1kTextureIndexCbCr\/fragments","value":[{"kind":"identifier","text":"kTextureIndexCbCr"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TextureIndices\/title","value":"TextureIndices"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TextureIndices\/fragments","value":[{"kind":"identifier","text":"TextureIndices"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}