{"hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"roleHeading":"Structure","modules":[{"name":"TruvideoSdkCamera"}],"navigatorTitle":[{"kind":"identifier","text":"MeasureUniforms"}],"symbolKind":"struct","role":"symbol","title":"MeasureUniforms","externalID":"c:@SA@MeasureUniforms","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"MeasureUniforms"}]},"sections":[],"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/MeasureUniforms\/init()","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/MeasureUniforms\/init(position:)"],"title":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/MeasureUniforms\/position"]}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/s8SendableP"],"title":"Conforms To","type":"conformsTo"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MeasureUniforms"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/truvideosdkcamera\/measureuniforms"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/truvideosdkcamera\/measureuniforms"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/MeasureUniforms"},"references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/MeasureUniforms":{"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MeasureUniforms"}],"abstract":[],"title":"MeasureUniforms","role":"symbol","url":"\/documentation\/truvideosdkcamera\/measureuniforms","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/MeasureUniforms","navigatorTitle":[{"text":"MeasureUniforms","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/MeasureUniforms/init(position:)":{"role":"symbol","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"position"},{"kind":"text","text":": "},{"text":"simd_float4","kind":"typeIdentifier","preciseIdentifier":"c:@T@simd_float4"},{"text":")","kind":"text"}],"abstract":[],"kind":"symbol","url":"\/documentation\/truvideosdkcamera\/measureuniforms\/init(position:)","title":"init(position:)","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/MeasureUniforms\/init(position:)"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/MeasureUniforms/position":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/MeasureUniforms\/position","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"position","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@simd_float4","text":"simd_float4","kind":"typeIdentifier"}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"position"}],"kind":"symbol","title":"position","abstract":[],"url":"\/documentation\/truvideosdkcamera\/measureuniforms\/position"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"kind":"symbol","url":"\/documentation\/truvideosdkcamera","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","type":"topic","abstract":[{"text":"Store and capture photos and videos using a fully integrated camera system.","type":"text"}],"title":"TruvideoSdkCamera","role":"collection"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/MeasureUniforms/init()":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/MeasureUniforms\/init()","title":"init()","role":"symbol","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"type":"topic","url":"\/documentation\/truvideosdkcamera\/measureuniforms\/init()","abstract":[]},"doc://com.truvideo.TruvideoSdkCamera/s8SendableP":{"title":"Swift.Sendable","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/s8SendableP","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Structure"},{"op":"replace","path":"\/metadata\/title","value":"MeasureUniforms"},{"value":"struct","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MeasureUniforms"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/MeasureUniforms\/position"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"typedef"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"MeasureUniforms","kind":"identifier"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1MeasureUniforms\/title","value":"MeasureUniforms","op":"replace"},{"op":"replace","value":"position","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1MeasureUniforms~1position\/title"},{"value":[{"kind":"identifier","text":"position"}],"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1MeasureUniforms~1position\/fragments"}]}]}