{"metadata":{"roleHeading":"Enumeration","externalID":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraLensFacing","symbolKind":"enum","role":"symbol","modules":[{"name":"TruvideoSdkCamera"}],"title":"TruvideoSdkCameraLensFacing","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TruvideoSdkCameraLensFacing"}],"navigatorTitle":[{"text":"TruvideoSdkCameraLensFacing","kind":"identifier"}]},"kind":"symbol","sections":[],"relationshipsSections":[{"identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/Se","doc:\/\/com.truvideo.TruvideoSdkCamera\/SE","doc:\/\/com.truvideo.TruvideoSdkCamera\/SQ","doc:\/\/com.truvideo.TruvideoSdkCamera\/SH","doc:\/\/com.truvideo.TruvideoSdkCamera\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcameralensfacing"]},{"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcameralensfacing"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraLensFacing","interfaceLanguage":"swift"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraLensFacing\/back","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraLensFacing\/front"]},{"title":"Initializers","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraLensFacing\/init(from:)-5hk6c","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraLensFacing\/init(rawValue:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraLensFacing\/rawValue-swift.property"]},{"identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraLensFacing\/encode(to:)"],"title":"Instance Methods"},{"identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraLensFacing\/RawValue-swift.typealias"],"title":"Type Aliases"},{"title":"Default Implementations","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraLensFacing\/Equatable-Implementations","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraLensFacing\/RawRepresentable-Implementations"],"generated":true}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TruvideoSdkCameraLensFacing"}]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"text":"Overview","anchor":"overview","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"This enum specifies whether the camera is using the ","type":"text"},{"inlineContent":[{"text":"front-facing","type":"text"}],"type":"strong"},{"type":"text","text":" or "},{"type":"strong","inlineContent":[{"text":"back-facing","type":"text"}]},{"type":"text","text":" lens."}]},{"text":"Available Values","level":2,"type":"heading","anchor":"Available-Values"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraLensFacing\/back","isActive":true,"type":"reference"},{"type":"text","text":": Uses the "},{"inlineContent":[{"text":"rear-facing","type":"text"}],"type":"strong"},{"text":" camera.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraLensFacing\/front","type":"reference"},{"type":"text","text":": Uses the "},{"type":"strong","inlineContent":[{"type":"text","text":"front-facing"}]},{"type":"text","text":" camera (selfie mode)."}]}]}],"type":"unorderedList"},{"type":"heading","level":2,"text":"Example Usage","anchor":"Example-Usage"},{"type":"codeListing","syntax":"swift","code":["let cameraConfig = TruvideoSdkCameraConfiguration(","    lensFacing: .back,","    flashMode: .off,","    orientation: .portrait,","    outputPath: \"video_output.mp4\",","    frontResolutions: [],","    frontResolution: nil,","    backResolutions: [],","    backResolution: nil,","    mode: .videoOnly",")"]}]}],"hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera"]]},"abstract":[{"text":"Defines the camera lens direction used for capturing media.","type":"text"}],"references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"kind":"symbol","url":"\/documentation\/truvideosdkcamera","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","type":"topic","abstract":[{"text":"Store and capture photos and videos using a fully integrated camera system.","type":"text"}],"title":"TruvideoSdkCamera","role":"collection"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraLensFacing/back":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"back","kind":"identifier"}],"type":"topic","abstract":[{"text":"Uses the rear-facing camera.","type":"text"}],"title":"TruvideoSdkCameraLensFacing.back","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameralensfacing\/back","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraLensFacing\/back","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"TruvideoSdkCameraLensFacingBack","kind":"identifier"}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraLensFacing/rawValue-swift.property":{"kind":"symbol","role":"symbol","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameralensfacing\/rawvalue-swift.property","title":"rawValue","abstract":[{"type":"text","text":"The corresponding value of the raw type."}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraLensFacing\/rawValue-swift.property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"rawValue","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"RawValue","preciseIdentifier":"s:17TruvideoSdkCamera0abC10LensFacingO8RawValuea"}],"type":"topic"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraLensFacing/RawValue-swift.typealias":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraLensFacing\/RawValue-swift.typealias","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RawValue","kind":"identifier"}],"title":"TruvideoSdkCameraLensFacing.RawValue","abstract":[{"type":"text","text":"The raw type that can be used to represent all values of the conforming"},{"type":"text","text":" "},{"text":"type.","type":"text"}],"kind":"symbol","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameralensfacing\/rawvalue-swift.typealias","type":"topic","navigatorTitle":[{"text":"RawValue","kind":"identifier"}]},"doc://com.truvideo.TruvideoSdkCamera/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/SY"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraLensFacing/front":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraLensFacing\/front","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameralensfacing\/front","title":"TruvideoSdkCameraLensFacing.front","abstract":[{"type":"text","text":"Uses the front-facing camera (selfie mode)."}],"navigatorTitle":[{"kind":"identifier","text":"TruvideoSdkCameraLensFacingFront"}],"role":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"front","kind":"identifier"}],"kind":"symbol"},"doc://com.truvideo.TruvideoSdkCamera/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/SH"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraLensFacing/encode(to:)":{"title":"encode(to:)","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraLensFacing\/encode(to:)","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"encode"},{"kind":"text","text":"("},{"text":"to","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"keyword","text":"any"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:s7EncoderP","text":"Encoder","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"type":"topic","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameralensfacing\/encode(to:)","abstract":[{"type":"text","text":"Encodes this value into the given encoder."}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraLensFacing/init(rawValue:)":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraLensFacing\/init(rawValue:)","kind":"symbol","type":"topic","title":"init(rawValue:)","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameralensfacing\/init(rawvalue:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:17TruvideoSdkCamera0abC10LensFacingO8RawValuea","text":"RawValue","kind":"typeIdentifier"},{"kind":"text","text":")"}],"abstract":[{"text":"Creates a new instance with the specified raw value.","type":"text"}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraLensFacing":{"type":"topic","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraLensFacing","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"TruvideoSdkCameraLensFacing","kind":"identifier"}],"abstract":[{"type":"text","text":"Defines the camera lens direction used for capturing media."}],"kind":"symbol","title":"TruvideoSdkCameraLensFacing","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameralensfacing","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TruvideoSdkCameraLensFacing"}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraLensFacing/init(from:)-5hk6c":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraLensFacing\/init(from:)-5hk6c","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameralensfacing\/init(from:)-5hk6c","abstract":[{"type":"text","text":"Creates a new instance by decoding from the given decoder."}],"kind":"symbol","type":"topic","title":"init(from:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"keyword","text":"any"},{"text":" ","kind":"text"},{"text":"Decoder","kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraLensFacing/Equatable-Implementations":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraLensFacing\/Equatable-Implementations","title":"Equatable Implementations","role":"collectionGroup","kind":"article","type":"topic","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameralensfacing\/equatable-implementations","abstract":[]},"doc://com.truvideo.TruvideoSdkCamera/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/SE"},"doc://com.truvideo.TruvideoSdkCamera/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/SQ"},"doc://com.truvideo.TruvideoSdkCamera/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/Se"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraLensFacing/RawRepresentable-Implementations":{"type":"topic","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraLensFacing\/RawRepresentable-Implementations","abstract":[],"kind":"article","title":"RawRepresentable Implementations","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameralensfacing\/rawrepresentable-implementations","role":"collectionGroup"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"TruvideoSdkCameraLensFacing"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"TruvideoSdkCameraLensFacing"}]},{"op":"replace","value":[{"kind":"identifier","text":"TruvideoSdkCameraLensFacing"}],"path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraLensFacing\/back","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraLensFacing\/front"],"title":"Enumeration Cases"}],"op":"replace"},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"TruvideoSdkCameraLensFacing","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"TruvideoSdkCameraLensFacingBack","op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraLensFacing~1back\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraLensFacing~1back\/fragments","value":[{"kind":"identifier","text":"TruvideoSdkCameraLensFacingBack"}]},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraLensFacing~1front\/title","value":"TruvideoSdkCameraLensFacingFront"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraLensFacing~1front\/fragments","value":[{"kind":"identifier","text":"TruvideoSdkCameraLensFacingFront"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraLensFacing\/title","op":"replace","value":"TruvideoSdkCameraLensFacing"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraLensFacing\/fragments","value":[{"text":"TruvideoSdkCameraLensFacing","kind":"identifier"}],"op":"replace"}]}]}