{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcameraresult"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcameraresult"]}],"kind":"symbol","abstract":[{"text":"A result of the recording session.","type":"text"}],"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/objc(pl)NSObject","doc:\/\/com.truvideo.TruvideoSdkCamera\/s7CVarArgP","doc:\/\/com.truvideo.TruvideoSdkCamera\/s28CustomDebugStringConvertibleP","doc:\/\/com.truvideo.TruvideoSdkCamera\/s23CustomStringConvertibleP","doc:\/\/com.truvideo.TruvideoSdkCamera\/SE","doc:\/\/com.truvideo.TruvideoSdkCamera\/SQ","doc:\/\/com.truvideo.TruvideoSdkCamera\/SH"],"type":"conformsTo"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraResult"},"schemaVersion":{"major":0,"patch":0,"minor":3},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraResult\/media"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TruvideoSdkCameraResult","kind":"identifier"}],"languages":["swift"]}]}],"metadata":{"modules":[{"name":"TruvideoSdkCamera"}],"externalID":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraResult","role":"symbol","roleHeading":"Class","title":"TruvideoSdkCameraResult","navigatorTitle":[{"kind":"identifier","text":"TruvideoSdkCameraResult"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TruvideoSdkCameraResult","kind":"identifier"}],"symbolKind":"class"},"hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera"]]},"sections":[],"references":{"doc://com.truvideo.TruvideoSdkCamera/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/SQ"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"kind":"symbol","url":"\/documentation\/truvideosdkcamera","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","type":"topic","abstract":[{"text":"Store and capture photos and videos using a fully integrated camera system.","type":"text"}],"title":"TruvideoSdkCamera","role":"collection"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraResult/media":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraResult\/media","title":"media","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"media"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"media"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraMedia","kind":"typeIdentifier","text":"TruvideoSdkCameraMedia"},{"text":"]","kind":"text"}],"type":"topic","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraresult\/media","abstract":[{"type":"text","text":"The media recorded during the session."}]},"doc://com.truvideo.TruvideoSdkCamera/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/s28CustomDebugStringConvertibleP"},"doc://com.truvideo.TruvideoSdkCamera/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/objc(pl)NSObject"},"doc://com.truvideo.TruvideoSdkCamera/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/objc(cs)NSObject"},"doc://com.truvideo.TruvideoSdkCamera/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/SH"},"doc://com.truvideo.TruvideoSdkCamera/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/SE"},"doc://com.truvideo.TruvideoSdkCamera/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/s7CVarArgP"},"doc://com.truvideo.TruvideoSdkCamera/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/s23CustomStringConvertibleP"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraResult":{"navigatorTitle":[{"text":"TruvideoSdkCameraResult","kind":"identifier"}],"kind":"symbol","title":"TruvideoSdkCameraResult","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TruvideoSdkCameraResult"}],"type":"topic","role":"symbol","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraresult","abstract":[{"text":"A result of the recording session.","type":"text"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraResult"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"TruvideoSdkCameraResult","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"TruvideoSdkCameraResult"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"TruvideoSdkCameraResult"}]},{"path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraResult\/media"]}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/objc(cs)NSObject"]}],"op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"TruvideoSdkCameraResult","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraResult~1media\/title","value":"media","op":"replace"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraResult~1media\/fragments","op":"replace","value":[{"kind":"identifier","text":"media"}]},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraResult\/title","op":"replace","value":"TruvideoSdkCameraResult"},{"op":"replace","value":[{"kind":"identifier","text":"TruvideoSdkCameraResult"}],"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraResult\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}