{"sections":[],"abstract":[{"type":"text","text":"Defines the delegate responsible for retrieving camera information."}],"topicSections":[{"identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraDelegate\/getTruvideoSdkCameraInformation()"],"title":"Instance Methods"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraDelegate"},"hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TruvideoSdkCameraDelegate","kind":"identifier"}]}],"kind":"declarations"},{"content":[{"level":2,"anchor":"overview","type":"heading","text":"Overview"},{"inlineContent":[{"type":"text","text":"The "},{"code":"TruvideoSdkCameraDelegate","type":"codeVoice"},{"type":"text","text":" allows applications to fetch camera details, such as available lenses,"},{"type":"text","text":" "},{"text":"supported resolutions, and hardware capabilities.","type":"text"}],"type":"paragraph"},{"anchor":"Example-Usage","type":"heading","level":2,"text":"Example Usage"},{"type":"codeListing","syntax":"swift","code":["let cameraInfo = TruvideoSdkCameraProvider.shared.camera.getTruvideoSdkCameraInformation()"]}],"kind":"content"}],"metadata":{"roleHeading":"Protocol","title":"TruvideoSdkCameraDelegate","symbolKind":"protocol","navigatorTitle":[{"kind":"identifier","text":"TruvideoSdkCameraDelegate"}],"modules":[{"name":"TruvideoSdkCamera"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"TruvideoSdkCameraDelegate","kind":"identifier"}],"externalID":"c:@M@TruvideoSdkCamera@objc(pl)TruvideoSdkCameraDelegate","role":"symbol"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcameradelegate"]},{"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcameradelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraDelegate/getTruvideoSdkCameraInformation()":{"abstract":[{"type":"text","text":"Retrieves all available camera information for both "},{"type":"strong","inlineContent":[{"type":"text","text":"front"}]},{"type":"text","text":" and "},{"inlineContent":[{"type":"text","text":"back"}],"type":"strong"},{"text":" cameras.","type":"text"}],"title":"getTruvideoSdkCameraInformation()","navigatorTitle":[{"text":"getTruvideoSdkCameraInformation","kind":"identifier"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraDelegate\/getTruvideoSdkCameraInformation()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getTruvideoSdkCameraInformation"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraInformation","text":"TruvideoSdkCameraInformation"}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameradelegate\/gettruvideosdkcamerainformation()","kind":"symbol","required":true,"type":"topic","role":"symbol"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraDelegate":{"abstract":[{"text":"Defines the delegate responsible for retrieving camera information.","type":"text"}],"title":"TruvideoSdkCameraDelegate","navigatorTitle":[{"text":"TruvideoSdkCameraDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"TruvideoSdkCameraDelegate","kind":"identifier"}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameradelegate","kind":"symbol","type":"topic","role":"symbol"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"kind":"symbol","url":"\/documentation\/truvideosdkcamera","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","type":"topic","abstract":[{"text":"Store and capture photos and videos using a fully integrated camera system.","type":"text"}],"title":"TruvideoSdkCamera","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Protocol","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"TruvideoSdkCameraDelegate","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"TruvideoSdkCameraDelegate","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"TruvideoSdkCameraDelegate"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraDelegate\/getTruvideoSdkCameraInformation()"],"title":"Instance Methods"}],"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TruvideoSdkCameraDelegate"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraDelegate~1getTruvideoSdkCameraInformation()\/title","value":"getTruvideoSdkCameraInformation"},{"value":[{"kind":"text","text":"- "},{"text":"getTruvideoSdkCameraInformation","kind":"identifier"}],"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraDelegate~1getTruvideoSdkCameraInformation()\/fragments","op":"replace"},{"value":"TruvideoSdkCameraDelegate","op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraDelegate\/title"},{"value":[{"text":"TruvideoSdkCameraDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraDelegate\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}