{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraMediaType"]]},"abstract":[{"text":"The media type representing a recorded video clip.","type":"text"}],"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"clip","kind":"identifier"}],"title":"TruvideoSdkCameraMediaType.clip","role":"symbol","symbolKind":"case","externalID":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraMediaType@TruvideoSdkCameraMediaTypeClip","navigatorTitle":[{"text":"TruvideoSdkCameraMediaTypeClip","kind":"identifier"}],"roleHeading":"Case","modules":[{"name":"TruvideoSdkCamera"}]},"identifier":{"url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraMediaType\/clip","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"clip"}]}]}],"variants":[{"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcameramediatype\/clip"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcameramediatype\/clip"]}],"references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","title":"TruvideoSdkCamera","role":"collection","type":"topic","url":"\/documentation\/truvideosdkcamera","kind":"symbol","abstract":[{"text":"Store and capture photos and videos using a fully integrated camera system.","type":"text"}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraMediaType":{"navigatorTitle":[{"text":"TruvideoSdkCameraMediaType","kind":"identifier"}],"type":"topic","title":"TruvideoSdkCameraMediaType","kind":"symbol","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameramediatype","role":"symbol","abstract":[{"type":"text","text":"An enumeration representing the different media types supported by the Truvideo SDK camera."}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraMediaType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TruvideoSdkCameraMediaType"}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraMediaType/clip":{"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameramediatype\/clip","navigatorTitle":[{"kind":"identifier","text":"TruvideoSdkCameraMediaTypeClip"}],"kind":"symbol","abstract":[{"type":"text","text":"The media type representing a recorded video clip."}],"role":"symbol","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraMediaType\/clip","title":"TruvideoSdkCameraMediaType.clip","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"clip"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"TruvideoSdkCameraMediaTypeClip","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"TruvideoSdkCameraMediaTypeClip"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"TruvideoSdkCameraMediaTypeClip"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraMediaType\/title","op":"replace","value":"TruvideoSdkCameraMediaType"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraMediaType\/fragments","value":[{"kind":"identifier","text":"TruvideoSdkCameraMediaType"}]},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraMediaType~1clip\/title","op":"replace","value":"TruvideoSdkCameraMediaTypeClip"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraMediaType~1clip\/fragments","op":"replace","value":[{"kind":"identifier","text":"TruvideoSdkCameraMediaTypeClip"}]}]}]}