{"variants":[{"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcameramediatype\/photo"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcameramediatype\/photo"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"roleHeading":"Case","externalID":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraMediaType@TruvideoSdkCameraMediaTypePhoto","title":"TruvideoSdkCameraMediaType.photo","symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"TruvideoSdkCameraMediaTypePhoto"}],"modules":[{"name":"TruvideoSdkCamera"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"photo"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraMediaType\/photo"},"hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraMediaType"]]},"sections":[],"abstract":[{"type":"text","text":"The media type representing a captured photo."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"photo","kind":"identifier"}],"languages":["swift"]}]}],"references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraMediaType/photo":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraMediaType\/photo","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"photo","kind":"identifier"}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TruvideoSdkCameraMediaTypePhoto"}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameramediatype\/photo","abstract":[{"type":"text","text":"The media type representing a captured photo."}],"kind":"symbol","title":"TruvideoSdkCameraMediaType.photo"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","title":"TruvideoSdkCamera","role":"collection","type":"topic","url":"\/documentation\/truvideosdkcamera","kind":"symbol","abstract":[{"text":"Store and capture photos and videos using a fully integrated camera system.","type":"text"}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraMediaType":{"navigatorTitle":[{"text":"TruvideoSdkCameraMediaType","kind":"identifier"}],"type":"topic","title":"TruvideoSdkCameraMediaType","kind":"symbol","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameramediatype","role":"symbol","abstract":[{"type":"text","text":"An enumeration representing the different media types supported by the Truvideo SDK camera."}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraMediaType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TruvideoSdkCameraMediaType"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"TruvideoSdkCameraMediaTypePhoto","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"TruvideoSdkCameraMediaTypePhoto"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"TruvideoSdkCameraMediaTypePhoto","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraMediaType~1photo\/title","value":"TruvideoSdkCameraMediaTypePhoto"},{"value":[{"kind":"identifier","text":"TruvideoSdkCameraMediaTypePhoto"}],"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraMediaType~1photo\/fragments"},{"op":"replace","value":"TruvideoSdkCameraMediaType","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraMediaType\/title"},{"value":[{"kind":"identifier","text":"TruvideoSdkCameraMediaType"}],"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraMediaType\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}