{"identifier":{"url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/truvideosdkcamera"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/truvideosdkcamera"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"Store and capture photos and videos using a fully integrated camera system.","type":"text"}],"topicSections":[{"identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/GettingStartedWithCamera","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/UsingARCamera","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/UsingCameraScanner"],"title":"Essentials"},{"identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkARCameraConfiguration","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraConfiguration","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraDevice","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraInformation","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraMedia","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraMediaMode","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraProvider","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraResolution","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraResult","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraScannerCode","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkScannerCameraConfiguration"],"title":"Classes"},{"title":"Protocols","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraAppDelegate","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraDelegate","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraEventsInterface","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraInterface"]},{"title":"Structures","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/BufferIndices","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/InstanceUniforms","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/MeasureUniforms","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/SharedUniforms","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TextureIndices","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruVideoError","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraEvent","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraScannerValidationResult","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/VertexAttributes"]},{"identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCamera","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/kBufferIndexInstanceVertices","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/kTextureIndexCbCr","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/kTextureIndexColor","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/kTextureIndexRGB","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/kTextureIndexY"],"title":"Variables"},{"identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraEventObserver","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraScannerValidation","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkScannerCameraViewCallback"],"title":"Type Aliases"},{"identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraEventType","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraFlashMode","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraLensFacing","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraMediaType","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraOrientation","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraScannerCodeFormat"],"title":"Enumerations"},{"identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/SwiftUI","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/UIKit"],"title":"Extended Modules"}],"kind":"symbol","metadata":{"externalID":"TruvideoSdkCamera","symbolKind":"module","roleHeading":"Framework","title":"TruvideoSdkCamera","role":"collection","modules":[{"name":"TruvideoSdkCamera"}]},"sections":[],"hierarchy":{"paths":[[]]},"primaryContentSections":[{"kind":"content","content":[{"type":"heading","anchor":"overview","text":"Overview","level":2},{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"type":"strong","inlineContent":[{"text":"TruvideoSdkCamera","type":"text"}]},{"type":"text","text":" framework provides a powerful, all-in-one camera solution that enables apps to "},{"inlineContent":[{"type":"text","text":"capture, record, and manage media efficiently"}],"type":"strong"},{"text":". It supports ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"Augmented Reality (AR), barcode scanning, and high-quality photo and video operations"}]},{"text":", making it ideal for a wide range of applications.","type":"text"}]}]}],"references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/BufferIndices":{"role":"symbol","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/BufferIndices","navigatorTitle":[{"text":"BufferIndices","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/truvideosdkcamera\/bufferindices","abstract":[],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"BufferIndices"}],"title":"BufferIndices"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/kTextureIndexCbCr":{"role":"symbol","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/kTextureIndexCbCr","navigatorTitle":[{"text":"kTextureIndexCbCr","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/truvideosdkcamera\/ktextureindexcbcr","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kTextureIndexCbCr"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@TextureIndices","text":"TextureIndices","kind":"typeIdentifier"}],"title":"kTextureIndexCbCr"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/kTextureIndexRGB":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"kTextureIndexRGB"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TextureIndices","preciseIdentifier":"c:@E@TextureIndices"}],"url":"\/documentation\/truvideosdkcamera\/ktextureindexrgb","title":"kTextureIndexRGB","abstract":[],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/kTextureIndexRGB","navigatorTitle":[{"text":"kTextureIndexRGB","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraFlashMode":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TruvideoSdkCameraFlashMode"}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraflashmode","title":"TruvideoSdkCameraFlashMode","abstract":[{"type":"text","text":"Defines the flash mode settings for the camera."}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraFlashMode","navigatorTitle":[{"text":"TruvideoSdkCameraFlashMode","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/kBufferIndexInstanceVertices":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"kBufferIndexInstanceVertices"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BufferIndices","preciseIdentifier":"c:@E@BufferIndices"}],"url":"\/documentation\/truvideosdkcamera\/kbufferindexinstancevertices","title":"kBufferIndexInstanceVertices","abstract":[],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/kBufferIndexInstanceVertices","navigatorTitle":[{"text":"kBufferIndexInstanceVertices","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraEventObserver":{"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"TruvideoSdkCameraEventObserver"}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraeventobserver","title":"TruvideoSdkCameraEventObserver","abstract":[{"type":"text","text":"A publisher that emits camera-related events."}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraEventObserver","navigatorTitle":[{"text":"TruvideoSdkCameraEventObserver","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TextureIndices":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TextureIndices"}],"url":"\/documentation\/truvideosdkcamera\/textureindices","title":"TextureIndices","abstract":[],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TextureIndices","navigatorTitle":[{"kind":"identifier","text":"TextureIndices"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraInterface":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"TruvideoSdkCameraInterface","kind":"identifier"}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcamerainterface","title":"TruvideoSdkCameraInterface","abstract":[{"type":"text","text":"Defines the interface for accessing "},{"code":"TruvideoSdkCamera","type":"codeVoice"},{"type":"text","text":" functionalities."}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraInterface","navigatorTitle":[{"text":"TruvideoSdkCameraInterface","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkARCameraConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TruvideoSdkARCameraConfiguration"}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkarcameraconfiguration","title":"TruvideoSdkARCameraConfiguration","abstract":[{"type":"text","text":"A configuration object for setting up the AR Camera in "},{"code":"TruvideoSdkCamera","type":"codeVoice"},{"text":".","type":"text"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkARCameraConfiguration","navigatorTitle":[{"text":"TruvideoSdkARCameraConfiguration","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/UsingCameraScanner":{"title":"Using the Camera Scanner","role":"article","abstract":[{"type":"text","text":"Learn how to integrate the Camera Scanner in "},{"type":"strong","inlineContent":[{"text":"TruvideoSdkCamera","type":"text"}]},{"type":"text","text":" to enable barcode and QR code"},{"type":"text","text":" "},{"text":"scanning with flash support, auto-close functionality, and validation capabilities.","type":"text"}],"type":"topic","kind":"article","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/UsingCameraScanner","url":"\/documentation\/truvideosdkcamera\/usingcamerascanner"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkScannerCameraConfiguration":{"title":"TruvideoSdkScannerCameraConfiguration","role":"symbol","abstract":[{"text":"Configuration settings for the ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"Truvideo Scanner Camera"}]},{"type":"text","text":"."}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TruvideoSdkScannerCameraConfiguration"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkScannerCameraConfiguration","url":"\/documentation\/truvideosdkcamera\/truvideosdkscannercameraconfiguration","navigatorTitle":[{"text":"TruvideoSdkScannerCameraConfiguration","kind":"identifier"}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"kind":"symbol","abstract":[{"type":"text","text":"Store and capture photos and videos using a fully integrated camera system."}],"url":"\/documentation\/truvideosdkcamera","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","title":"TruvideoSdkCamera","type":"topic","role":"collection"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/kTextureIndexColor":{"title":"kTextureIndexColor","role":"symbol","abstract":[],"type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"kTextureIndexColor","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@TextureIndices","text":"TextureIndices","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/kTextureIndexColor","url":"\/documentation\/truvideosdkcamera\/ktextureindexcolor","navigatorTitle":[{"text":"kTextureIndexColor","kind":"identifier"}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraEventsInterface":{"title":"TruvideoSdkCameraEventsInterface","role":"symbol","abstract":[{"type":"text","text":"Defines the interface for handling camera-related events."}],"type":"topic","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"TruvideoSdkCameraEventsInterface","kind":"identifier"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraEventsInterface","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraeventsinterface","navigatorTitle":[{"kind":"identifier","text":"TruvideoSdkCameraEventsInterface"}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraMediaMode":{"title":"TruvideoSdkCameraMediaMode","role":"symbol","abstract":[],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TruvideoSdkCameraMediaMode"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraMediaMode","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameramediamode","navigatorTitle":[{"text":"TruvideoSdkCameraMediaMode","kind":"identifier"}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraScannerValidationResult":{"title":"TruvideoSdkCameraScannerValidationResult","role":"symbol","abstract":[{"type":"text","text":"Represents the result of a barcode validation process."}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TruvideoSdkCameraScannerValidationResult"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraScannerValidationResult","url":"\/documentation\/truvideosdkcamera\/truvideosdkcamerascannervalidationresult","navigatorTitle":[{"text":"TruvideoSdkCameraScannerValidationResult","kind":"identifier"}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/UsingARCamera":{"title":"Using the AR Camera","role":"article","abstract":[{"type":"text","text":"Learn how to integrate the AR Camera in "},{"type":"strong","inlineContent":[{"type":"text","text":"TruvideoSdkCamera"}]},{"text":" to enable Augmented Reality (AR) experiences, including 3D","type":"text"},{"type":"text","text":" "},{"type":"text","text":"object placement, distance measurement, and AR-enhanced video recording."}],"type":"topic","kind":"article","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/UsingARCamera","url":"\/documentation\/truvideosdkcamera\/usingarcamera"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraInformation":{"title":"TruvideoSdkCameraInformation","role":"symbol","abstract":[{"type":"text","text":"Provides detailed information about available camera devices."}],"type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TruvideoSdkCameraInformation","kind":"identifier"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraInformation","url":"\/documentation\/truvideosdkcamera\/truvideosdkcamerainformation","navigatorTitle":[{"kind":"identifier","text":"TruvideoSdkCameraInformation"}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruVideoError":{"title":"TruVideoError","role":"symbol","abstract":[{"type":"text","text":"A type representing all the errors that can be thrown."}],"type":"topic","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"TruVideoError","kind":"identifier"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruVideoError","url":"\/documentation\/truvideosdkcamera\/truvideoerror","navigatorTitle":[{"text":"TruVideoError","kind":"identifier"}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraResolution":{"kind":"symbol","abstract":[],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraresolution","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TruvideoSdkCameraResolution","kind":"identifier"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraResolution","title":"TruvideoSdkCameraResolution","type":"topic","navigatorTitle":[{"text":"TruvideoSdkCameraResolution","kind":"identifier"}],"role":"symbol"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraConfiguration":{"title":"TruvideoSdkCameraConfiguration","role":"symbol","abstract":[{"type":"text","text":"A configuration object for setting up the camera in "},{"code":"TruvideoSdkCamera","type":"codeVoice"},{"text":".","type":"text"}],"type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TruvideoSdkCameraConfiguration","kind":"identifier"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraConfiguration","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraconfiguration","navigatorTitle":[{"kind":"identifier","text":"TruvideoSdkCameraConfiguration"}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraMediaType":{"title":"TruvideoSdkCameraMediaType","role":"symbol","abstract":[{"type":"text","text":"An enumeration representing the different media types supported by the Truvideo SDK camera."}],"type":"topic","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"TruvideoSdkCameraMediaType","kind":"identifier"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraMediaType","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameramediatype","navigatorTitle":[{"kind":"identifier","text":"TruvideoSdkCameraMediaType"}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraScannerCode":{"title":"TruvideoSdkCameraScannerCode","role":"symbol","abstract":[{"text":"Represents the result of a barcode or QR code scan.","type":"text"}],"type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TruvideoSdkCameraScannerCode","kind":"identifier"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraScannerCode","url":"\/documentation\/truvideosdkcamera\/truvideosdkcamerascannercode","navigatorTitle":[{"kind":"identifier","text":"TruvideoSdkCameraScannerCode"}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraOrientation":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"TruvideoSdkCameraOrientation","kind":"identifier"}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraorientation","title":"TruvideoSdkCameraOrientation","abstract":[{"type":"text","text":"Defines the camera orientation for media capture."}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraOrientation","navigatorTitle":[{"kind":"identifier","text":"TruvideoSdkCameraOrientation"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraScannerCodeFormat":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TruvideoSdkCameraScannerCodeFormat"}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcamerascannercodeformat","title":"TruvideoSdkCameraScannerCodeFormat","abstract":[{"text":"Defines the supported barcode and QR code formats for the scanner.","type":"text"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraScannerCodeFormat","navigatorTitle":[{"text":"TruvideoSdkCameraScannerCodeFormat","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraDevice":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TruvideoSdkCameraDevice","kind":"identifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"TruvideoSdkCameraDevice","kind":"identifier"}],"abstract":[{"type":"text","text":"Represents a camera device available on the system."}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameradevice","type":"topic","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraDevice","title":"TruvideoSdkCameraDevice"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraDelegate":{"kind":"symbol","abstract":[{"type":"text","text":"Defines the delegate responsible for retrieving camera information."}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameradelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TruvideoSdkCameraDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraDelegate","title":"TruvideoSdkCameraDelegate","type":"topic","navigatorTitle":[{"text":"TruvideoSdkCameraDelegate","kind":"identifier"}],"role":"symbol"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/SwiftUI":{"url":"\/documentation\/truvideosdkcamera\/swiftui","title":"SwiftUI","abstract":[],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/SwiftUI","kind":"symbol","role":"collection","type":"topic"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraVersionNumber":{"fragments":[{"kind":"identifier","text":"TruvideoSdkCameraVersionNumber"}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraversionnumber","title":"TruvideoSdkCameraVersionNumber","abstract":[{"type":"text","text":"Project version number for TruvideoSdkCamera."}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraVersionNumber","kind":"symbol","role":"symbol","type":"topic"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/MeasureUniforms":{"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MeasureUniforms"}],"url":"\/documentation\/truvideosdkcamera\/measureuniforms","title":"MeasureUniforms","abstract":[],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/MeasureUniforms","navigatorTitle":[{"text":"MeasureUniforms","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraEvent":{"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"TruvideoSdkCameraEvent","kind":"identifier"}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraevent","title":"TruvideoSdkCameraEvent","abstract":[{"type":"text","text":"Represents a camera event emitted by "},{"type":"codeVoice","code":"TruvideoSdkCamera"},{"text":".","type":"text"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraEvent","navigatorTitle":[{"text":"TruvideoSdkCameraEvent","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraVersionString":{"fragments":[{"kind":"identifier","text":"TruvideoSdkCameraVersionString"}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraversionstring","title":"TruvideoSdkCameraVersionString","abstract":[{"type":"text","text":"Project version string for TruvideoSdkCamera."}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraVersionString","kind":"symbol","role":"symbol","type":"topic"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/SharedUniforms":{"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SharedUniforms"}],"url":"\/documentation\/truvideosdkcamera\/shareduniforms","title":"SharedUniforms","abstract":[],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/SharedUniforms","navigatorTitle":[{"text":"SharedUniforms","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/kTextureIndexY":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"kTextureIndexY"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@TextureIndices","text":"TextureIndices","kind":"typeIdentifier"}],"url":"\/documentation\/truvideosdkcamera\/ktextureindexy","title":"kTextureIndexY","abstract":[],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/kTextureIndexY","navigatorTitle":[{"kind":"identifier","text":"kTextureIndexY"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraResult":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TruvideoSdkCameraResult"}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraresult","title":"TruvideoSdkCameraResult","abstract":[{"type":"text","text":"A result of the recording session."}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraResult","navigatorTitle":[{"kind":"identifier","text":"TruvideoSdkCameraResult"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraAppDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"TruvideoSdkCameraAppDelegate","kind":"identifier"}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraappdelegate","title":"TruvideoSdkCameraAppDelegate","abstract":[{"type":"text","text":"Defines the application delegate for handling camera-related configurations."}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraAppDelegate","navigatorTitle":[{"text":"TruvideoSdkCameraAppDelegate","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/UIKit":{"url":"\/documentation\/truvideosdkcamera\/uikit","title":"UIKit","abstract":[],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/UIKit","kind":"symbol","role":"collection","type":"topic"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraLensFacing":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TruvideoSdkCameraLensFacing"}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameralensfacing","title":"TruvideoSdkCameraLensFacing","abstract":[{"type":"text","text":"Defines the camera lens direction used for capturing media."}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraLensFacing","navigatorTitle":[{"kind":"identifier","text":"TruvideoSdkCameraLensFacing"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraEventType":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"TruvideoSdkCameraEventType","kind":"identifier"}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraeventtype","title":"TruvideoSdkCameraEventType","abstract":[{"type":"text","text":"Defines the different types of events emitted by "},{"code":"TruvideoSdkCamera","type":"codeVoice"},{"text":".","type":"text"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraEventType","navigatorTitle":[{"text":"TruvideoSdkCameraEventType","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraScannerValidation":{"fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TruvideoSdkCameraScannerValidation"}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcamerascannervalidation","title":"TruvideoSdkCameraScannerValidation","abstract":[{"type":"text","text":"A function signature for validating scanned barcodes."}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraScannerValidation","navigatorTitle":[{"text":"TruvideoSdkCameraScannerValidation","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCamera":{"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TruvideoSdkCamera"},{"text":": ","kind":"text"},{"text":"TruvideoSdkCameraInterface","kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(pl)TruvideoSdkCameraInterface"},{"text":" & ","kind":"text"},{"text":"TruvideoSdkCameraEventsInterface","kind":"typeIdentifier","preciseIdentifier":"s:17TruvideoSdkCamera0abC15EventsInterfaceP"}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcamera","title":"TruvideoSdkCamera","abstract":[{"type":"text","text":"The global instance of "},{"type":"codeVoice","code":"TruvideoSdkCamera"},{"type":"text","text":", providing access to camera functionalities."}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCamera","kind":"symbol","role":"symbol","type":"topic"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkScannerCameraViewCallback":{"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TruvideoSdkScannerCameraViewCallback","kind":"identifier"}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkscannercameraviewcallback","title":"TruvideoSdkScannerCameraViewCallback","abstract":[{"type":"text","text":"A callback function that handles the result of a barcode or QR code scan."}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkScannerCameraViewCallback","navigatorTitle":[{"text":"TruvideoSdkScannerCameraViewCallback","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/GettingStartedWithCamera":{"url":"\/documentation\/truvideosdkcamera\/gettingstartedwithcamera","title":"Integrating the Camera into Your App","abstract":[{"text":"Learn how to integrate the Camera in ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"TruvideoSdkCamera"}]},{"type":"text","text":" for photo and video capturing."}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/GettingStartedWithCamera","kind":"article","role":"article","type":"topic"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/InstanceUniforms":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"InstanceUniforms"}],"url":"\/documentation\/truvideosdkcamera\/instanceuniforms","title":"InstanceUniforms","abstract":[],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/InstanceUniforms","navigatorTitle":[{"text":"InstanceUniforms","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/VertexAttributes":{"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"VertexAttributes","kind":"identifier"}],"url":"\/documentation\/truvideosdkcamera\/vertexattributes","title":"VertexAttributes","abstract":[],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/VertexAttributes","navigatorTitle":[{"text":"VertexAttributes","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraMedia":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TruvideoSdkCameraMedia","kind":"identifier"}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameramedia","title":"TruvideoSdkCameraMedia","abstract":[{"type":"text","text":"A class representing a media file captured by the Truvideo SDK camera."}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraMedia","navigatorTitle":[{"text":"TruvideoSdkCameraMedia","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraProvider":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TruvideoSdkCameraProvider","kind":"identifier"}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraprovider","title":"TruvideoSdkCameraProvider","abstract":[{"type":"text","text":"Provides a shared instance for accessing "},{"type":"codeVoice","code":"TruvideoSdkCamera"},{"text":" functionalities.","type":"text"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraProvider","navigatorTitle":[{"text":"TruvideoSdkCameraProvider","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/GettingStartedWithCamera","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/UsingARCamera","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/UsingCameraScanner"],"title":"Essentials"},{"identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkARCameraConfiguration","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraConfiguration","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraDevice","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraInformation","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraMedia","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraMediaMode","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraProvider","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraResolution","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraResult","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraScannerCode","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkScannerCameraConfiguration"],"title":"Classes"},{"title":"Protocols","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraAppDelegate","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraDelegate","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraInterface"]},{"identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/InstanceUniforms","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/MeasureUniforms","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/SharedUniforms"],"title":"Structures"},{"identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraVersionNumber","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraVersionString"],"title":"Variables"},{"title":"Enumeration Cases","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/kBufferIndexInstanceVertices","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/kTextureIndexCbCr","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/kTextureIndexColor","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/kTextureIndexRGB","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/kTextureIndexY"]},{"title":"Enumerations","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/BufferIndices","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TextureIndices","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraFlashMode","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraLensFacing","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraMediaType","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraOrientation","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraScannerCodeFormat","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/VertexAttributes"]}]},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":"BufferIndices","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1BufferIndices\/title"},{"op":"replace","value":[{"kind":"identifier","text":"BufferIndices"}],"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1BufferIndices\/fragments"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1kTextureIndexCbCr\/title","op":"replace","value":"kTextureIndexCbCr"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1kTextureIndexCbCr\/fragments","value":[{"kind":"identifier","text":"kTextureIndexCbCr"}]},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1kTextureIndexRGB\/title","op":"replace","value":"kTextureIndexRGB"},{"value":[{"text":"kTextureIndexRGB","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1kTextureIndexRGB\/fragments"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraFlashMode\/title","value":"TruvideoSdkCameraFlashMode","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraFlashMode\/fragments","value":[{"kind":"identifier","text":"TruvideoSdkCameraFlashMode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1kBufferIndexInstanceVertices\/title","value":"kBufferIndexInstanceVertices"},{"op":"replace","value":[{"text":"kBufferIndexInstanceVertices","kind":"identifier"}],"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1kBufferIndexInstanceVertices\/fragments"},{"value":"TextureIndices","op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TextureIndices\/title"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TextureIndices\/fragments","op":"replace","value":[{"text":"TextureIndices","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraInterface\/title","value":"TruvideoSdkCameraInterface","op":"replace"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraInterface\/fragments","value":[{"kind":"identifier","text":"TruvideoSdkCameraInterface"}],"op":"replace"},{"op":"replace","value":"TruvideoSdkARCameraConfiguration","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkARCameraConfiguration\/title"},{"value":[{"kind":"identifier","text":"TruvideoSdkARCameraConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkARCameraConfiguration\/fragments"},{"op":"replace","value":"TruvideoSdkScannerCameraConfiguration","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkScannerCameraConfiguration\/title"},{"value":[{"text":"TruvideoSdkScannerCameraConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkScannerCameraConfiguration\/fragments"},{"value":"kTextureIndexColor","op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1kTextureIndexColor\/title"},{"op":"replace","value":[{"text":"kTextureIndexColor","kind":"identifier"}],"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1kTextureIndexColor\/fragments"},{"op":"replace","value":"TruvideoSdkCameraMediaMode","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraMediaMode\/title"},{"value":[{"kind":"identifier","text":"TruvideoSdkCameraMediaMode"}],"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraMediaMode\/fragments","op":"replace"},{"op":"replace","value":"TruvideoSdkCameraInformation","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraInformation\/title"},{"op":"replace","value":[{"text":"TruvideoSdkCameraInformation","kind":"identifier"}],"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraInformation\/fragments"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraResolution\/title","value":"TruvideoSdkCameraResolution","op":"replace"},{"op":"replace","value":[{"text":"TruvideoSdkCameraResolution","kind":"identifier"}],"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraResolution\/fragments"},{"op":"replace","value":"TruvideoSdkCameraConfiguration","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraConfiguration\/title"},{"value":[{"kind":"identifier","text":"TruvideoSdkCameraConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraConfiguration\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraMediaType\/title","value":"TruvideoSdkCameraMediaType"},{"op":"replace","value":[{"kind":"identifier","text":"TruvideoSdkCameraMediaType"}],"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraMediaType\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraScannerCode\/title","value":"TruvideoSdkCameraScannerCode"},{"value":[{"text":"TruvideoSdkCameraScannerCode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraScannerCode\/fragments"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraOrientation\/title","value":"TruvideoSdkCameraOrientation","op":"replace"},{"value":[{"text":"TruvideoSdkCameraOrientation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraOrientation\/fragments"},{"value":"TruvideoSdkCameraScannerCodeFormat","op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraScannerCodeFormat\/title"},{"value":[{"kind":"identifier","text":"TruvideoSdkCameraScannerCodeFormat"}],"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraScannerCodeFormat\/fragments"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraDevice\/title","op":"replace","value":"TruvideoSdkCameraDevice"},{"value":[{"text":"TruvideoSdkCameraDevice","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraDevice\/fragments"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraDelegate\/title","value":"TruvideoSdkCameraDelegate","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraDelegate\/fragments","value":[{"kind":"identifier","text":"TruvideoSdkCameraDelegate"}]},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1MeasureUniforms\/title","op":"replace","value":"MeasureUniforms"},{"value":"SharedUniforms","op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1SharedUniforms\/title"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1kTextureIndexY\/title","op":"replace","value":"kTextureIndexY"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1kTextureIndexY\/fragments","op":"replace","value":[{"text":"kTextureIndexY","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraResult\/title","value":"TruvideoSdkCameraResult"},{"value":[{"kind":"identifier","text":"TruvideoSdkCameraResult"}],"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraResult\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraAppDelegate\/title","value":"TruvideoSdkCameraAppDelegate","op":"replace"},{"value":[{"text":"TruvideoSdkCameraAppDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraAppDelegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraLensFacing\/title","value":"TruvideoSdkCameraLensFacing"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraLensFacing\/fragments","value":[{"text":"TruvideoSdkCameraLensFacing","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1InstanceUniforms\/title","op":"replace","value":"InstanceUniforms"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1VertexAttributes\/title","op":"replace","value":"VertexAttributes"},{"value":[{"text":"VertexAttributes","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1VertexAttributes\/fragments"},{"op":"replace","value":"TruvideoSdkCameraMedia","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraMedia\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraMedia\/fragments","value":[{"text":"TruvideoSdkCameraMedia","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraProvider\/title","value":"TruvideoSdkCameraProvider"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraProvider\/fragments","value":[{"text":"TruvideoSdkCameraProvider","kind":"identifier"}]}]}]}