{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera"]]},"topicSections":[{"identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/InstanceUniforms\/init()","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/InstanceUniforms\/init(modelMatrix:)"],"title":"Initializers"},{"identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/InstanceUniforms\/modelMatrix"],"title":"Instance Properties"}],"kind":"symbol","variants":[{"paths":["\/documentation\/truvideosdkcamera\/instanceuniforms"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/truvideosdkcamera\/instanceuniforms"]}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/s8SendableP"],"title":"Conforms To","type":"conformsTo"}],"sections":[],"identifier":{"url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/InstanceUniforms","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"InstanceUniforms"}]}]}],"metadata":{"symbolKind":"struct","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"InstanceUniforms","kind":"identifier"}],"modules":[{"name":"TruvideoSdkCamera"}],"roleHeading":"Structure","title":"InstanceUniforms","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"InstanceUniforms"}],"externalID":"c:@SA@InstanceUniforms"},"references":{"doc://com.truvideo.TruvideoSdkCamera/s8SendableP":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/s8SendableP","type":"unresolvable","title":"Swift.Sendable"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/InstanceUniforms":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"InstanceUniforms"}],"url":"\/documentation\/truvideosdkcamera\/instanceuniforms","title":"InstanceUniforms","abstract":[],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/InstanceUniforms","navigatorTitle":[{"text":"InstanceUniforms","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/InstanceUniforms/init(modelMatrix:)":{"kind":"symbol","title":"init(modelMatrix:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"modelMatrix","kind":"externalParam"},{"kind":"text","text":": "},{"text":"matrix_float4x4","kind":"typeIdentifier","preciseIdentifier":"c:@T@matrix_float4x4"},{"text":")","kind":"text"}],"type":"topic","url":"\/documentation\/truvideosdkcamera\/instanceuniforms\/init(modelmatrix:)","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/InstanceUniforms\/init(modelMatrix:)","role":"symbol","abstract":[]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"kind":"symbol","abstract":[{"type":"text","text":"Store and capture photos and videos using a fully integrated camera system."}],"url":"\/documentation\/truvideosdkcamera","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","title":"TruvideoSdkCamera","type":"topic","role":"collection"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/InstanceUniforms/init()":{"abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/InstanceUniforms\/init()","kind":"symbol","url":"\/documentation\/truvideosdkcamera\/instanceuniforms\/init()","title":"init()","type":"topic","role":"symbol"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/InstanceUniforms/modelMatrix":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"modelMatrix","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@matrix_float4x4","text":"matrix_float4x4","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/InstanceUniforms\/modelMatrix","type":"topic","title":"modelMatrix","navigatorTitle":[{"kind":"identifier","text":"modelMatrix"}],"abstract":[],"kind":"symbol","url":"\/documentation\/truvideosdkcamera\/instanceuniforms\/modelmatrix","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Structure","path":"\/metadata\/roleHeading"},{"op":"replace","value":"InstanceUniforms","path":"\/metadata\/title"},{"value":"struct","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"InstanceUniforms","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/InstanceUniforms\/modelMatrix"],"title":"Instance Properties"}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"typedef","kind":"keyword"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"InstanceUniforms","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1InstanceUniforms\/title","value":"InstanceUniforms"},{"value":"modelMatrix","op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1InstanceUniforms~1modelMatrix\/title"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1InstanceUniforms~1modelMatrix\/fragments","value":[{"text":"modelMatrix","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}