{"variants":[{"paths":["\/documentation\/truvideosdkcamera\/kbufferindexinstancevertices"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/truvideosdkcamera\/kbufferindexinstancevertices"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/kBufferIndexInstanceVertices"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"kBufferIndexInstanceVertices","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@BufferIndices","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/BufferIndices","text":"BufferIndices"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"metadata":{"roleHeading":"Global Variable","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"kBufferIndexInstanceVertices"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@BufferIndices","text":"BufferIndices","kind":"typeIdentifier"}],"title":"kBufferIndexInstanceVertices","modules":[{"name":"TruvideoSdkCamera"}],"role":"symbol","symbolKind":"var","externalID":"c:@E@BufferIndices@kBufferIndexInstanceVertices","navigatorTitle":[{"text":"kBufferIndexInstanceVertices","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera"]]},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/kBufferIndexInstanceVertices":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"kBufferIndexInstanceVertices"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BufferIndices","preciseIdentifier":"c:@E@BufferIndices"}],"url":"\/documentation\/truvideosdkcamera\/kbufferindexinstancevertices","title":"kBufferIndexInstanceVertices","abstract":[],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/kBufferIndexInstanceVertices","navigatorTitle":[{"text":"kBufferIndexInstanceVertices","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"kind":"symbol","abstract":[{"type":"text","text":"Store and capture photos and videos using a fully integrated camera system."}],"url":"\/documentation\/truvideosdkcamera","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","title":"TruvideoSdkCamera","type":"topic","role":"collection"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/BufferIndices":{"role":"symbol","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/BufferIndices","navigatorTitle":[{"text":"BufferIndices","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/truvideosdkcamera\/bufferindices","abstract":[],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"BufferIndices"}],"title":"BufferIndices"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"kBufferIndexInstanceVertices","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","value":[{"text":"kBufferIndexInstanceVertices","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"kBufferIndexInstanceVertices","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","value":"kBufferIndexInstanceVertices","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1kBufferIndexInstanceVertices\/title"},{"value":[{"text":"kBufferIndexInstanceVertices","kind":"identifier"}],"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1kBufferIndexInstanceVertices\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1BufferIndices\/title","value":"BufferIndices"},{"op":"replace","value":[{"text":"BufferIndices","kind":"identifier"}],"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1BufferIndices\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}