{"hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/BufferIndices"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/kBufferIndexMeshGenerics"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"kBufferIndexMeshGenerics"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@BufferIndices","kind":"typeIdentifier","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/BufferIndices","text":"BufferIndices"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"metadata":{"roleHeading":"Global Variable","externalID":"c:@E@BufferIndices@kBufferIndexMeshGenerics","symbolKind":"var","navigatorTitle":[{"text":"kBufferIndexMeshGenerics","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"kBufferIndexMeshGenerics"},{"kind":"text","text":": "},{"text":"BufferIndices","preciseIdentifier":"c:@E@BufferIndices","kind":"typeIdentifier"}],"title":"kBufferIndexMeshGenerics","role":"symbol","modules":[{"name":"TruvideoSdkCamera"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/truvideosdkcamera\/kbufferindexmeshgenerics"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/truvideosdkcamera\/kbufferindexmeshgenerics"]}],"references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/kBufferIndexMeshGenerics":{"kind":"symbol","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/kBufferIndexMeshGenerics","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"kBufferIndexMeshGenerics","kind":"identifier"},{"text":": ","kind":"text"},{"text":"BufferIndices","kind":"typeIdentifier","preciseIdentifier":"c:@E@BufferIndices"}],"title":"kBufferIndexMeshGenerics","abstract":[],"role":"symbol","url":"\/documentation\/truvideosdkcamera\/kbufferindexmeshgenerics","navigatorTitle":[{"text":"kBufferIndexMeshGenerics","kind":"identifier"}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"kind":"symbol","abstract":[{"type":"text","text":"Store and capture photos and videos using a fully integrated camera system."}],"url":"\/documentation\/truvideosdkcamera","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","title":"TruvideoSdkCamera","type":"topic","role":"collection"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/BufferIndices":{"role":"symbol","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/BufferIndices","navigatorTitle":[{"text":"BufferIndices","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/truvideosdkcamera\/bufferindices","abstract":[],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"BufferIndices"}],"title":"BufferIndices"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"kBufferIndexMeshGenerics"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"kind":"identifier","text":"kBufferIndexMeshGenerics"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"kBufferIndexMeshGenerics","kind":"identifier"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1kBufferIndexMeshGenerics\/title","value":"kBufferIndexMeshGenerics"},{"op":"replace","value":[{"text":"kBufferIndexMeshGenerics","kind":"identifier"}],"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1kBufferIndexMeshGenerics\/fragments"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1BufferIndices\/title","value":"BufferIndices","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1BufferIndices\/fragments","value":[{"kind":"identifier","text":"BufferIndices"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}