{"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"metadata":{"title":"kBufferIndexSharedUniforms","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"kBufferIndexSharedUniforms"},{"text":": ","kind":"text"},{"text":"BufferIndices","kind":"typeIdentifier","preciseIdentifier":"c:@E@BufferIndices"}],"modules":[{"name":"TruvideoSdkCamera"}],"navigatorTitle":[{"text":"kBufferIndexSharedUniforms","kind":"identifier"}],"role":"symbol","symbolKind":"var","roleHeading":"Global Variable","externalID":"c:@E@BufferIndices@kBufferIndexSharedUniforms"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"kBufferIndexSharedUniforms"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/BufferIndices","preciseIdentifier":"c:@E@BufferIndices","kind":"typeIdentifier","text":"BufferIndices"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/BufferIndices"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/kBufferIndexSharedUniforms"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/truvideosdkcamera\/kbufferindexshareduniforms"]},{"paths":["\/documentation\/truvideosdkcamera\/kbufferindexshareduniforms"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/kBufferIndexSharedUniforms":{"kind":"symbol","title":"kBufferIndexSharedUniforms","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"kBufferIndexSharedUniforms","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@BufferIndices","text":"BufferIndices"}],"type":"topic","navigatorTitle":[{"text":"kBufferIndexSharedUniforms","kind":"identifier"}],"url":"\/documentation\/truvideosdkcamera\/kbufferindexshareduniforms","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/kBufferIndexSharedUniforms","role":"symbol","abstract":[]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/BufferIndices":{"role":"symbol","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/BufferIndices","navigatorTitle":[{"text":"BufferIndices","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/truvideosdkcamera\/bufferindices","abstract":[],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"BufferIndices"}],"title":"BufferIndices"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"kind":"symbol","abstract":[{"type":"text","text":"Store and capture photos and videos using a fully integrated camera system."}],"url":"\/documentation\/truvideosdkcamera","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","title":"TruvideoSdkCamera","type":"topic","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"kBufferIndexSharedUniforms","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"value":[{"text":"kBufferIndexSharedUniforms","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"kBufferIndexSharedUniforms","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"kBufferIndexSharedUniforms","op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1kBufferIndexSharedUniforms\/title"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1kBufferIndexSharedUniforms\/fragments","value":[{"text":"kBufferIndexSharedUniforms","kind":"identifier"}],"op":"replace"},{"value":"BufferIndices","op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1BufferIndices\/title"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1BufferIndices\/fragments","op":"replace","value":[{"kind":"identifier","text":"BufferIndices"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}