{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/truvideosdkcamera\/kvertexattributeposition"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/truvideosdkcamera\/kvertexattributeposition"]}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/VertexAttributes"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/kVertexAttributePosition"},"metadata":{"title":"kVertexAttributePosition","modules":[{"name":"TruvideoSdkCamera"}],"roleHeading":"Global Variable","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kVertexAttributePosition","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@VertexAttributes","text":"VertexAttributes","kind":"typeIdentifier"}],"externalID":"c:@E@VertexAttributes@kVertexAttributePosition","symbolKind":"var","navigatorTitle":[{"text":"kVertexAttributePosition","kind":"identifier"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"kVertexAttributePosition"},{"kind":"text","text":": "},{"text":"VertexAttributes","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/VertexAttributes","kind":"typeIdentifier","preciseIdentifier":"c:@E@VertexAttributes"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}]}]}],"references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/VertexAttributes":{"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"VertexAttributes","kind":"identifier"}],"url":"\/documentation\/truvideosdkcamera\/vertexattributes","title":"VertexAttributes","abstract":[],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/VertexAttributes","navigatorTitle":[{"text":"VertexAttributes","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/kVertexAttributePosition":{"abstract":[],"title":"kVertexAttributePosition","url":"\/documentation\/truvideosdkcamera\/kvertexattributeposition","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"kVertexAttributePosition","kind":"identifier"},{"kind":"text","text":": "},{"text":"VertexAttributes","preciseIdentifier":"c:@E@VertexAttributes","kind":"typeIdentifier"}],"kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"kVertexAttributePosition"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/kVertexAttributePosition"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"kind":"symbol","abstract":[{"type":"text","text":"Store and capture photos and videos using a fully integrated camera system."}],"url":"\/documentation\/truvideosdkcamera","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","title":"TruvideoSdkCamera","type":"topic","role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"kVertexAttributePosition","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"kVertexAttributePosition"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"kVertexAttributePosition","kind":"identifier"}]}],"kind":"declarations"}},{"op":"replace","value":"VertexAttributes","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1VertexAttributes\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1VertexAttributes\/fragments","value":[{"text":"VertexAttributes","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1kVertexAttributePosition\/title","value":"kVertexAttributePosition","op":"replace"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1kVertexAttributePosition\/fragments","value":[{"text":"kVertexAttributePosition","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}