{"metadata":{"roleHeading":"Global Variable","externalID":"c:@E@VertexAttributes@kVertexAttributeTexcoord","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kVertexAttributeTexcoord"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"VertexAttributes","preciseIdentifier":"c:@E@VertexAttributes"}],"symbolKind":"var","modules":[{"name":"TruvideoSdkCamera"}],"title":"kVertexAttributeTexcoord","role":"symbol","navigatorTitle":[{"text":"kVertexAttributeTexcoord","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/VertexAttributes"]]},"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kVertexAttributeTexcoord","kind":"identifier"},{"text":": ","kind":"text"},{"text":"VertexAttributes","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/VertexAttributes","kind":"typeIdentifier","preciseIdentifier":"c:@E@VertexAttributes"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/truvideosdkcamera\/kvertexattributetexcoord"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/truvideosdkcamera\/kvertexattributetexcoord"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/kVertexAttributeTexcoord"},"references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/kVertexAttributeTexcoord":{"abstract":[],"title":"kVertexAttributeTexcoord","url":"\/documentation\/truvideosdkcamera\/kvertexattributetexcoord","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"kVertexAttributeTexcoord","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@VertexAttributes","text":"VertexAttributes","kind":"typeIdentifier"}],"kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"text":"kVertexAttributeTexcoord","kind":"identifier"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/kVertexAttributeTexcoord"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"kind":"symbol","abstract":[{"type":"text","text":"Store and capture photos and videos using a fully integrated camera system."}],"url":"\/documentation\/truvideosdkcamera","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","title":"TruvideoSdkCamera","type":"topic","role":"collection"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/VertexAttributes":{"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"VertexAttributes","kind":"identifier"}],"url":"\/documentation\/truvideosdkcamera\/vertexattributes","title":"VertexAttributes","abstract":[],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/VertexAttributes","navigatorTitle":[{"text":"VertexAttributes","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"kVertexAttributeTexcoord"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"kVertexAttributeTexcoord","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"kVertexAttributeTexcoord","kind":"identifier"}],"languages":["occ"]}]}},{"value":"kVertexAttributeTexcoord","op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1kVertexAttributeTexcoord\/title"},{"value":[{"kind":"identifier","text":"kVertexAttributeTexcoord"}],"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1kVertexAttributeTexcoord\/fragments"},{"op":"replace","value":"VertexAttributes","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1VertexAttributes\/title"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1VertexAttributes\/fragments","value":[{"text":"VertexAttributes","kind":"identifier"}],"op":"replace"}]}]}