{"variants":[{"paths":["\/documentation\/truvideosdkcamera\/kvertexattributecolor"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/truvideosdkcamera\/kvertexattributecolor"]}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"roleHeading":"Global Variable","role":"symbol","title":"kVertexAttributeColor","modules":[{"name":"TruvideoSdkCamera"}],"externalID":"c:@E@VertexAttributes@kVertexAttributeColor","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"kVertexAttributeColor","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@VertexAttributes","text":"VertexAttributes","kind":"typeIdentifier"}],"symbolKind":"var","navigatorTitle":[{"text":"kVertexAttributeColor","kind":"identifier"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/VertexAttributes"]]},"identifier":{"url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/kVertexAttributeColor","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"kVertexAttributeColor","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@VertexAttributes","text":"VertexAttributes","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/VertexAttributes","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/kVertexAttributeColor":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/kVertexAttributeColor","abstract":[],"role":"symbol","title":"kVertexAttributeColor","kind":"symbol","url":"\/documentation\/truvideosdkcamera\/kvertexattributecolor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"kVertexAttributeColor","kind":"identifier"},{"kind":"text","text":": "},{"text":"VertexAttributes","preciseIdentifier":"c:@E@VertexAttributes","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"kVertexAttributeColor","kind":"identifier"}],"type":"topic"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"kind":"symbol","abstract":[{"type":"text","text":"Store and capture photos and videos using a fully integrated camera system."}],"url":"\/documentation\/truvideosdkcamera","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","title":"TruvideoSdkCamera","type":"topic","role":"collection"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/VertexAttributes":{"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"VertexAttributes","kind":"identifier"}],"url":"\/documentation\/truvideosdkcamera\/vertexattributes","title":"VertexAttributes","abstract":[],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/VertexAttributes","navigatorTitle":[{"text":"VertexAttributes","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"value":"kVertexAttributeColor","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"kVertexAttributeColor"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"kVertexAttributeColor","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1kVertexAttributeColor\/title","value":"kVertexAttributeColor","op":"replace"},{"value":[{"text":"kVertexAttributeColor","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1kVertexAttributeColor\/fragments"},{"value":"VertexAttributes","op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1VertexAttributes\/title"},{"value":[{"text":"VertexAttributes","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1VertexAttributes\/fragments"}]}]}