{"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/SharedUniforms\/init()","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/SharedUniforms\/init(projectionMatrix:viewMatrix:ambientLightColor:directionalLightDirection:directionalLightColor:materialShininess:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/SharedUniforms\/ambientLightColor","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/SharedUniforms\/directionalLightColor","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/SharedUniforms\/directionalLightDirection","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/SharedUniforms\/materialShininess","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/SharedUniforms\/projectionMatrix","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/SharedUniforms\/viewMatrix"]}],"metadata":{"roleHeading":"Structure","externalID":"c:@SA@SharedUniforms","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SharedUniforms","kind":"identifier"}],"symbolKind":"struct","modules":[{"name":"TruvideoSdkCamera"}],"title":"SharedUniforms","role":"symbol","navigatorTitle":[{"text":"SharedUniforms","kind":"identifier"}]},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SharedUniforms","kind":"identifier"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/truvideosdkcamera\/shareduniforms"]},{"paths":["\/documentation\/truvideosdkcamera\/shareduniforms"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"relationshipsSections":[{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/s8SendableP"],"kind":"relationships"}],"identifier":{"url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/SharedUniforms","interfaceLanguage":"swift"},"references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"kind":"symbol","abstract":[{"type":"text","text":"Store and capture photos and videos using a fully integrated camera system."}],"url":"\/documentation\/truvideosdkcamera","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","title":"TruvideoSdkCamera","type":"topic","role":"collection"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/SharedUniforms/viewMatrix":{"kind":"symbol","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/SharedUniforms\/viewMatrix","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewMatrix"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"matrix_float4x4","preciseIdentifier":"c:@T@matrix_float4x4"}],"title":"viewMatrix","abstract":[],"role":"symbol","url":"\/documentation\/truvideosdkcamera\/shareduniforms\/viewmatrix","navigatorTitle":[{"kind":"identifier","text":"viewMatrix"}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/SharedUniforms/directionalLightDirection":{"kind":"symbol","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/SharedUniforms\/directionalLightDirection","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"directionalLightDirection","kind":"identifier"},{"kind":"text","text":": "},{"text":"vector_float3","preciseIdentifier":"c:@T@vector_float3","kind":"typeIdentifier"}],"title":"directionalLightDirection","abstract":[],"role":"symbol","url":"\/documentation\/truvideosdkcamera\/shareduniforms\/directionallightdirection","navigatorTitle":[{"text":"directionalLightDirection","kind":"identifier"}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/SharedUniforms/ambientLightColor":{"abstract":[],"title":"ambientLightColor","url":"\/documentation\/truvideosdkcamera\/shareduniforms\/ambientlightcolor","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"ambientLightColor","kind":"identifier"},{"kind":"text","text":": "},{"text":"vector_float3","preciseIdentifier":"c:@T@vector_float3","kind":"typeIdentifier"}],"kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"text":"ambientLightColor","kind":"identifier"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/SharedUniforms\/ambientLightColor"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/SharedUniforms/projectionMatrix":{"abstract":[],"title":"projectionMatrix","url":"\/documentation\/truvideosdkcamera\/shareduniforms\/projectionmatrix","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"projectionMatrix"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@matrix_float4x4","text":"matrix_float4x4"}],"kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"text":"projectionMatrix","kind":"identifier"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/SharedUniforms\/projectionMatrix"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/SharedUniforms/init()":{"abstract":[],"title":"init()","url":"\/documentation\/truvideosdkcamera\/shareduniforms\/init()","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"()"}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/SharedUniforms\/init()"},"doc://com.truvideo.TruvideoSdkCamera/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/s8SendableP"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/SharedUniforms":{"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SharedUniforms"}],"url":"\/documentation\/truvideosdkcamera\/shareduniforms","title":"SharedUniforms","abstract":[],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/SharedUniforms","navigatorTitle":[{"text":"SharedUniforms","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/SharedUniforms/init(projectionMatrix:viewMatrix:ambientLightColor:directionalLightDirection:directionalLightColor:materialShininess:)":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/SharedUniforms\/init(projectionMatrix:viewMatrix:ambientLightColor:directionalLightDirection:directionalLightColor:materialShininess:)","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"projectionMatrix","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@matrix_float4x4","text":"matrix_float4x4","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"viewMatrix","kind":"externalParam"},{"kind":"text","text":": "},{"text":"matrix_float4x4","kind":"typeIdentifier","preciseIdentifier":"c:@T@matrix_float4x4"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"ambientLightColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@vector_float3","text":"vector_float3"},{"kind":"text","text":", "},{"text":"directionalLightDirection","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@vector_float3","kind":"typeIdentifier","text":"vector_float3"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"directionalLightColor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"vector_float3","preciseIdentifier":"c:@T@vector_float3"},{"text":", ","kind":"text"},{"text":"materialShininess","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"text":")","kind":"text"}],"url":"\/documentation\/truvideosdkcamera\/shareduniforms\/init(projectionmatrix:viewmatrix:ambientlightcolor:directionallightdirection:directionallightcolor:materialshininess:)","abstract":[],"title":"init(projectionMatrix:viewMatrix:ambientLightColor:directionalLightDirection:directionalLightColor:materialShininess:)"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/SharedUniforms/directionalLightColor":{"abstract":[],"url":"\/documentation\/truvideosdkcamera\/shareduniforms\/directionallightcolor","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/SharedUniforms\/directionalLightColor","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"directionalLightColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"vector_float3","kind":"typeIdentifier","preciseIdentifier":"c:@T@vector_float3"}],"title":"directionalLightColor","navigatorTitle":[{"text":"directionalLightColor","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/SharedUniforms/materialShininess":{"abstract":[],"title":"materialShininess","url":"\/documentation\/truvideosdkcamera\/shareduniforms\/materialshininess","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"materialShininess","kind":"identifier"},{"kind":"text","text":": "},{"text":"Float","preciseIdentifier":"s:Sf","kind":"typeIdentifier"}],"kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"text":"materialShininess","kind":"identifier"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/SharedUniforms\/materialShininess"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Structure","op":"replace"},{"value":"SharedUniforms","op":"replace","path":"\/metadata\/title"},{"value":"struct","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SharedUniforms"}]},{"path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/SharedUniforms\/ambientLightColor","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/SharedUniforms\/directionalLightColor","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/SharedUniforms\/directionalLightDirection","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/SharedUniforms\/materialShininess","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/SharedUniforms\/projectionMatrix","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/SharedUniforms\/viewMatrix"]}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"typedef","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"SharedUniforms","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1SharedUniforms~1viewMatrix\/title","value":"viewMatrix","op":"replace"},{"value":[{"text":"viewMatrix","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1SharedUniforms~1viewMatrix\/fragments"},{"value":"directionalLightDirection","op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1SharedUniforms~1directionalLightDirection\/title"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1SharedUniforms~1directionalLightDirection\/fragments","op":"replace","value":[{"kind":"identifier","text":"directionalLightDirection"}]},{"op":"replace","value":"ambientLightColor","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1SharedUniforms~1ambientLightColor\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1SharedUniforms~1ambientLightColor\/fragments","value":[{"text":"ambientLightColor","kind":"identifier"}]},{"value":"projectionMatrix","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1SharedUniforms~1projectionMatrix\/title","op":"replace"},{"value":[{"kind":"identifier","text":"projectionMatrix"}],"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1SharedUniforms~1projectionMatrix\/fragments"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1SharedUniforms\/title","value":"SharedUniforms","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1SharedUniforms~1directionalLightColor\/title","value":"directionalLightColor"},{"value":[{"text":"directionalLightColor","kind":"identifier"}],"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1SharedUniforms~1directionalLightColor\/fragments","op":"replace"},{"value":"materialShininess","op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1SharedUniforms~1materialShininess\/title"},{"op":"replace","value":[{"text":"materialShininess","kind":"identifier"}],"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1SharedUniforms~1materialShininess\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}