{"variants":[{"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcameraflashmode"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcameraflashmode"]}],"hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"TruvideoSdkCameraFlashMode","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"level":2,"text":"Overview","anchor":"overview","type":"heading"},{"inlineContent":[{"text":"This enum specifies whether the camera ","type":"text"},{"inlineContent":[{"text":"flash is enabled or disabled","type":"text"}],"type":"strong"},{"type":"text","text":"."}],"type":"paragraph"},{"text":"Available Values","type":"heading","anchor":"Available-Values","level":2},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraFlashMode\/off","type":"reference","isActive":true},{"type":"text","text":": "},{"inlineContent":[{"type":"text","text":"Flash is disabled"}],"type":"strong"},{"text":".","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"reference","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraFlashMode\/on","isActive":true},{"text":": ","type":"text"},{"inlineContent":[{"text":"Flash is always enabled","type":"text"}],"type":"strong"},{"type":"text","text":"."}],"type":"paragraph"}]}],"type":"unorderedList"},{"level":2,"anchor":"Example-Usage","type":"heading","text":"Example Usage"},{"syntax":"swift","code":["let cameraConfig = TruvideoSdkCameraConfiguration(","    flashMode: .on",")"],"type":"codeListing"}]}],"metadata":{"title":"TruvideoSdkCameraFlashMode","modules":[{"name":"TruvideoSdkCamera"}],"roleHeading":"Enumeration","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"TruvideoSdkCameraFlashMode","kind":"identifier"}],"externalID":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraFlashMode","symbolKind":"enum","navigatorTitle":[{"text":"TruvideoSdkCameraFlashMode","kind":"identifier"}]},"identifier":{"url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraFlashMode","interfaceLanguage":"swift"},"relationshipsSections":[{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/Se","doc:\/\/com.truvideo.TruvideoSdkCamera\/SE","doc:\/\/com.truvideo.TruvideoSdkCamera\/SQ","doc:\/\/com.truvideo.TruvideoSdkCamera\/SH","doc:\/\/com.truvideo.TruvideoSdkCamera\/SY"],"kind":"relationships"}],"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraFlashMode\/off","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraFlashMode\/on"]},{"title":"Initializers","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraFlashMode\/init(from:)-2875k","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraFlashMode\/init(rawValue:)"]},{"identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraFlashMode\/rawValue-swift.property"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraFlashMode\/encode(to:)"]},{"title":"Type Aliases","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraFlashMode\/RawValue-swift.typealias"]},{"identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraFlashMode\/Equatable-Implementations","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraFlashMode\/RawRepresentable-Implementations"],"title":"Default Implementations","generated":true}],"abstract":[{"type":"text","text":"Defines the flash mode settings for the camera."}],"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraFlashMode/on":{"navigatorTitle":[{"text":"TruvideoSdkCameraFlashModeOn","kind":"identifier"}],"abstract":[{"text":"Flash is always enabled.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"on"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraFlashMode\/on","kind":"symbol","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraflashmode\/on","title":"TruvideoSdkCameraFlashMode.on","type":"topic","role":"symbol"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraFlashMode/Equatable-Implementations":{"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraflashmode\/equatable-implementations","type":"topic","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraFlashMode\/Equatable-Implementations","kind":"article","title":"Equatable Implementations","role":"collectionGroup","abstract":[]},"doc://com.truvideo.TruvideoSdkCamera/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/SQ","title":"Swift.Equatable"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraFlashMode/encode(to:)":{"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraflashmode\/encode(to:)","abstract":[{"text":"Encodes this value into the given encoder.","type":"text"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraFlashMode\/encode(to:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"encode","kind":"identifier"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"keyword","text":"any"},{"text":" ","kind":"text"},{"text":"Encoder","preciseIdentifier":"s:s7EncoderP","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"title":"encode(to:)","role":"symbol","type":"topic","kind":"symbol"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraFlashMode/off":{"abstract":[{"text":"Flash is disabled.","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"TruvideoSdkCameraFlashModeOff"}],"title":"TruvideoSdkCameraFlashMode.off","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"off","kind":"identifier"}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraflashmode\/off","role":"symbol","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraFlashMode\/off","kind":"symbol"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraFlashMode":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TruvideoSdkCameraFlashMode"}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraflashmode","title":"TruvideoSdkCameraFlashMode","abstract":[{"type":"text","text":"Defines the flash mode settings for the camera."}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraFlashMode","navigatorTitle":[{"text":"TruvideoSdkCameraFlashMode","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraFlashMode/RawValue-swift.typealias":{"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraflashmode\/rawvalue-swift.typealias","abstract":[{"type":"text","text":"The raw type that can be used to represent all values of the conforming"},{"type":"text","text":" "},{"type":"text","text":"type."}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraFlashMode\/RawValue-swift.typealias","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"RawValue","kind":"identifier"}],"title":"TruvideoSdkCameraFlashMode.RawValue","navigatorTitle":[{"kind":"identifier","text":"RawValue"}],"role":"symbol","type":"topic","kind":"symbol"},"doc://com.truvideo.TruvideoSdkCamera/Se":{"type":"unresolvable","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/Se","title":"Swift.Decodable"},"doc://com.truvideo.TruvideoSdkCamera/SY":{"type":"unresolvable","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/SY","title":"Swift.RawRepresentable"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraFlashMode/init(from:)-2875k":{"abstract":[{"type":"text","text":"Creates a new instance by decoding from the given decoder."}],"title":"init(from:)","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraflashmode\/init(from:)-2875k","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"kind":"text","text":": "},{"text":"any","kind":"keyword"},{"kind":"text","text":" "},{"text":"Decoder","kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraFlashMode\/init(from:)-2875k"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraFlashMode/init(rawValue:)":{"abstract":[{"text":"Creates a new instance with the specified raw value.","type":"text"}],"title":"init(rawValue:)","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraflashmode\/init(rawvalue:)","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:17TruvideoSdkCamera0abC9FlashModeO8RawValuea","text":"RawValue"},{"text":")","kind":"text"}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraFlashMode\/init(rawValue:)"},"doc://com.truvideo.TruvideoSdkCamera/SE":{"title":"Swift.Encodable","type":"unresolvable","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/SE"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"kind":"symbol","abstract":[{"type":"text","text":"Store and capture photos and videos using a fully integrated camera system."}],"url":"\/documentation\/truvideosdkcamera","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","title":"TruvideoSdkCamera","type":"topic","role":"collection"},"doc://com.truvideo.TruvideoSdkCamera/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/SH"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraFlashMode/RawRepresentable-Implementations":{"abstract":[],"title":"RawRepresentable Implementations","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraflashmode\/rawrepresentable-implementations","kind":"article","role":"collectionGroup","type":"topic","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraFlashMode\/RawRepresentable-Implementations"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraFlashMode/rawValue-swift.property":{"abstract":[{"type":"text","text":"The corresponding value of the raw type."}],"title":"rawValue","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraflashmode\/rawvalue-swift.property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rawValue"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"RawValue","preciseIdentifier":"s:17TruvideoSdkCamera0abC9FlashModeO8RawValuea"}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraFlashMode\/rawValue-swift.property"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"TruvideoSdkCameraFlashMode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"TruvideoSdkCameraFlashMode","kind":"identifier"}]},{"value":[{"text":"TruvideoSdkCameraFlashMode","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraFlashMode\/off","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraFlashMode\/on"],"title":"Enumeration Cases"}]},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TruvideoSdkCameraFlashMode"},{"text":": ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"value":"TruvideoSdkCameraFlashModeOn","op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraFlashMode~1on\/title"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraFlashMode~1on\/fragments","op":"replace","value":[{"kind":"identifier","text":"TruvideoSdkCameraFlashModeOn"}]},{"value":"TruvideoSdkCameraFlashModeOff","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraFlashMode~1off\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraFlashMode~1off\/fragments","op":"replace","value":[{"kind":"identifier","text":"TruvideoSdkCameraFlashModeOff"}]},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraFlashMode\/title","value":"TruvideoSdkCameraFlashMode"},{"value":[{"text":"TruvideoSdkCameraFlashMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraFlashMode\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}