{"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/Se","doc:\/\/com.truvideo.TruvideoSdkCamera\/SE","doc:\/\/com.truvideo.TruvideoSdkCamera\/SQ","doc:\/\/com.truvideo.TruvideoSdkCamera\/SH","doc:\/\/com.truvideo.TruvideoSdkCamera\/SY"],"type":"conformsTo","title":"Conforms To"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraMediaType\/clip","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraMediaType\/photo"],"title":"Enumeration Cases"},{"identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraMediaType\/init(from:)-q0ub","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraMediaType\/init(rawValue:)"],"title":"Initializers"},{"identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraMediaType\/rawValue-swift.property"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraMediaType\/encode(to:)"],"title":"Instance Methods"},{"title":"Type Aliases","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraMediaType\/RawValue-swift.typealias"]},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraMediaType\/Equatable-Implementations","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraMediaType\/RawRepresentable-Implementations"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"TruvideoSdkCameraMediaType","kind":"identifier"}],"languages":["swift"]}]},{"kind":"content","content":[{"text":"Overview","type":"heading","anchor":"overview","level":2},{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"TruvideoSdkCameraMediaType"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Codable"},{"type":"text","text":" and "},{"code":"RawRepresentable","type":"codeVoice"},{"text":", allowing it to be","type":"text"},{"type":"text","text":" "},{"text":"encoded and decoded from JSON. The raw values are stored as ","type":"text"},{"type":"codeVoice","code":"String"},{"type":"text","text":" representations."}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcameramediatype"]},{"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcameramediatype"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraMediaType"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera"]]},"metadata":{"roleHeading":"Enumeration","externalID":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraMediaType","symbolKind":"enum","navigatorTitle":[{"text":"TruvideoSdkCameraMediaType","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"TruvideoSdkCameraMediaType","kind":"identifier"}],"title":"TruvideoSdkCameraMediaType","role":"symbol","modules":[{"name":"TruvideoSdkCamera"}]},"abstract":[{"text":"An enumeration representing the different media types supported by the Truvideo SDK camera.","type":"text"}],"references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraMediaType/photo":{"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameramediatype\/photo","abstract":[{"text":"The media type representing a captured photo.","type":"text"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraMediaType\/photo","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"photo"}],"title":"TruvideoSdkCameraMediaType.photo","navigatorTitle":[{"kind":"identifier","text":"TruvideoSdkCameraMediaTypePhoto"}],"role":"symbol","type":"topic","kind":"symbol"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"kind":"symbol","abstract":[{"type":"text","text":"Store and capture photos and videos using a fully integrated camera system."}],"url":"\/documentation\/truvideosdkcamera","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","title":"TruvideoSdkCamera","type":"topic","role":"collection"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraMediaType/RawRepresentable-Implementations":{"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameramediatype\/rawrepresentable-implementations","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraMediaType\/RawRepresentable-Implementations","title":"RawRepresentable Implementations","role":"collectionGroup","abstract":[],"type":"topic","kind":"article"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraMediaType/init(from:)-q0ub":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraMediaType\/init(from:)-q0ub","kind":"symbol","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"text":": ","kind":"text"},{"text":"any","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP","text":"Decoder"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"title":"init(from:)","abstract":[{"text":"Creates a new instance by decoding from the given decoder.","type":"text"}],"role":"symbol","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameramediatype\/init(from:)-q0ub"},"doc://com.truvideo.TruvideoSdkCamera/SY":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://com.truvideo.TruvideoSdkCamera/SE":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/SE","title":"Swift.Encodable","type":"unresolvable"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraMediaType/rawValue-swift.property":{"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameramediatype\/rawvalue-swift.property","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraMediaType\/rawValue-swift.property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"rawValue","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:17TruvideoSdkCamera0abC9MediaTypeO8RawValuea","kind":"typeIdentifier","text":"RawValue"}],"title":"rawValue","kind":"symbol","abstract":[{"text":"The string representation of each media type.","type":"text"}],"role":"symbol","type":"topic"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraMediaType":{"title":"TruvideoSdkCameraMediaType","role":"symbol","abstract":[{"type":"text","text":"An enumeration representing the different media types supported by the Truvideo SDK camera."}],"type":"topic","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"TruvideoSdkCameraMediaType","kind":"identifier"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraMediaType","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameramediatype","navigatorTitle":[{"kind":"identifier","text":"TruvideoSdkCameraMediaType"}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraMediaType/Equatable-Implementations":{"kind":"article","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraMediaType\/Equatable-Implementations","type":"topic","title":"Equatable Implementations","abstract":[],"role":"collectionGroup","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameramediatype\/equatable-implementations"},"doc://com.truvideo.TruvideoSdkCamera/SH":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.truvideo.TruvideoSdkCamera/SQ":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraMediaType/RawValue-swift.typealias":{"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameramediatype\/rawvalue-swift.typealias","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraMediaType\/RawValue-swift.typealias","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"RawValue","kind":"identifier"}],"title":"TruvideoSdkCameraMediaType.RawValue","kind":"symbol","abstract":[{"text":"The raw type that can be used to represent all values of the conforming type.","type":"text"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"RawValue","kind":"identifier"}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraMediaType/init(rawValue:)":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraMediaType\/init(rawValue:)","title":"init(rawValue:)","type":"topic","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:17TruvideoSdkCamera0abC9MediaTypeO8RawValuea","text":"RawValue"},{"text":")","kind":"text"}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameramediatype\/init(rawvalue:)","kind":"symbol","abstract":[{"text":"Creates a new instance with the specified raw value.","type":"text"}]},"doc://com.truvideo.TruvideoSdkCamera/Se":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/Se","title":"Swift.Decodable","type":"unresolvable"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraMediaType/encode(to:)":{"title":"encode(to:)","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameramediatype\/encode(to:)","kind":"symbol","type":"topic","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraMediaType\/encode(to:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"encode"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"text":"any","kind":"keyword"},{"kind":"text","text":" "},{"text":"Encoder","preciseIdentifier":"s:s7EncoderP","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"abstract":[{"type":"text","text":"Encodes this value into the given encoder."}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraMediaType/clip":{"kind":"symbol","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraMediaType\/clip","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"clip"}],"title":"TruvideoSdkCameraMediaType.clip","abstract":[{"text":"The media type representing a recorded video clip.","type":"text"}],"role":"symbol","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameramediatype\/clip","navigatorTitle":[{"kind":"identifier","text":"TruvideoSdkCameraMediaTypeClip"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"value":"TruvideoSdkCameraMediaType","op":"replace","path":"\/metadata\/title"},{"value":"enum","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"TruvideoSdkCameraMediaType","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"TruvideoSdkCameraMediaType"}]},{"op":"replace","value":[{"identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraMediaType\/clip","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraMediaType\/photo"],"title":"Enumeration Cases"}],"path":"\/topicSections"},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"TruvideoSdkCameraMediaType","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraMediaType~1photo\/title","value":"TruvideoSdkCameraMediaTypePhoto"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraMediaType~1photo\/fragments","value":[{"text":"TruvideoSdkCameraMediaTypePhoto","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraMediaType\/title","value":"TruvideoSdkCameraMediaType"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraMediaType\/fragments","value":[{"text":"TruvideoSdkCameraMediaType","kind":"identifier"}]},{"op":"replace","value":"TruvideoSdkCameraMediaTypeClip","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraMediaType~1clip\/title"},{"value":[{"text":"TruvideoSdkCameraMediaTypeClip","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraMediaType~1clip\/fragments"}]}]}