{"variants":[{"paths":["\/documentation\/truvideosdkcamera\/truvideosdkscannercameraconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/truvideosdkcamera\/truvideosdkscannercameraconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkScannerCameraConfiguration","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"modules":[{"name":"TruvideoSdkCamera"}],"title":"TruvideoSdkScannerCameraConfiguration","symbolKind":"class","roleHeading":"Class","navigatorTitle":[{"text":"TruvideoSdkScannerCameraConfiguration","kind":"identifier"}],"role":"symbol","externalID":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkScannerCameraConfiguration","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TruvideoSdkScannerCameraConfiguration","kind":"identifier"}]},"topicSections":[{"identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkScannerCameraConfiguration\/init(flashMode:orientation:codeFormats:autoClose:validator:)"],"title":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkScannerCameraConfiguration\/autoClose","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkScannerCameraConfiguration\/codeFormats","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkScannerCameraConfiguration\/flashMode","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkScannerCameraConfiguration\/orientation","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkScannerCameraConfiguration\/validator"]},{"identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkScannerCameraConfiguration\/instantiate(with:orientation:autoClose:)"],"title":"Type Methods"}],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"},{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/objc(pl)NSObject","doc:\/\/com.truvideo.TruvideoSdkCamera\/s7CVarArgP","doc:\/\/com.truvideo.TruvideoSdkCamera\/s28CustomDebugStringConvertibleP","doc:\/\/com.truvideo.TruvideoSdkCamera\/s23CustomStringConvertibleP","doc:\/\/com.truvideo.TruvideoSdkCamera\/SQ","doc:\/\/com.truvideo.TruvideoSdkCamera\/SH"],"kind":"relationships"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TruvideoSdkScannerCameraConfiguration","kind":"identifier"}]}]},{"kind":"content","content":[{"level":2,"anchor":"overview","text":"Overview","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"This class allows developers to customize ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"flash mode, orientation, supported barcode types, and validation rules"}]},{"type":"text","text":"."}]},{"type":"heading","level":2,"text":"Example Usage","anchor":"Example-Usage"},{"type":"codeListing","code":["let scannerConfig = TruvideoSdkScannerCameraConfiguration(","    flashMode: .auto,","    orientation: .portrait,","    codeFormats: [.codeQR, .dataMatrix],","    autoClose: true",")"],"syntax":"swift"}]}],"abstract":[{"type":"text","text":"Configuration settings for the "},{"type":"strong","inlineContent":[{"text":"Truvideo Scanner Camera","type":"text"}]},{"type":"text","text":"."}],"references":{"doc://com.truvideo.TruvideoSdkCamera/SH":{"type":"unresolvable","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/SH","title":"Swift.Hashable"},"doc://com.truvideo.TruvideoSdkCamera/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkScannerCameraConfiguration/autoClose":{"abstract":[{"text":"Determines whether the scanner ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"automatically closes"}]},{"type":"text","text":" after a successful scan."}],"navigatorTitle":[{"text":"autoClose","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/truvideosdkcamera\/truvideosdkscannercameraconfiguration\/autoclose","title":"autoClose","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"autoClose"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkScannerCameraConfiguration\/autoClose","role":"symbol","type":"topic"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkScannerCameraConfiguration/orientation":{"abstract":[{"text":"Defines the ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"camera orientation"}]},{"type":"text","text":" during scanning."}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkscannercameraconfiguration\/orientation","type":"topic","kind":"symbol","role":"symbol","title":"orientation","navigatorTitle":[{"text":"orientation","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"orientation","kind":"identifier"},{"kind":"text","text":": "},{"text":"TruvideoSdkCameraOrientation","kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraOrientation"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkScannerCameraConfiguration\/orientation"},"doc://com.truvideo.TruvideoSdkCamera/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/objc(cs)NSObject"},"doc://com.truvideo.TruvideoSdkCamera/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/s28CustomDebugStringConvertibleP"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkScannerCameraConfiguration/codeFormats":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkScannerCameraConfiguration\/codeFormats","abstract":[{"text":"The list of ","type":"text"},{"type":"strong","inlineContent":[{"text":"barcode formats","type":"text"}]},{"text":" that the scanner will detect.","type":"text"}],"role":"symbol","title":"codeFormats","kind":"symbol","url":"\/documentation\/truvideosdkcamera\/truvideosdkscannercameraconfiguration\/codeformats","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"codeFormats","kind":"identifier"},{"text":": [","kind":"text"},{"text":"TruvideoSdkCameraScannerCodeFormat","kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraScannerCodeFormat"},{"text":"]","kind":"text"}],"type":"topic"},"doc://com.truvideo.TruvideoSdkCamera/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/SQ"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkScannerCameraConfiguration/instantiate(with:orientation:autoClose:)":{"url":"\/documentation\/truvideosdkcamera\/truvideosdkscannercameraconfiguration\/instantiate(with:orientation:autoclose:)","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkScannerCameraConfiguration\/instantiate(with:orientation:autoClose:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"instantiate"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"with"},{"text":": ","kind":"text"},{"text":"TruvideoSdkCameraFlashMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraFlashMode"},{"kind":"text","text":", "},{"text":"orientation","kind":"externalParam"},{"kind":"text","text":": "},{"text":"TruvideoSdkCameraOrientation","kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraOrientation"},{"text":", ","kind":"text"},{"text":"autoClose","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":") -> ","kind":"text"},{"text":"TruvideoSdkScannerCameraConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkScannerCameraConfiguration"}],"title":"instantiate(with:orientation:autoClose:)","kind":"symbol","abstract":[{"type":"text","text":"Creates a scanner configuration with default settings."}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"instantiateWith:orientation:autoClose:"}]},"doc://com.truvideo.TruvideoSdkCamera/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/objc(pl)NSObject"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkScannerCameraConfiguration":{"title":"TruvideoSdkScannerCameraConfiguration","role":"symbol","abstract":[{"text":"Configuration settings for the ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"Truvideo Scanner Camera"}]},{"type":"text","text":"."}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TruvideoSdkScannerCameraConfiguration"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkScannerCameraConfiguration","url":"\/documentation\/truvideosdkcamera\/truvideosdkscannercameraconfiguration","navigatorTitle":[{"text":"TruvideoSdkScannerCameraConfiguration","kind":"identifier"}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"kind":"symbol","abstract":[{"type":"text","text":"Store and capture photos and videos using a fully integrated camera system."}],"url":"\/documentation\/truvideosdkcamera","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","title":"TruvideoSdkCamera","type":"topic","role":"collection"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkScannerCameraConfiguration/init(flashMode:orientation:codeFormats:autoClose:validator:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"flashMode","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraFlashMode","kind":"typeIdentifier","text":"TruvideoSdkCameraFlashMode"},{"kind":"text","text":", "},{"kind":"externalParam","text":"orientation"},{"kind":"text","text":": "},{"text":"TruvideoSdkCameraOrientation","kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraOrientation"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"codeFormats"},{"kind":"text","text":": ["},{"text":"TruvideoSdkCameraScannerCodeFormat","kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraScannerCodeFormat"},{"text":"], ","kind":"text"},{"text":"autoClose","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"text":"validator","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:17TruvideoSdkCamera0abC17ScannerValidationa","text":"TruvideoSdkCameraScannerValidation"},{"text":"?)","kind":"text"}],"kind":"symbol","url":"\/documentation\/truvideosdkcamera\/truvideosdkscannercameraconfiguration\/init(flashmode:orientation:codeformats:autoclose:validator:)","title":"init(flashMode:orientation:codeFormats:autoClose:validator:)","abstract":[{"text":"Initializes a scanner configuration with custom settings.","type":"text"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkScannerCameraConfiguration\/init(flashMode:orientation:codeFormats:autoClose:validator:)"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkScannerCameraConfiguration/validator":{"abstract":[{"type":"text","text":"A "},{"inlineContent":[{"type":"text","text":"validation function"}],"type":"strong"},{"text":" that determines whether a scanned barcode is accepted.","type":"text"}],"title":"validator","url":"\/documentation\/truvideosdkcamera\/truvideosdkscannercameraconfiguration\/validator","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"validator","kind":"identifier"},{"kind":"text","text":": "},{"text":"TruvideoSdkCameraScannerValidation","kind":"typeIdentifier","preciseIdentifier":"s:17TruvideoSdkCamera0abC17ScannerValidationa"},{"text":"?","kind":"text"}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkScannerCameraConfiguration\/validator"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkScannerCameraConfiguration/flashMode":{"navigatorTitle":[{"text":"flashMode","kind":"identifier"}],"role":"symbol","title":"flashMode","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"flashMode"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraFlashMode","text":"TruvideoSdkCameraFlashMode"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkScannerCameraConfiguration\/flashMode","abstract":[{"type":"text","text":"Specifies whether the "},{"type":"strong","inlineContent":[{"text":"flash","type":"text"}]},{"type":"text","text":" is enabled during scanning."}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkscannercameraconfiguration\/flashmode"},"doc://com.truvideo.TruvideoSdkCamera/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"TruvideoSdkScannerCameraConfiguration","op":"replace","path":"\/metadata\/title"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"TruvideoSdkScannerCameraConfiguration"}]},{"op":"replace","value":[{"text":"TruvideoSdkScannerCameraConfiguration","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkScannerCameraConfiguration\/autoClose","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkScannerCameraConfiguration\/flashMode","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkScannerCameraConfiguration\/orientation"]},{"title":"Type Methods","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkScannerCameraConfiguration\/instantiate(with:orientation:autoClose:)"]}]},{"op":"replace","value":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/objc(cs)NSObject"]}],"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TruvideoSdkScannerCameraConfiguration"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"autoClose","op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkScannerCameraConfiguration~1autoClose\/title"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkScannerCameraConfiguration~1autoClose\/fragments","op":"replace","value":[{"text":"autoClose","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkScannerCameraConfiguration~1orientation\/title","value":"orientation"},{"op":"replace","value":[{"kind":"identifier","text":"orientation"}],"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkScannerCameraConfiguration~1orientation\/fragments"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkScannerCameraConfiguration~1instantiate(with:orientation:autoClose:)\/title","op":"replace","value":"instantiateWith:orientation:autoClose:"},{"value":[{"kind":"text","text":"+ "},{"text":"instantiateWith:orientation:autoClose:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkScannerCameraConfiguration~1instantiate(with:orientation:autoClose:)\/fragments"},{"op":"replace","value":"TruvideoSdkScannerCameraConfiguration","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkScannerCameraConfiguration\/title"},{"value":[{"kind":"identifier","text":"TruvideoSdkScannerCameraConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkScannerCameraConfiguration\/fragments"},{"op":"replace","value":"flashMode","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkScannerCameraConfiguration~1flashMode\/title"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkScannerCameraConfiguration~1flashMode\/fragments","op":"replace","value":[{"text":"flashMode","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}