{"hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera"]]},"topicSections":[{"identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraDevice\/id","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraDevice\/isTapToFocusEnabled","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraDevice\/lensFacing","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraDevice\/resolutions","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraDevice\/sensorOrientation","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraDevice\/withFlash"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraDevice\/encode(to:)"]}],"abstract":[{"text":"Represents a camera device available on the system.","type":"text"}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TruvideoSdkCameraDevice"}]}]},{"content":[{"text":"Overview","level":2,"anchor":"overview","type":"heading"},{"type":"paragraph","inlineContent":[{"code":"TruvideoSdkCameraDevice","type":"codeVoice"},{"type":"text","text":" provides details about a specific camera, including its "},{"type":"strong","inlineContent":[{"text":"ID, lens direction, supported resolutions, flash availability, and sensor orientation","type":"text"}]},{"type":"text","text":"."}]},{"type":"heading","anchor":"Example-Usage","level":2,"text":"Example Usage"},{"type":"codeListing","code":["let backCamera = TruvideoSdkCameraDevice(","    id: \"com.truvideo.backcamera\",","    lensFacing: .back,","    resolutions: [TruvideoSdkCameraResolution(width: 1920, height: 1080)],","    withFlash: true,","    isTapToFocusEnabled: true,","    sensorOrientation: 90",")"],"syntax":"swift"}],"kind":"content"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraDevice"},"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TruvideoSdkCameraDevice"}],"title":"TruvideoSdkCameraDevice","navigatorTitle":[{"kind":"identifier","text":"TruvideoSdkCameraDevice"}],"roleHeading":"Class","role":"symbol","modules":[{"name":"TruvideoSdkCamera"}],"symbolKind":"class","externalID":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraDevice"},"schemaVersion":{"minor":3,"patch":0,"major":0},"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/objc(cs)NSObject"],"type":"inheritsFrom"},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/objc(pl)NSObject","doc:\/\/com.truvideo.TruvideoSdkCamera\/s7CVarArgP","doc:\/\/com.truvideo.TruvideoSdkCamera\/s28CustomDebugStringConvertibleP","doc:\/\/com.truvideo.TruvideoSdkCamera\/s23CustomStringConvertibleP","doc:\/\/com.truvideo.TruvideoSdkCamera\/SE","doc:\/\/com.truvideo.TruvideoSdkCamera\/SQ","doc:\/\/com.truvideo.TruvideoSdkCamera\/SH"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcameradevice"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcameradevice"]}],"sections":[],"references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraDevice/resolutions":{"abstract":[{"type":"text","text":"The list of supported resolutions for this camera device."}],"title":"resolutions","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameradevice\/resolutions","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"resolutions","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraResolution","text":"TruvideoSdkCameraResolution"},{"kind":"text","text":"]"}],"kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"resolutions"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraDevice\/resolutions"},"doc://com.truvideo.TruvideoSdkCamera/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/SE"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraDevice/sensorOrientation":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraDevice\/sensorOrientation","kind":"symbol","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sensorOrientation","kind":"identifier"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"title":"sensorOrientation","abstract":[{"text":"The sensor orientation of the camera, in degrees.","type":"text"}],"role":"symbol","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameradevice\/sensororientation","navigatorTitle":[{"text":"sensorOrientation","kind":"identifier"}]},"doc://com.truvideo.TruvideoSdkCamera/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/s28CustomDebugStringConvertibleP"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraDevice/isTapToFocusEnabled":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isTapToFocusEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"isTapToFocusEnabled"}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameradevice\/istaptofocusenabled","abstract":[{"type":"text","text":"Indicates whether the camera supports tap-to-focus functionality."}],"type":"topic","title":"isTapToFocusEnabled","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraDevice\/isTapToFocusEnabled"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraDevice":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TruvideoSdkCameraDevice","kind":"identifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"TruvideoSdkCameraDevice","kind":"identifier"}],"abstract":[{"type":"text","text":"Represents a camera device available on the system."}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameradevice","type":"topic","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraDevice","title":"TruvideoSdkCameraDevice"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraDevice/lensFacing":{"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameradevice\/lensfacing","abstract":[{"type":"text","text":"The lens direction of the camera."}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraDevice\/lensFacing","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"lensFacing"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraLensFacing","text":"TruvideoSdkCameraLensFacing","kind":"typeIdentifier"}],"title":"lensFacing","navigatorTitle":[{"kind":"identifier","text":"lensFacing"}],"role":"symbol","type":"topic","kind":"symbol"},"doc://com.truvideo.TruvideoSdkCamera/SH":{"type":"unresolvable","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/SH","title":"Swift.Hashable"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraDevice/id":{"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameradevice\/id","abstract":[{"type":"text","text":"The unique identifier of the camera device."}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraDevice\/id","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"id"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"title":"id","navigatorTitle":[{"kind":"identifier","text":"id"}],"role":"symbol","type":"topic","kind":"symbol"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"kind":"symbol","abstract":[{"type":"text","text":"Store and capture photos and videos using a fully integrated camera system."}],"url":"\/documentation\/truvideosdkcamera","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","title":"TruvideoSdkCamera","type":"topic","role":"collection"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraDevice/encode(to:)":{"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameradevice\/encode(to:)","abstract":[],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraDevice\/encode(to:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"encode","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"text":": ","kind":"text"},{"kind":"keyword","text":"any"},{"text":" ","kind":"text"},{"text":"Encoder","preciseIdentifier":"s:s7EncoderP","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"title":"encode(to:)","role":"symbol","type":"topic","kind":"symbol"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraDevice/withFlash":{"navigatorTitle":[{"text":"withFlash","kind":"identifier"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraDevice\/withFlash","type":"topic","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameradevice\/withflash","kind":"symbol","title":"withFlash","role":"symbol","abstract":[{"text":"Indicates whether the camera device has a built-in flash.","type":"text"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"withFlash","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]},"doc://com.truvideo.TruvideoSdkCamera/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/objc(cs)NSObject"},"doc://com.truvideo.TruvideoSdkCamera/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/SQ"},"doc://com.truvideo.TruvideoSdkCamera/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/s23CustomStringConvertibleP"},"doc://com.truvideo.TruvideoSdkCamera/objc(pl)NSObject":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.truvideo.TruvideoSdkCamera/s7CVarArgP":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"TruvideoSdkCameraDevice","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"value":[{"text":"TruvideoSdkCameraDevice","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"TruvideoSdkCameraDevice"}]},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraDevice\/id","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraDevice\/isTapToFocusEnabled","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraDevice\/lensFacing","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraDevice\/resolutions","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraDevice\/sensorOrientation","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraDevice\/withFlash"],"title":"Instance Properties"}]},{"value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/objc(cs)NSObject"],"type":"inheritsFrom"}],"path":"\/relationshipsSections","op":"replace"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"TruvideoSdkCameraDevice","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"op":"replace","value":"resolutions","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraDevice~1resolutions\/title"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraDevice~1resolutions\/fragments","op":"replace","value":[{"text":"resolutions","kind":"identifier"}]},{"value":"sensorOrientation","op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraDevice~1sensorOrientation\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraDevice~1sensorOrientation\/fragments","value":[{"kind":"identifier","text":"sensorOrientation"}]},{"value":"isTapToFocusEnabled","op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraDevice~1isTapToFocusEnabled\/title"},{"value":[{"kind":"identifier","text":"isTapToFocusEnabled"}],"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraDevice~1isTapToFocusEnabled\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraDevice\/title","value":"TruvideoSdkCameraDevice","op":"replace"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraDevice\/fragments","op":"replace","value":[{"kind":"identifier","text":"TruvideoSdkCameraDevice"}]},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraDevice~1lensFacing\/title","value":"lensFacing","op":"replace"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraDevice~1lensFacing\/fragments","value":[{"text":"lensFacing","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraDevice~1id\/title","value":"id"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraDevice~1id\/fragments","value":[{"text":"id","kind":"identifier"}],"op":"replace"},{"value":"withFlash","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraDevice~1withFlash\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraDevice~1withFlash\/fragments","value":[{"kind":"identifier","text":"withFlash"}]}]}]}