{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentTruvideoSdkScannerCameraView"},{"text":"(","kind":"text"},{"text":"preset","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkScannerCameraConfiguration","text":"TruvideoSdkScannerCameraConfiguration","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkScannerCameraConfiguration","kind":"typeIdentifier"},{"text":" = .init(\n            flashMode: .off,\n            orientation: nil\n        ), ","kind":"text"},{"text":"onComplete","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"kind":"text","text":" ("},{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraScannerCode","text":"TruvideoSdkCameraScannerCode","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraScannerCode","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"preset","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A "},{"code":"TruvideoSdkCameraConfiguration","type":"codeVoice"},{"type":"text","text":" object that defines the configuration for the camera."}]}]},{"name":"onComplete","content":[{"inlineContent":[{"text":"A callback function that receives a ","type":"text"},{"code":"TruvideoSdkCameraScannerCode","type":"codeVoice"},{"text":" containing the scanned barcode data.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"level":2,"text":"Discussion","anchor":"discussion","type":"heading"},{"inlineContent":[{"type":"text","text":"This method displays the "},{"type":"strong","inlineContent":[{"type":"text","text":"TruvideoSdkScannerCamera"}]},{"text":", allowing users to scan barcodes and QR codes.","type":"text"}],"type":"paragraph"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/truvideosdkcamera\/uikit\/uiviewcontroller\/presenttruvideosdkscannercameraview(preset:oncomplete:)"]}],"abstract":[{"type":"text","text":"Presents the Scanner Camera view in full-screen mode."}],"metadata":{"modules":[{"name":"TruvideoSdkCamera","relatedModules":["UIKit"]}],"extendedModule":"UIKit","symbolKind":"method","roleHeading":"Instance Method","externalID":"c:@CM@TruvideoSdkCamera@@objc(cs)UIViewController(im)presentTruvideoSdkScannerCameraViewWithPreset:onComplete:","title":"presentTruvideoSdkScannerCameraView(preset:onComplete:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"presentTruvideoSdkScannerCameraView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"preset","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TruvideoSdkScannerCameraConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkScannerCameraConfiguration"},{"text":", ","kind":"text"},{"text":"onComplete","kind":"externalParam"},{"text":": (","kind":"text"},{"preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraScannerCode","text":"TruvideoSdkCameraScannerCode","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/UIKit","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/UIKit\/UIViewController"]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/UIKit\/UIViewController\/presentTruvideoSdkScannerCameraView(preset:onComplete:)","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/UIKit/UIViewController":{"title":"UIViewController","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/UIKit\/UIViewController","type":"topic","url":"\/documentation\/truvideosdkcamera\/uikit\/uiviewcontroller","role":"symbol","fragments":[{"text":"extension","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"}],"abstract":[],"kind":"symbol","navigatorTitle":[{"text":"UIViewController","kind":"identifier"}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkScannerCameraConfiguration":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"TruvideoSdkScannerCameraConfiguration","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TruvideoSdkScannerCameraConfiguration"}],"abstract":[{"type":"text","text":"Configuration settings for the "},{"type":"strong","inlineContent":[{"text":"Truvideo Scanner Camera","type":"text"}]},{"type":"text","text":"."}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkscannercameraconfiguration","kind":"symbol","title":"TruvideoSdkScannerCameraConfiguration","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkScannerCameraConfiguration"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/UIKit/UIViewController/presentTruvideoSdkScannerCameraView(preset:onComplete:)":{"title":"presentTruvideoSdkScannerCameraView(preset:onComplete:)","url":"\/documentation\/truvideosdkcamera\/uikit\/uiviewcontroller\/presenttruvideosdkscannercameraview(preset:oncomplete:)","abstract":[{"text":"Presents the Scanner Camera view in full-screen mode.","type":"text"}],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/UIKit\/UIViewController\/presentTruvideoSdkScannerCameraView(preset:onComplete:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"presentTruvideoSdkScannerCameraView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"preset","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TruvideoSdkScannerCameraConfiguration","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkScannerCameraConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"onComplete","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"TruvideoSdkCameraScannerCode","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraScannerCode","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","title":"TruvideoSdkCamera","role":"collection","type":"topic","url":"\/documentation\/truvideosdkcamera","kind":"symbol","abstract":[{"text":"Store and capture photos and videos using a fully integrated camera system.","type":"text"}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraScannerCode":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraScannerCode","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TruvideoSdkCameraScannerCode","kind":"identifier"}],"type":"topic","abstract":[{"text":"Represents the result of a barcode or QR code scan.","type":"text"}],"title":"TruvideoSdkCameraScannerCode","role":"symbol","url":"\/documentation\/truvideosdkcamera\/truvideosdkcamerascannercode","navigatorTitle":[{"text":"TruvideoSdkCameraScannerCode","kind":"identifier"}],"kind":"symbol"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/UIKit":{"title":"UIKit","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/UIKit","type":"topic","url":"\/documentation\/truvideosdkcamera\/uikit","role":"collection","abstract":[],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkScannerCameraConfiguration\/title","value":"TruvideoSdkScannerCameraConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkScannerCameraConfiguration\/fragments","op":"replace","value":[{"text":"TruvideoSdkScannerCameraConfiguration","kind":"identifier"}]},{"op":"replace","value":"TruvideoSdkCameraScannerCode","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraScannerCode\/title"},{"op":"replace","value":[{"text":"TruvideoSdkCameraScannerCode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraScannerCode\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}