{"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"flashMode","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraFlashMode","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraFlashMode","text":"TruvideoSdkCameraFlashMode"}]}]},{"kind":"content","content":[{"type":"heading","text":"Discussion","level":2,"anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"Determines whether the flash is on, off, or set to auto mode.","type":"text"}]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkARCameraConfiguration"]]},"sections":[],"identifier":{"url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkARCameraConfiguration\/flashMode","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/truvideosdkcamera\/truvideosdkarcameraconfiguration\/flashmode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/truvideosdkcamera\/truvideosdkarcameraconfiguration\/flashmode"]}],"metadata":{"roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"flashMode","kind":"identifier"},{"kind":"text","text":": "},{"text":"TruvideoSdkCameraFlashMode","preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraFlashMode","kind":"typeIdentifier"}],"externalID":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkARCameraConfiguration(py)flashMode","title":"flashMode","navigatorTitle":[{"text":"flashMode","kind":"identifier"}],"role":"symbol","symbolKind":"property","modules":[{"name":"TruvideoSdkCamera"}]},"abstract":[{"type":"text","text":"The flash mode setting for the AR Camera."}],"references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","title":"TruvideoSdkCamera","role":"collection","type":"topic","url":"\/documentation\/truvideosdkcamera","kind":"symbol","abstract":[{"text":"Store and capture photos and videos using a fully integrated camera system.","type":"text"}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraFlashMode":{"title":"TruvideoSdkCameraFlashMode","type":"topic","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraFlashMode","role":"symbol","abstract":[{"text":"Defines the flash mode settings for the camera.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"TruvideoSdkCameraFlashMode","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"TruvideoSdkCameraFlashMode"}],"kind":"symbol","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraflashmode"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkARCameraConfiguration/flashMode":{"navigatorTitle":[{"kind":"identifier","text":"flashMode"}],"title":"flashMode","role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/truvideosdkcamera\/truvideosdkarcameraconfiguration\/flashmode","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkARCameraConfiguration\/flashMode","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"flashMode","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TruvideoSdkCameraFlashMode","preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraFlashMode"}],"abstract":[{"type":"text","text":"The flash mode setting for the AR Camera."}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkARCameraConfiguration":{"navigatorTitle":[{"kind":"identifier","text":"TruvideoSdkARCameraConfiguration"}],"title":"TruvideoSdkARCameraConfiguration","role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkARCameraConfiguration","url":"\/documentation\/truvideosdkcamera\/truvideosdkarcameraconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TruvideoSdkARCameraConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"A configuration object for setting up the AR Camera in "},{"type":"codeVoice","code":"TruvideoSdkCamera"},{"text":".","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"flashMode","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"flashMode","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"TruvideoSdkCameraFlashMode","kind":"typeIdentifier","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraFlashMode","preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraFlashMode"},{"text":" ","kind":"text"},{"text":"flashMode","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraFlashMode\/title","value":"TruvideoSdkCameraFlashMode"},{"value":[{"kind":"identifier","text":"TruvideoSdkCameraFlashMode"}],"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraFlashMode\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkARCameraConfiguration~1flashMode\/title","value":"flashMode"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkARCameraConfiguration~1flashMode\/fragments","value":[{"kind":"identifier","text":"flashMode"}]},{"op":"replace","value":"TruvideoSdkARCameraConfiguration","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkARCameraConfiguration\/title"},{"value":[{"kind":"identifier","text":"TruvideoSdkARCameraConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkARCameraConfiguration\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}