{"variants":[{"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcameraconfiguration\/init(lensfacing:flashmode:orientation:outputpath:frontresolutions:frontresolution:backresolutions:backresolution:mode:)"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraConfiguration\/init(lensFacing:flashMode:orientation:outputPath:frontResolutions:frontResolution:backResolutions:backResolution:mode:)"},"abstract":[{"type":"text","text":"Creates a new instance of "},{"type":"codeVoice","code":"TruvideoSdkCameraConfiguration"},{"type":"text","text":" with customizable settings."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraConfiguration"]]},"metadata":{"modules":[{"name":"TruvideoSdkCamera"}],"symbolKind":"init","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"lensFacing","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraLensFacing","text":"TruvideoSdkCameraLensFacing","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"flashMode","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TruvideoSdkCameraFlashMode","preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraFlashMode"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"orientation"},{"kind":"text","text":": "},{"text":"TruvideoSdkCameraOrientation","preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraOrientation","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"outputPath"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"frontResolutions"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraResolution","text":"TruvideoSdkCameraResolution"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"frontResolution"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraResolution","text":"TruvideoSdkCameraResolution"},{"text":"?, ","kind":"text"},{"text":"backResolutions","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"TruvideoSdkCameraResolution","kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraResolution"},{"kind":"text","text":"], "},{"text":"backResolution","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraResolution","text":"TruvideoSdkCameraResolution"},{"text":"?, ","kind":"text"},{"text":"mode","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraMediaMode","kind":"typeIdentifier","text":"TruvideoSdkCameraMediaMode"},{"text":")","kind":"text"}],"role":"symbol","externalID":"s:17TruvideoSdkCamera0abC13ConfigurationC10lensFacing9flashMode11orientation10outputPath16frontResolutions0L10Resolution04backM00oN04modeAcA0abc4LensF0O_AA0abc5FlashH0OAA0abC11OrientationOSgSSSayAA0abcN0CGAUSgAvwA0abc5MediaH0Ctcfc","roleHeading":"Initializer","title":"init(lensFacing:flashMode:orientation:outputPath:frontResolutions:frontResolution:backResolutions:backResolution:mode:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"lensFacing","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraLensFacing","text":"TruvideoSdkCameraLensFacing","kind":"typeIdentifier","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraLensFacing"},{"kind":"text","text":", "},{"text":"flashMode","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraFlashMode","text":"TruvideoSdkCameraFlashMode","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraFlashMode","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"orientation"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraOrientation","preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraOrientation","text":"TruvideoSdkCameraOrientation"},{"text":"?, ","kind":"text"},{"text":"outputPath","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"frontResolutions","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraResolution","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraResolution","text":"TruvideoSdkCameraResolution"},{"text":"], ","kind":"text"},{"text":"frontResolution","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraResolution","kind":"typeIdentifier","text":"TruvideoSdkCameraResolution","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraResolution"},{"text":"?, ","kind":"text"},{"text":"backResolutions","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"TruvideoSdkCameraResolution","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraResolution","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraResolution"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"backResolution"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraResolution","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraResolution","text":"TruvideoSdkCameraResolution","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"mode","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraMediaMode","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraMediaMode","kind":"typeIdentifier","text":"TruvideoSdkCameraMediaMode"},{"text":")","kind":"text"}]}]},{"kind":"parameters","parameters":[{"name":"lensFacing","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The camera lens selection ("},{"type":"codeVoice","code":".front"},{"type":"text","text":" or "},{"type":"codeVoice","code":".back"},{"type":"text","text":")."}]}]},{"name":"flashMode","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The flash mode setting ("},{"code":".on","type":"codeVoice"},{"text":", ","type":"text"},{"type":"codeVoice","code":".off"},{"type":"text","text":")."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The camera’s orientation ("},{"type":"codeVoice","code":".portrait"},{"type":"text","text":", "},{"code":".landscapeLeft","type":"codeVoice"},{"type":"text","text":", "},{"type":"codeVoice","code":".landscapeRight"},{"type":"text","text":", "},{"type":"codeVoice","code":".portraitReverse"},{"type":"text","text":")."}]}],"name":"orientation"},{"name":"outputPath","content":[{"inlineContent":[{"type":"text","text":"The destination file path for captured media."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Available resolutions for the "},{"type":"strong","inlineContent":[{"text":"front-facing","type":"text"}]},{"type":"text","text":" camera."}],"type":"paragraph"}],"name":"frontResolutions"},{"content":[{"inlineContent":[{"text":"The selected resolution for the ","type":"text"},{"type":"strong","inlineContent":[{"text":"front-facing","type":"text"}]},{"text":" camera.","type":"text"}],"type":"paragraph"}],"name":"frontResolution"},{"content":[{"inlineContent":[{"text":"Available resolutions for the ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"rear-facing"}]},{"text":" camera.","type":"text"}],"type":"paragraph"}],"name":"backResolutions"},{"name":"backResolution","content":[{"type":"paragraph","inlineContent":[{"text":"The selected resolution for the ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"rear-facing"}]},{"text":" camera.","type":"text"}]}]},{"name":"mode","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The media capture mode ("},{"type":"codeVoice","code":".photoOnly"},{"text":", ","type":"text"},{"type":"codeVoice","code":".videoOnly"},{"type":"text","text":", "},{"code":".videoAndPicture","type":"codeVoice"},{"text":").","type":"text"}]}]}]}],"references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraFlashMode":{"title":"TruvideoSdkCameraFlashMode","type":"topic","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraFlashMode","role":"symbol","abstract":[{"text":"Defines the flash mode settings for the camera.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"TruvideoSdkCameraFlashMode","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"TruvideoSdkCameraFlashMode"}],"kind":"symbol","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraflashmode"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","title":"TruvideoSdkCamera","role":"collection","type":"topic","url":"\/documentation\/truvideosdkcamera","kind":"symbol","abstract":[{"text":"Store and capture photos and videos using a fully integrated camera system.","type":"text"}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraMediaMode":{"type":"topic","abstract":[],"title":"TruvideoSdkCameraMediaMode","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraMediaMode","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TruvideoSdkCameraMediaMode","kind":"identifier"}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameramediamode","navigatorTitle":[{"text":"TruvideoSdkCameraMediaMode","kind":"identifier"}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraLensFacing":{"type":"topic","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraLensFacing","title":"TruvideoSdkCameraLensFacing","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TruvideoSdkCameraLensFacing"}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameralensfacing","navigatorTitle":[{"text":"TruvideoSdkCameraLensFacing","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Defines the camera lens direction used for capturing media.","type":"text"}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraConfiguration/init(lensFacing:flashMode:orientation:outputPath:frontResolutions:frontResolution:backResolutions:backResolution:mode:)":{"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"lensFacing","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TruvideoSdkCameraLensFacing","preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraLensFacing"},{"text":", ","kind":"text"},{"text":"flashMode","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraFlashMode","kind":"typeIdentifier","text":"TruvideoSdkCameraFlashMode"},{"kind":"text","text":", "},{"kind":"externalParam","text":"orientation"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TruvideoSdkCameraOrientation","preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraOrientation"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"outputPath"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"frontResolutions","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraResolution","text":"TruvideoSdkCameraResolution"},{"text":"], ","kind":"text"},{"text":"frontResolution","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraResolution","text":"TruvideoSdkCameraResolution"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"backResolutions"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraResolution","kind":"typeIdentifier","text":"TruvideoSdkCameraResolution"},{"text":"], ","kind":"text"},{"text":"backResolution","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TruvideoSdkCameraResolution","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraResolution"},{"text":"?, ","kind":"text"},{"text":"mode","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraMediaMode","text":"TruvideoSdkCameraMediaMode"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraConfiguration\/init(lensFacing:flashMode:orientation:outputPath:frontResolutions:frontResolution:backResolutions:backResolution:mode:)","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraconfiguration\/init(lensfacing:flashmode:orientation:outputpath:frontresolutions:frontresolution:backresolutions:backresolution:mode:)","type":"topic","title":"init(lensFacing:flashMode:orientation:outputPath:frontResolutions:frontResolution:backResolutions:backResolution:mode:)","kind":"symbol","abstract":[{"type":"text","text":"Creates a new instance of "},{"type":"codeVoice","code":"TruvideoSdkCameraConfiguration"},{"type":"text","text":" with customizable settings."}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraOrientation":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TruvideoSdkCameraOrientation"}],"title":"TruvideoSdkCameraOrientation","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TruvideoSdkCameraOrientation"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraOrientation","abstract":[{"type":"text","text":"Defines the camera orientation for media capture."}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraorientation"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraConfiguration":{"abstract":[{"text":"A configuration object for setting up the camera in ","type":"text"},{"type":"codeVoice","code":"TruvideoSdkCamera"},{"type":"text","text":"."}],"navigatorTitle":[{"text":"TruvideoSdkCameraConfiguration","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TruvideoSdkCameraConfiguration"}],"type":"topic","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraconfiguration","kind":"symbol","title":"TruvideoSdkCameraConfiguration","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraConfiguration"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraResolution":{"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraresolution","kind":"symbol","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraResolution","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TruvideoSdkCameraResolution"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"TruvideoSdkCameraResolution"}],"title":"TruvideoSdkCameraResolution","abstract":[]}},"variantOverrides":[{"patch":[{"value":"TruvideoSdkCameraFlashMode","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraFlashMode\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraFlashMode\/fragments","op":"replace","value":[{"text":"TruvideoSdkCameraFlashMode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraMediaMode\/title","op":"replace","value":"TruvideoSdkCameraMediaMode"},{"op":"replace","value":[{"text":"TruvideoSdkCameraMediaMode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraMediaMode\/fragments"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraLensFacing\/title","op":"replace","value":"TruvideoSdkCameraLensFacing"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraLensFacing\/fragments","value":[{"text":"TruvideoSdkCameraLensFacing","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraOrientation\/title","op":"replace","value":"TruvideoSdkCameraOrientation"},{"value":[{"text":"TruvideoSdkCameraOrientation","kind":"identifier"}],"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraOrientation\/fragments","op":"replace"},{"op":"replace","value":"TruvideoSdkCameraConfiguration","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraConfiguration\/title"},{"op":"replace","value":[{"text":"TruvideoSdkCameraConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraConfiguration\/fragments"},{"value":"TruvideoSdkCameraResolution","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraResolution\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraResolution\/fragments","value":[{"text":"TruvideoSdkCameraResolution","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}