{"identifier":{"url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraEventType\/truvideoSdkCameraEventRecordingResumed(resolution:orientation:lensFacing:)","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraEventType"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"truvideoSdkCameraEventRecordingResumed","kind":"identifier"},{"text":"(","kind":"text"},{"text":"resolution","kind":"externalParam"},{"kind":"text","text":": "},{"text":"TruvideoSdkCameraResolution","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraResolution","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraResolution","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"orientation","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraOrientation","kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraOrientation","text":"TruvideoSdkCameraOrientation"},{"text":", ","kind":"text"},{"text":"lensFacing","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraLensFacing","text":"TruvideoSdkCameraLensFacing","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraLensFacing"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The current recording resolution."}],"type":"paragraph"}],"name":"resolution"},{"name":"orientation","content":[{"inlineContent":[{"text":"The current camera orientation.","type":"text"}],"type":"paragraph"}]},{"name":"lensFacing","content":[{"inlineContent":[{"text":"The current lens direction.","type":"text"}],"type":"paragraph"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcameraeventtype\/truvideosdkcameraeventrecordingresumed(resolution:orientation:lensfacing:)"]}],"metadata":{"symbolKind":"case","roleHeading":"Case","modules":[{"name":"TruvideoSdkCamera"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"truvideoSdkCameraEventRecordingResumed"},{"kind":"text","text":"("},{"text":"resolution","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraResolution","text":"TruvideoSdkCameraResolution"},{"kind":"text","text":", "},{"text":"orientation","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraOrientation","text":"TruvideoSdkCameraOrientation"},{"text":", ","kind":"text"},{"text":"lensFacing","kind":"externalParam"},{"kind":"text","text":": "},{"text":"TruvideoSdkCameraLensFacing","preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraLensFacing","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"TruvideoSdkCameraEventType.truvideoSdkCameraEventRecordingResumed(resolution:orientation:lensFacing:)","externalID":"s:17TruvideoSdkCamera0abC9EventTypeO08truvideobcD16RecordingResumedyAcA0abC10ResolutionC_AA0abC11OrientationOAA0abC10LensFacingOtcACmF","role":"symbol"},"sections":[],"abstract":[{"type":"text","text":"Triggered when "},{"inlineContent":[{"text":"video recording is resumed","type":"text"}],"type":"strong"},{"type":"text","text":" after being paused."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraOrientation":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"TruvideoSdkCameraOrientation","kind":"identifier"}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraorientation","title":"TruvideoSdkCameraOrientation","abstract":[{"type":"text","text":"Defines the camera orientation for media capture."}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraOrientation","navigatorTitle":[{"kind":"identifier","text":"TruvideoSdkCameraOrientation"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraEventType/truvideoSdkCameraEventRecordingResumed(resolution:orientation:lensFacing:)":{"kind":"symbol","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraEventType\/truvideoSdkCameraEventRecordingResumed(resolution:orientation:lensFacing:)","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"truvideoSdkCameraEventRecordingResumed"},{"kind":"text","text":"("},{"kind":"externalParam","text":"resolution"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraResolution","text":"TruvideoSdkCameraResolution"},{"kind":"text","text":", "},{"kind":"externalParam","text":"orientation"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraOrientation","kind":"typeIdentifier","text":"TruvideoSdkCameraOrientation"},{"text":", ","kind":"text"},{"text":"lensFacing","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TruvideoSdkCameraLensFacing","preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraLensFacing"},{"kind":"text","text":")"}],"title":"TruvideoSdkCameraEventType.truvideoSdkCameraEventRecordingResumed(resolution:orientation:lensFacing:)","abstract":[{"text":"Triggered when ","type":"text"},{"type":"strong","inlineContent":[{"text":"video recording is resumed","type":"text"}]},{"type":"text","text":" after being paused."}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraeventtype\/truvideosdkcameraeventrecordingresumed(resolution:orientation:lensfacing:)","type":"topic","role":"symbol"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraEventType":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"TruvideoSdkCameraEventType","kind":"identifier"}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraeventtype","title":"TruvideoSdkCameraEventType","abstract":[{"type":"text","text":"Defines the different types of events emitted by "},{"code":"TruvideoSdkCamera","type":"codeVoice"},{"text":".","type":"text"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraEventType","navigatorTitle":[{"text":"TruvideoSdkCameraEventType","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraResolution":{"kind":"symbol","abstract":[],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraresolution","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TruvideoSdkCameraResolution","kind":"identifier"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraResolution","title":"TruvideoSdkCameraResolution","type":"topic","navigatorTitle":[{"text":"TruvideoSdkCameraResolution","kind":"identifier"}],"role":"symbol"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraLensFacing":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TruvideoSdkCameraLensFacing"}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameralensfacing","title":"TruvideoSdkCameraLensFacing","abstract":[{"type":"text","text":"Defines the camera lens direction used for capturing media."}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraLensFacing","navigatorTitle":[{"kind":"identifier","text":"TruvideoSdkCameraLensFacing"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"kind":"symbol","abstract":[{"type":"text","text":"Store and capture photos and videos using a fully integrated camera system."}],"url":"\/documentation\/truvideosdkcamera","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","title":"TruvideoSdkCamera","type":"topic","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraOrientation\/title","op":"replace","value":"TruvideoSdkCameraOrientation"},{"value":[{"kind":"identifier","text":"TruvideoSdkCameraOrientation"}],"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraOrientation\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraResolution\/title","value":"TruvideoSdkCameraResolution"},{"op":"replace","value":[{"text":"TruvideoSdkCameraResolution","kind":"identifier"}],"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraResolution\/fragments"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraLensFacing\/title","value":"TruvideoSdkCameraLensFacing","op":"replace"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraLensFacing\/fragments","op":"replace","value":[{"text":"TruvideoSdkCameraLensFacing","kind":"identifier"}]}]}]}