{"hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraEventType"]]},"metadata":{"roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"truvideoSdkCameraEventRecordingStarted","kind":"identifier"},{"text":"(","kind":"text"},{"text":"resolution","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TruvideoSdkCameraResolution","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraResolution"},{"kind":"text","text":", "},{"text":"orientation","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraOrientation","text":"TruvideoSdkCameraOrientation"},{"kind":"text","text":", "},{"text":"lensFacing","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraLensFacing","text":"TruvideoSdkCameraLensFacing","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"TruvideoSdkCameraEventType.truvideoSdkCameraEventRecordingStarted(resolution:orientation:lensFacing:)","role":"symbol","modules":[{"name":"TruvideoSdkCamera"}],"symbolKind":"case","externalID":"s:17TruvideoSdkCamera0abC9EventTypeO08truvideobcD16RecordingStartedyAcA0abC10ResolutionC_AA0abC11OrientationOAA0abC10LensFacingOtcACmF"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcameraeventtype\/truvideosdkcameraeventrecordingstarted(resolution:orientation:lensfacing:)"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraEventType\/truvideoSdkCameraEventRecordingStarted(resolution:orientation:lensFacing:)"},"sections":[],"abstract":[{"text":"Triggered when ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"video recording starts"}]},{"text":".","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"truvideoSdkCameraEventRecordingStarted"},{"kind":"text","text":"("},{"kind":"externalParam","text":"resolution"},{"text":": ","kind":"text"},{"text":"TruvideoSdkCameraResolution","kind":"typeIdentifier","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraResolution","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraResolution"},{"kind":"text","text":", "},{"text":"orientation","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraOrientation","text":"TruvideoSdkCameraOrientation","kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraOrientation"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"lensFacing"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraLensFacing","text":"TruvideoSdkCameraLensFacing","preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraLensFacing"},{"kind":"text","text":")"}]}],"kind":"declarations"},{"parameters":[{"name":"resolution","content":[{"inlineContent":[{"text":"The resolution at the start of recording.","type":"text"}],"type":"paragraph"}]},{"name":"orientation","content":[{"inlineContent":[{"text":"The camera orientation.","type":"text"}],"type":"paragraph"}]},{"name":"lensFacing","content":[{"inlineContent":[{"text":"The active camera lens.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"}],"kind":"symbol","references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"kind":"symbol","abstract":[{"type":"text","text":"Store and capture photos and videos using a fully integrated camera system."}],"url":"\/documentation\/truvideosdkcamera","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","title":"TruvideoSdkCamera","type":"topic","role":"collection"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraLensFacing":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TruvideoSdkCameraLensFacing"}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameralensfacing","title":"TruvideoSdkCameraLensFacing","abstract":[{"type":"text","text":"Defines the camera lens direction used for capturing media."}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraLensFacing","navigatorTitle":[{"kind":"identifier","text":"TruvideoSdkCameraLensFacing"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraEventType":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"TruvideoSdkCameraEventType","kind":"identifier"}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraeventtype","title":"TruvideoSdkCameraEventType","abstract":[{"type":"text","text":"Defines the different types of events emitted by "},{"code":"TruvideoSdkCamera","type":"codeVoice"},{"text":".","type":"text"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraEventType","navigatorTitle":[{"text":"TruvideoSdkCameraEventType","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraResolution":{"kind":"symbol","abstract":[],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraresolution","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TruvideoSdkCameraResolution","kind":"identifier"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraResolution","title":"TruvideoSdkCameraResolution","type":"topic","navigatorTitle":[{"text":"TruvideoSdkCameraResolution","kind":"identifier"}],"role":"symbol"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraEventType/truvideoSdkCameraEventRecordingStarted(resolution:orientation:lensFacing:)":{"kind":"symbol","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraEventType\/truvideoSdkCameraEventRecordingStarted(resolution:orientation:lensFacing:)","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"truvideoSdkCameraEventRecordingStarted"},{"kind":"text","text":"("},{"text":"resolution","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TruvideoSdkCameraResolution","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraResolution"},{"kind":"text","text":", "},{"kind":"externalParam","text":"orientation"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraOrientation","kind":"typeIdentifier","text":"TruvideoSdkCameraOrientation"},{"text":", ","kind":"text"},{"text":"lensFacing","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TruvideoSdkCameraLensFacing","preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraLensFacing"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Triggered when "},{"inlineContent":[{"text":"video recording starts","type":"text"}],"type":"strong"},{"type":"text","text":"."}],"title":"TruvideoSdkCameraEventType.truvideoSdkCameraEventRecordingStarted(resolution:orientation:lensFacing:)","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraeventtype\/truvideosdkcameraeventrecordingstarted(resolution:orientation:lensfacing:)","type":"topic","role":"symbol"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraOrientation":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"TruvideoSdkCameraOrientation","kind":"identifier"}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraorientation","title":"TruvideoSdkCameraOrientation","abstract":[{"type":"text","text":"Defines the camera orientation for media capture."}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraOrientation","navigatorTitle":[{"kind":"identifier","text":"TruvideoSdkCameraOrientation"}],"kind":"symbol","role":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraLensFacing\/title","value":"TruvideoSdkCameraLensFacing","op":"replace"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraLensFacing\/fragments","op":"replace","value":[{"kind":"identifier","text":"TruvideoSdkCameraLensFacing"}]},{"value":"TruvideoSdkCameraResolution","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraResolution\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraResolution\/fragments","op":"replace","value":[{"text":"TruvideoSdkCameraResolution","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraOrientation\/title","value":"TruvideoSdkCameraOrientation"},{"value":[{"kind":"identifier","text":"TruvideoSdkCameraOrientation"}],"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraOrientation\/fragments"}]}]}