{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"presentTruvideoSdkARCameraView","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"isPresented"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Binding","preciseIdentifier":"s:7SwiftUI7BindingV"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"preset"},{"kind":"text","text":": "},{"text":"TruvideoSdkARCameraConfiguration","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkARCameraConfiguration","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkARCameraConfiguration","kind":"typeIdentifier"},{"kind":"text","text":" = .init(flashMode: .off, mode: .videoAndPicture()), "},{"kind":"externalParam","text":"onComplete"},{"text":": ","kind":"text"},{"kind":"attribute","text":"@escaping"},{"text":" (","kind":"text"},{"preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraResult","text":"TruvideoSdkCameraResult","kind":"typeIdentifier","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraResult"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":") -> ","kind":"text"},{"kind":"keyword","text":"some"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:7SwiftUI4ViewP","text":"View","kind":"typeIdentifier"},{"text":"\n","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"content":[{"inlineContent":[{"text":"A boolean indicating whether the preview is presented.","type":"text"}],"type":"paragraph"}],"name":"isPresented"},{"name":"preset","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A preset to configure de AR Camera"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A callback with the recording result"}]}],"name":"onComplete"}],"kind":"parameters"},{"kind":"content","content":[{"text":"Return Value","anchor":"return-value","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"The modified view."}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/SwiftUI\/View\/presentTruvideoSdkARCameraView(isPresented:preset:onComplete:)"},"hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/SwiftUI","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/SwiftUI\/View"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","abstract":[{"type":"text","text":"Present the AR camera view over the full screen"}],"metadata":{"role":"symbol","roleHeading":"Instance Method","externalID":"s:7SwiftUI4ViewP17TruvideoSdkCameraE07presentde8ARCameraC011isPresented6preset10onCompleteQrAA7BindingVySbG_AD0deH13ConfigurationCyAD0deF6ResultCctF","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentTruvideoSdkARCameraView"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"isPresented"},{"kind":"text","text":": "},{"text":"Binding","preciseIdentifier":"s:7SwiftUI7BindingV","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":">, "},{"text":"preset","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkARCameraConfiguration","kind":"typeIdentifier","text":"TruvideoSdkARCameraConfiguration"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"onComplete"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","text":"TruvideoSdkCameraResult","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraResult"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":") -> ","kind":"text"},{"kind":"keyword","text":"some"},{"kind":"text","text":" "},{"text":"View","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP"}],"extendedModule":"SwiftUI","modules":[{"name":"TruvideoSdkCamera","relatedModules":["SwiftUI"]}],"title":"presentTruvideoSdkARCameraView(isPresented:preset:onComplete:)","symbolKind":"method"},"variants":[{"paths":["\/documentation\/truvideosdkcamera\/swiftui\/view\/presenttruvideosdkarcameraview(ispresented:preset:oncomplete:)"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"kind":"symbol","url":"\/documentation\/truvideosdkcamera","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","type":"topic","abstract":[{"text":"Store and capture photos and videos using a fully integrated camera system.","type":"text"}],"title":"TruvideoSdkCamera","role":"collection"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/SwiftUI/View/presentTruvideoSdkARCameraView(isPresented:preset:onComplete:)":{"role":"symbol","type":"topic","url":"\/documentation\/truvideosdkcamera\/swiftui\/view\/presenttruvideosdkarcameraview(ispresented:preset:oncomplete:)","kind":"symbol","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/SwiftUI\/View\/presentTruvideoSdkARCameraView(isPresented:preset:onComplete:)","abstract":[{"type":"text","text":"Present the AR camera view over the full screen"}],"title":"presentTruvideoSdkARCameraView(isPresented:preset:onComplete:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"presentTruvideoSdkARCameraView"},{"text":"(","kind":"text"},{"text":"isPresented","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:7SwiftUI7BindingV","text":"Binding","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"text":"preset","kind":"externalParam"},{"kind":"text","text":": "},{"text":"TruvideoSdkARCameraConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkARCameraConfiguration"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"onComplete"},{"text":": (","kind":"text"},{"preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraResult","text":"TruvideoSdkCameraResult","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":") -> ","kind":"text"},{"kind":"keyword","text":"some"},{"kind":"text","text":" "},{"text":"View","preciseIdentifier":"s:7SwiftUI4ViewP","kind":"typeIdentifier"}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkARCameraConfiguration":{"abstract":[{"type":"text","text":"A configuration object for setting up the AR Camera in "},{"code":"TruvideoSdkCamera","type":"codeVoice"},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TruvideoSdkARCameraConfiguration","kind":"identifier"}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkarcameraconfiguration","type":"topic","role":"symbol","navigatorTitle":[{"text":"TruvideoSdkARCameraConfiguration","kind":"identifier"}],"kind":"symbol","title":"TruvideoSdkARCameraConfiguration","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkARCameraConfiguration"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/SwiftUI/View":{"title":"View","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/SwiftUI\/View","role":"symbol","navigatorTitle":[{"text":"View","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","preciseIdentifier":"s:7SwiftUI4ViewP","text":"View"}],"type":"topic","url":"\/documentation\/truvideosdkcamera\/swiftui\/view","abstract":[]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraResult":{"navigatorTitle":[{"text":"TruvideoSdkCameraResult","kind":"identifier"}],"kind":"symbol","title":"TruvideoSdkCameraResult","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TruvideoSdkCameraResult"}],"type":"topic","role":"symbol","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraresult","abstract":[{"text":"A result of the recording session.","type":"text"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraResult"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/SwiftUI":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/SwiftUI","title":"SwiftUI","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/truvideosdkcamera\/swiftui","abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","value":"TruvideoSdkARCameraConfiguration","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkARCameraConfiguration\/title"},{"value":[{"kind":"identifier","text":"TruvideoSdkARCameraConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkARCameraConfiguration\/fragments"},{"value":"TruvideoSdkCameraResult","op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraResult\/title"},{"value":[{"text":"TruvideoSdkCameraResult","kind":"identifier"}],"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraResult\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}